// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: connector.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secret WHERE id = $1 AND business_id = $2
`

type DeleteSecretParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

// DeleteSecret removes one secret scoped to (id, business); :execrows lets the caller detect a no-op delete.
func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, arg.ID, arg.BusinessID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnector = `-- name: GetConnector :one
SELECT id, business_id, tenant_root_id, type, display_name, base_url, allow_private_base_url, secret_ref, config, status, created_at, updated_at FROM connector WHERE id = $1 AND business_id = $2
`

type GetConnectorParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

// GetConnector fetches one connector scoped to (id, business); foreign/unknown id → no row (→ not-found).
func (q *Queries) GetConnector(ctx context.Context, arg GetConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnector, arg.ID, arg.BusinessID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantRootID,
		&i.Type,
		&i.DisplayName,
		&i.BaseUrl,
		&i.AllowPrivateBaseUrl,
		&i.SecretRef,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT id, business_id, tenant_root_id, scope, sealed_value, created_at, updated_at FROM secret WHERE id = $1 AND business_id = $2
`

type GetSecretParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

// GetSecret fetches one sealed secret scoped to (id, business). RLS + the business predicate
// make a foreign/unknown id return no row (→ not-found).
func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, arg.ID, arg.BusinessID)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantRootID,
		&i.Scope,
		&i.SealedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConnector = `-- name: InsertConnector :one
INSERT INTO connector (id, business_id, tenant_root_id, type, display_name, base_url,
    allow_private_base_url, secret_ref, config, status, created_at, updated_at)
SELECT $1, b.id, b.tenant_root_id, $2::connector_type,
    $3, $4, $5,
    $6, $7, $8, now(), now()
FROM business b
WHERE b.id = $9::uuid
  AND EXISTS (SELECT 1 FROM secret s WHERE s.id = $6 AND s.business_id = b.id)
RETURNING id, business_id, tenant_root_id, type, display_name, base_url, allow_private_base_url, secret_ref, config, status, created_at, updated_at
`

type InsertConnectorParams struct {
	ID                  uuid.UUID     `json:"id"`
	Type                ConnectorType `json:"type"`
	DisplayName         string        `json:"display_name"`
	BaseUrl             string        `json:"base_url"`
	AllowPrivateBaseUrl bool          `json:"allow_private_base_url"`
	SecretRef           uuid.UUID     `json:"secret_ref"`
	Config              []byte        `json:"config"`
	Status              string        `json:"status"`
	BusinessID          uuid.UUID     `json:"business_id"`
}

// InsertConnector derives tenant_root_id from the RLS-visible business AND requires secret_ref to
// belong to the SAME business (defense-in-depth beyond the same-tenant FK). Unknown business or
// foreign secret → zero rows.
func (q *Queries) InsertConnector(ctx context.Context, arg InsertConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, insertConnector,
		arg.ID,
		arg.Type,
		arg.DisplayName,
		arg.BaseUrl,
		arg.AllowPrivateBaseUrl,
		arg.SecretRef,
		arg.Config,
		arg.Status,
		arg.BusinessID,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantRootID,
		&i.Type,
		&i.DisplayName,
		&i.BaseUrl,
		&i.AllowPrivateBaseUrl,
		&i.SecretRef,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSecret = `-- name: InsertSecret :one
INSERT INTO secret (id, business_id, tenant_root_id, scope, sealed_value, created_at, updated_at)
SELECT $1, b.id, b.tenant_root_id, $2, $3, now(), now()
FROM business b
WHERE b.id = $4::uuid
RETURNING id, business_id, tenant_root_id, scope, sealed_value, created_at, updated_at
`

type InsertSecretParams struct {
	ID          uuid.UUID `json:"id"`
	Scope       string    `json:"scope"`
	SealedValue string    `json:"sealed_value"`
	BusinessID  uuid.UUID `json:"business_id"`
}

// InsertSecret seals-then-stores: caller passes a pre-generated id + the sealed ciphertext.
// tenant_root_id is derived from the (RLS-visible) business, so an invisible business inserts zero rows.
func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, insertSecret,
		arg.ID,
		arg.Scope,
		arg.SealedValue,
		arg.BusinessID,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantRootID,
		&i.Scope,
		&i.SealedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :execrows
INSERT INTO connector_webhook_delivery (id, business_id, tenant_root_id, connector_id, external_delivery_id, received_at)
SELECT $1, b.id, b.tenant_root_id, $2, $3, now()
FROM business b
WHERE b.id = $4::uuid
  AND EXISTS (SELECT 1 FROM connector c WHERE c.id = $2 AND c.business_id = b.id)
ON CONFLICT (connector_id, external_delivery_id) DO NOTHING
`

type RecordWebhookDeliveryParams struct {
	ID                 uuid.UUID `json:"id"`
	ConnectorID        uuid.UUID `json:"connector_id"`
	ExternalDeliveryID string    `json:"external_delivery_id"`
	BusinessID         uuid.UUID `json:"business_id"`
}

// RecordWebhookDelivery dedupes inbound webhook deliveries per connector: ON CONFLICT
// DO NOTHING means a replayed external_delivery_id inserts zero rows, which the caller
// reads as "already seen". tenant_root derived from the RLS-visible business; the EXISTS
// guard requires connector_id to belong to the SAME business (defense-in-depth).
func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWebhookDelivery,
		arg.ID,
		arg.ConnectorID,
		arg.ExternalDeliveryID,
		arg.BusinessID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
