// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Serializes structural mutations within a tenant (research R5).
	AcquireTenantLock(ctx context.Context, hashtext string) error
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AllPermissionKeys(ctx context.Context) ([]string, error)
	ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error
	ConsumeOneTimeToken(ctx context.Context, arg ConsumeOneTimeTokenParams) (OneTimeToken, error)
	CountActiveChildren(ctx context.Context, parentID pgtype.UUID) (int64, error)
	// Direct Owners (locked role) whose membership is AT this business. At the tenant
	// root this is the last-Owner count guarded by FR-014/FR-024.
	CountDirectOwners(ctx context.Context, businessID uuid.UUID) (int64, error)
	CountRoleMemberships(ctx context.Context, roleID uuid.UUID) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// CreateBusiness uses :exec (no RETURNING): under RLS, INSERT ... RETURNING
	// applies the SELECT/USING policy to the returned row, which the creator cannot
	// yet see (no membership at insert time). The caller builds the result from inputs.
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) error
	CreateHumanPrincipal(ctx context.Context, arg CreateHumanPrincipalParams) (Principal, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) error
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreateOneTimeToken(ctx context.Context, arg CreateOneTimeTokenParams) (OneTimeToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	// Removes a principal's DIRECT membership at a business (revoke / leave).
	// Inherited access from ancestors is unaffected (edge: grants are independent).
	DeleteMembershipAt(ctx context.Context, arg DeleteMembershipAtParams) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DepthFromRoot(ctx context.Context, arg DepthFromRootParams) (int32, error)
	// Effective permissions for a principal at a business: the union of permissions
	// from every grant the principal holds on the business or any non-archived
	// ancestor (downward-only inheritance, FR-010). The locked Owner role is handled
	// separately (HasOwnerRole + AllPermissionKeys) so future catalog additions are
	// covered automatically (research R3).
	EffectivePermissions(ctx context.Context, arg EffectivePermissionsParams) ([]string, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByPrincipal(ctx context.Context, id uuid.UUID) (Account, error)
	GetBusiness(ctx context.Context, id uuid.UUID) (Business, error)
	// A tenant-owned (non-preset) role; presets have NULL tenant_root_id and never match.
	GetCustomRole(ctx context.Context, arg GetCustomRoleParams) (GetCustomRoleRow, error)
	// ---- Member role management (T063) ----
	// The target principal's direct membership at a business. RLS scopes this to the
	// caller's authorized subtree, so an admin can read members of a business they
	// administer while a bare member sees only their own row.
	GetMembershipAt(ctx context.Context, arg GetMembershipAtParams) (GetMembershipAtRow, error)
	GetPendingInvitation(ctx context.Context, arg GetPendingInvitationParams) (GetPendingInvitationRow, error)
	GetPrincipalByAccount(ctx context.Context, accountID pgtype.UUID) (Principal, error)
	// The kind ('human'|'agent') of a principal; ownership may pass only to a human.
	GetPrincipalKind(ctx context.Context, id uuid.UUID) (string, error)
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error)
	// A role assignable within the tenant (a preset, or one the tenant owns), with
	// the bits the assignment guard needs (is_locked marks the full-access Owner role).
	GetRoleInTenant(ctx context.Context, arg GetRoleInTenantParams) (GetRoleInTenantRow, error)
	GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error)
	HasOwnerRole(ctx context.Context, arg HasOwnerRoleParams) (bool, error)
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	// Link a new child ($1) under parent ($2): inherit the parent's ancestor chain
	// (+1 depth). The child's self row is inserted separately via InsertClosureSelf.
	InsertChildClosure(ctx context.Context, arg InsertChildClosureParams) error
	InsertClosureSelf(ctx context.Context, arg InsertClosureSelfParams) error
	IsAccountVerifiedByPrincipal(ctx context.Context, id uuid.UUID) (bool, error)
	// True if candidate ($2) is the node ($1) itself or a descendant of it.
	IsDescendant(ctx context.Context, arg IsDescendantParams) (bool, error)
	// A business's audit trail, newest first, keyset-paginated on (created_at, id).
	// The first page passes a far-future sentinel cursor so the predicate is uniform.
	// RLS scopes audit_entry to the caller's authorized businesses; the service
	// additionally gates on audit.read. Projection omits new_value/old_value.
	ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]ListAuditEntriesRow, error)
	// RLS scopes the result to businesses the caller can see.
	ListBusinesses(ctx context.Context) ([]Business, error)
	ListInvitations(ctx context.Context, businessID uuid.UUID) ([]ListInvitationsRow, error)
	// Keyset pagination over the global catalog; pass '' as the cursor for the first
	// page and the last returned key thereafter. Fetch limit+1 to detect a next page.
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error)
	// Presets (tenant_root_id IS NULL) plus the tenant's custom roles. RLS scopes
	// this to roles the caller may see; the predicate narrows to one tenant.
	ListTenantRoles(ctx context.Context, tenantRootID pgtype.UUID) ([]ListTenantRolesRow, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error
	OwnerRoleID(ctx context.Context) (uuid.UUID, error)
	// The id of a built-in preset role by key (owner/admin/member/viewer).
	PresetRoleID(ctx context.Context, key string) (uuid.UUID, error)
	// Subtree move is performed by the SECURITY DEFINER move_business() function
	// (migration 0009), invoked via tx.Exec from the service so the closure rewrite
	// is RLS-exempt (the moved subtree is transiently unauthorized mid-rewrite).
	RenameBusiness(ctx context.Context, arg RenameBusinessParams) error
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (uuid.UUID, error)
	RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error
	// Invitation lifecycle queries. Create/list/revoke/resend run under the inviter's
	// principal (a member with members.manage), so RLS scopes them to the business.
	// Acceptance is handled by the accept_invitation() SECURITY DEFINER function
	// (invitees are not yet members), invoked via raw SQL in the service.
	// A role assignable within the tenant: a preset (NULL tenant) or the tenant's own.
	RoleVisibleInTenant(ctx context.Context, arg RoleVisibleInTenantParams) (uuid.UUID, error)
	RotateInvitationToken(ctx context.Context, arg RotateInvitationTokenParams) (uuid.UUID, error)
	SetSubtreeStatus(ctx context.Context, arg SetSubtreeStatusParams) error
	SoftDeleteBusiness(ctx context.Context, id uuid.UUID) error
	SubtreeHeight(ctx context.Context, ancestorID uuid.UUID) (int32, error)
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (Account, error)
	// Reassigns a member's role at a business, recording who made the change. :exec
	// (no RETURNING): RLS can hide the just-updated row from the caller (42501).
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error
	UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) error
}

var _ Querier = (*Queries)(nil)
