// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Per-agent usage rollup for a business over [from_ts, to_ts). LEFT JOIN so agents
	// with zero runs in the window still appear (with zeros). RLS on agent + agent_run
	// (under WithPrincipal) scopes to the caller's businesses; the business_id arg narrows.
	// The window filter on r.created_at + r.agent_id rides agent_run_agent_month_idx (0028).
	AccountingSummaryByAgent(ctx context.Context, arg AccountingSummaryByAgentParams) ([]AccountingSummaryByAgentRow, error)
	// Serializes structural mutations within a tenant (research R5).
	AcquireTenantLock(ctx context.Context, hashtext string) error
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	// Sum of cost across this agent's runs in the current calendar month (UTC).
	AgentMonthToDateCostCents(ctx context.Context, arg AgentMonthToDateCostCentsParams) (int64, error)
	AllPermissionKeys(ctx context.Context) ([]string, error)
	// BlankTicketAttachments blanks attachment filenames on a ticket (the blob bytes are
	// purged out-of-band via attachment.purge). Returns the count blanked — the audit
	// scope count. Joined through ticket_message so it stays scoped to one ticket.
	BlankTicketAttachments(ctx context.Context, arg BlankTicketAttachmentsParams) (int64, error)
	// BlankTicketMessages blanks every message body on a ticket (FR-014). Returns the
	// number of messages blanked — the audit scope count. Scoped to (ticket_id, business_id).
	BlankTicketMessages(ctx context.Context, arg BlankTicketMessagesParams) (int64, error)
	// BumpTicketActivity touches the denormalized last_message_at/updated_at after a
	// new message; runs in the same tx as the message insert.
	BumpTicketActivity(ctx context.Context, arg BumpTicketActivityParams) error
	ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error
	// ConnectorWebhookContext returns the connector's tenancy + base_url + allow_private_base_url +
	// sealed credential blob for the principal-less webhook handler to build the typed connector
	// and verify the HMAC signature in Go. Returns no row if the connector does not exist or is
	// not enabled. Inlined so sqlc can infer column types (sqlc cannot introspect SECURITY DEFINER
	// TABLE function returns without the function in schema.sql). Migration 0043 extended the
	// DEFINER fn to return base_url + allow_private_base_url; the inline query mirrors that.
	ConnectorWebhookContext(ctx context.Context, id uuid.UUID) (ConnectorWebhookContextRow, error)
	ConsumeOneTimeToken(ctx context.Context, arg ConsumeOneTimeTokenParams) (OneTimeToken, error)
	CountActiveChildren(ctx context.Context, parentID pgtype.UUID) (int64, error)
	// Direct Owners (locked role) whose membership is AT this business. At the tenant
	// root this is the last-Owner count guarded by FR-014/FR-024.
	CountDirectOwners(ctx context.Context, businessID uuid.UUID) (int64, error)
	// Count detached (native) tickets in this business that belong to the connector's provider host
	// (same scheme://host as base_url). Used to derive the skipped-duplicate count after relink.
	CountReadoptableTickets(ctx context.Context, arg CountReadoptableTicketsParams) (int64, error)
	CountRoleMemberships(ctx context.Context, roleID uuid.UUID) (int64, error)
	// CountTicketMessages is the message_count facet of the Ticket schema.
	CountTicketMessages(ctx context.Context, arg CountTicketMessagesParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, principalID uuid.UUID) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// CreateAgent inserts an agent definition. tenant_root_id is derived from the
	// business row (RLS-gated). Duplicate (business_id, name) → 23505 → 409.
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	// Agent runtime (spec 003 US2) — agent definition queries. Every query runs inside
	// the caller's RLS principal context (db.WithPrincipal) AND pushes the
	// (business_id, …) ownership predicate into SQL (dual enforcement, mirroring ai.sql).
	// tenant_root_id is derived from the business row on insert.
	// CreateAgentPrincipal creates the kind='agent' principal for a new agent, homed at
	// and tenant-scoped to the business. INSERT…SELECT FROM business gates on RLS
	// visibility: an invisible business yields no row → ErrNoRows → 404 (no oracle).
	// principal is not RLS-scoped, so the gate lives in the business SELECT.
	CreateAgentPrincipal(ctx context.Context, arg CreateAgentPrincipalParams) (uuid.UUID, error)
	// Insert a run, deriving tenant_root_id from the (RLS-visible) agent. An invisible
	// or foreign agent yields no row -> pgx.ErrNoRows -> no-oracle 404.
	CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error)
	// Insert a pending item, deriving tenant_root_id from the (RLS-visible) parent run.
	// An invisible/foreign run yields no row -> pgx.ErrNoRows -> no-oracle not-found.
	// TTL is passed in seconds (make_interval avoids a pgtype.Interval param).
	CreateApprovalItem(ctx context.Context, arg CreateApprovalItemParams) (ApprovalItem, error)
	// CreateBusiness uses :exec (no RETURNING): under RLS, INSERT ... RETURNING
	// applies the SELECT/USING policy to the returned row, which the creator cannot
	// yet see (no membership at insert time). The caller builds the result from inputs.
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) error
	// Idempotent event-triggered run. Dedups on (agent_id, trigger_dedup_key) -- the conflict
	// target matches the partial unique index -- so an at-least-once redelivery of
	// ticket.created creates at most one run per agent. ON CONFLICT DO NOTHING => 0 rows =>
	// pgx.ErrNoRows in the caller, which maps it to "already enqueued" (created=false).
	// tenant_root_id is derived from the (agent-principal-visible) agent row, never supplied.
	CreateEventAgentRun(ctx context.Context, arg CreateEventAgentRunParams) (AgentRun, error)
	CreateHumanPrincipal(ctx context.Context, arg CreateHumanPrincipalParams) (Principal, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) error
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreateOneTimeToken(ctx context.Context, arg CreateOneTimeTokenParams) (OneTimeToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	// ---- Account lifecycle (T077, FR-028) ----
	// Reversible deactivation; Login already denies any non-active account (FR-026).
	DeactivateAccount(ctx context.Context, id uuid.UUID) error
	// Transition pending -> approved|denied iff still pending AND not past expiry. A row
	// that is already decided/expired returns no row (caller maps to 409 conflict).
	DecideApprovalItem(ctx context.Context, arg DecideApprovalItemParams) (ApprovalItem, error)
	// DeleteAIProviderCredential deletes a credential by (id, business_id).
	// Returns rows-affected so the service can map 0 => ErrNotFound.
	DeleteAIProviderCredential(ctx context.Context, arg DeleteAIProviderCredentialParams) (int64, error)
	// DeleteAgent atomically deletes the agent and its kind='agent' principal. The agent
	// row is deleted first (it FKs the principal), then the principal. rows-affected (the
	// principal delete) = 0 when the agent doesn't exist / isn't visible → 404 (no oracle).
	DeleteAgent(ctx context.Context, arg DeleteAgentParams) (int64, error)
	// DeleteCompany hard-deletes a company scoped to (id, tenant_root_id) (companies carry no
	// PII / soft-delete column). The contact.company_id → company FK is NO ACTION (restrict),
	// so the service nulls out contacts' company_id (DetachContactsFromCompany) in the same tx
	// immediately before this delete — otherwise an in-use company would raise SQLSTATE 23503.
	DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error
	// DeleteConnectorOutboundOps cascades the outbound op queue for a connector.
	DeleteConnectorOutboundOps(ctx context.Context, connectorID uuid.UUID) (int64, error)
	// DeleteConnectorRow removes the connector row, scoped to (id, business_id). Run AFTER the
	// detach + cascade (those clear FKs into connector) and BEFORE Vault.Delete (the connector
	// still references secret_ref until this runs).
	DeleteConnectorRow(ctx context.Context, arg DeleteConnectorRowParams) (int64, error)
	// DeleteConnectorSyncState cascades the per-ticket sync bookkeeping for a connector.
	DeleteConnectorSyncState(ctx context.Context, connectorID uuid.UUID) (int64, error)
	// DeleteConnectorWebhookDeliveries cascades the inbound webhook-dedup rows for a connector.
	DeleteConnectorWebhookDeliveries(ctx context.Context, connectorID uuid.UUID) (int64, error)
	// DeleteMCPServer deletes an MCP server by (id, business_id).
	// Returns rows-affected so the service can map 0 => ErrNotFound.
	DeleteMCPServer(ctx context.Context, arg DeleteMCPServerParams) (int64, error)
	DeleteMCPToolPolicy(ctx context.Context, arg DeleteMCPToolPolicyParams) (int64, error)
	// Removes a principal's DIRECT membership at a business (revoke / leave).
	// Inherited access from ancestors is unaffected (edge: grants are independent).
	DeleteMembershipAt(ctx context.Context, arg DeleteMembershipAtParams) error
	// DeleteRepoConnector removes one connector scoped to the business (RLS + explicit
	// predicate). Cascades to its code_review rows via the existing FK.
	DeleteRepoConnector(ctx context.Context, arg DeleteRepoConnectorParams) (int64, error)
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	// DeleteSecret removes one secret scoped to (id, business); :execrows lets the caller detect a no-op delete.
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error)
	// DeleteTicketTags removes every tag row for a ticket — the first half of a
	// full-set tag replacement. Scoped to (ticket_id, business_id).
	DeleteTicketTags(ctx context.Context, arg DeleteTicketTagsParams) error
	DepthFromRoot(ctx context.Context, arg DepthFromRootParams) (int32, error)
	// DetachContactsFromCompany nulls out company_id on every contact pointing at a company,
	// scoped to (company_id, tenant_root_id). The contact.company_id → company FK is NO ACTION
	// (restrict), so a company with contacts cannot be hard-deleted until they are detached;
	// the service runs this in the same tx immediately before DeleteCompany. Touches updated_at.
	DetachContactsFromCompany(ctx context.Context, arg DetachContactsFromCompanyParams) error
	// DetachTicketMessagesFromConnector — same sever for message-level external linkage.
	DetachTicketMessagesFromConnector(ctx context.Context, connectorID pgtype.UUID) (int64, error)
	// DetachTicketsFromConnector severs linked tickets on hard-delete: NULL connector_id only,
	// PRESERVING external_id/external_url as read-only history. Permitted by
	// CHECK(connector_id IS NULL OR external_id IS NOT NULL) — the NULL-connector clause passes.
	// Scoped by connector_id (a globally-unique uuid the caller already confirmed it owns).
	DetachTicketsFromConnector(ctx context.Context, connectorID pgtype.UUID) (int64, error)
	// DismissFailedOps acknowledges a connector's failed outbound ops without retrying: failed →
	// dismissed (a terminal, non-degrading state kept for audit/forensics). Health counts
	// status='failed', so dismissing clears 'degraded' (manyforge-xfj). Same (connector_id,
	// business_id) scoping as RetryFailedOps. Returns the number dismissed.
	DismissFailedOps(ctx context.Context, arg DismissFailedOpsParams) (int64, error)
	// Effective permissions for a principal at a business: the union of permissions
	// from every grant the principal holds on the business or any non-archived
	// ancestor (downward-only inheritance, FR-010). The locked Owner role is handled
	// separately (HasOwnerRole + AllPermissionKeys) so future catalog additions are
	// covered automatically (research R3).
	EffectivePermissions(ctx context.Context, arg EffectivePermissionsParams) ([]string, error)
	// EnqueueOutboundComment records a pending 'comment' outbound op for a connector-linked
	// ticket, in the caller's (principal) tx. The ownership predicate is pushed into SQL: the
	// row is inserted ONLY if the ticket is owned by the business AND is connector-linked, and
	// connector_id/tenant_root_id are derived from that ticket row (defense-in-depth beyond RLS).
	EnqueueOutboundComment(ctx context.Context, arg EnqueueOutboundCommentParams) error
	// EnqueueOutboundCreate records a pending 'create_issue' op linking an as-yet-unlinked
	// native ticket to a connector. Inserted ONLY if the ticket is owned + NOT already linked.
	// connector_id is supplied (not derived) because the ticket isn't linked yet; tenant_root_id
	// comes from the ticket. The connector's own tenancy is re-checked via the composite FK.
	EnqueueOutboundCreate(ctx context.Context, arg EnqueueOutboundCreateParams) (int64, error)
	// EnqueueOutboundTransition records a pending 'transition' outbound op for a connector-linked
	// ticket, in the caller's (principal) tx. Ownership is pushed into SQL (id + business_id +
	// connector-linked) and connector_id/tenant_root_id are derived from the ticket row. The
	// NOT EXISTS guard dedups: a second identical enqueue while a same-status transition is still
	// pending/in_progress is a no-op (idempotent agent retries do not pile up duplicate ops).
	EnqueueOutboundTransition(ctx context.Context, arg EnqueueOutboundTransitionParams) error
	// Notify/events queries (spec 002, SL-C/SL-D). Plain table ops only; the
	// SECURITY DEFINER drain functions (claim_outbox_batch / mark_outbox_processed /
	// reschedule_outbox) are called via raw pgx in internal/platform/events (sqlc
	// can't resolve a function's RETURNS columns — functions aren't in db/schema.sql,
	// mirroring how the foundation calls accept_invitation).
	// ---- outbox (SL-C) ----
	// Enqueue a side-effect in the SAME transaction as the source mutation. Rides
	// the WITH CHECK (true) policy, so it works with or without a principal context.
	EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error
	// The caller's own grants (data portability). RLS scopes business/role joins to
	// what the caller may already see; their own memberships are always visible.
	ExportMembershipsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]ExportMembershipsForPrincipalRow, error)
	// NOTE (manyforge-deo.11): there is intentionally NO UpdateAIProviderCredential query
	// yet. When one is added it MUST include allow_private_base_url (and the service must
	// re-validate it via validateBaseURL and re-audit the trust grant) — otherwise an update
	// built from a partial body silently zeros the SSRF trust flag, demoting a trusted
	// self-host credential to the locked-down dialer (or leaving a stale trust the operator
	// believes was revoked). Pinned in
	// internal/security_regression/ai_credential_update_pin_test.go.
	// GetAIProviderCredential loads a credential by (business_id, provider) — the
	// ownership predicate. RLS scopes rows to the caller's authorized businesses;
	// the explicit business_id is defense in depth. pgx.ErrNoRows => ErrNotFound.
	GetAIProviderCredential(ctx context.Context, arg GetAIProviderCredentialParams) (AiProviderCredential, error)
	// GetAIProviderCredentialByID loads a credential by (id, business_id) — the
	// ownership predicate. Used when the caller holds the UUID directly.
	GetAIProviderCredentialByID(ctx context.Context, arg GetAIProviderCredentialByIDParams) (AiProviderCredential, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByPrincipal(ctx context.Context, id uuid.UUID) (Account, error)
	// GetAgent loads an agent by (id, business_id) — the ownership predicate. RLS
	// scopes rows to the caller's authorized businesses; the explicit business_id is
	// defense in depth. pgx.ErrNoRows => ErrNotFound.
	GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error)
	// Scope the read by agent_id too (not just business_id): a same-business request for
	// run R via a DIFFERENT agent's path yields no row -> pgx.ErrNoRows -> no-oracle 404.
	GetAgentRun(ctx context.Context, arg GetAgentRunParams) (AgentRun, error)
	// Business-scoped read (RLS + predicate). Unknown/foreign id -> pgx.ErrNoRows -> 404.
	GetApprovalItem(ctx context.Context, arg GetApprovalItemParams) (ApprovalItem, error)
	GetBusiness(ctx context.Context, id uuid.UUID) (Business, error)
	GetCodeReview(ctx context.Context, arg GetCodeReviewParams) (CodeReview, error)
	// GetCompany loads a single company scoped to (id, tenant_root_id) — the ownership
	// predicate. pgx.ErrNoRows ⇒ ErrNotFound (no oracle).
	GetCompany(ctx context.Context, arg GetCompanyParams) (Company, error)
	// GetConnector fetches one connector scoped to (id, business); foreign/unknown id → no row (→ not-found).
	GetConnector(ctx context.Context, arg GetConnectorParams) (Connector, error)
	// GetConnectorHealth returns the same aggregates for a single connector (used by Get). The
	// caller has already confirmed ownership via GetConnector; RLS still scopes the subqueries.
	GetConnectorHealth(ctx context.Context, connectorID pgtype.UUID) (GetConnectorHealthRow, error)
	// GetContact loads a single live contact scoped to (id, tenant_root_id) — the ownership
	// predicate. deleted_at IS NULL excludes soft-deleted rows; pgx.ErrNoRows ⇒ ErrNotFound
	// (foreign-tenant / unknown / deleted all collapse to one no-oracle 404 shape).
	GetContact(ctx context.Context, arg GetContactParams) (Contact, error)
	// GetContactByEmail looks up a live contact by (tenant_root_id, primary_email) — the
	// dedup probe before requester linkage.
	GetContactByEmail(ctx context.Context, arg GetContactByEmailParams) (Contact, error)
	// A tenant-owned (non-preset) role; presets have NULL tenant_root_id and never match.
	GetCustomRole(ctx context.Context, arg GetCustomRoleParams) (GetCustomRoleRow, error)
	// GetEmailDomain loads a single email domain scoped to (id, business_id) — the
	// ownership predicate. RLS already scopes rows to the caller's authorized
	// businesses; the explicit business_id is defense in depth. pgx.ErrNoRows ⇒ the
	// service maps to ErrNotFound (unknown / other-business / unauthorized are all 404).
	GetEmailDomain(ctx context.Context, arg GetEmailDomainParams) (EmailDomain, error)
	// GetEnabledMCPServerByID resolves one enabled server by id under RLS (+ explicit business_id).
	// Used by the tool-discovery endpoint to connect. pgx.ErrNoRows => ErrNotFound (no oracle).
	GetEnabledMCPServerByID(ctx context.Context, arg GetEnabledMCPServerByIDParams) (McpServer, error)
	// GetEnabledMCPServerByName fetches a single enabled MCP server by (business_id, name).
	// Used by ApprovalExecutor to resolve the server for an approved mcp: tool call.
	// RLS scopes rows to the caller's authorized businesses; the explicit business_id is
	// defense in depth. pgx.ErrNoRows => ErrNotFound (cross-tenant names are invisible).
	GetEnabledMCPServerByName(ctx context.Context, arg GetEnabledMCPServerByNameParams) (McpServer, error)
	GetErasureSchedule(ctx context.Context, accountID uuid.UUID) (GetErasureScheduleRow, error)
	// GetMCPServerByID loads an MCP server by (id, business_id) — the ownership
	// predicate. RLS scopes rows to the caller's authorized businesses; the explicit
	// business_id is defense in depth. pgx.ErrNoRows => ErrNotFound.
	GetMCPServerByID(ctx context.Context, arg GetMCPServerByIDParams) (McpServer, error)
	GetMCPToolPolicy(ctx context.Context, arg GetMCPToolPolicyParams) (McpToolPolicy, error)
	// ---- Member role management (T063) ----
	// The target principal's direct membership at a business. RLS scopes this to the
	// caller's authorized subtree, so an admin can read members of a business they
	// administer while a bare member sees only their own row.
	GetMembershipAt(ctx context.Context, arg GetMembershipAtParams) (GetMembershipAtRow, error)
	// GetOutboundMessageByApproval looks up the (single) message a given approval produced,
	// for the dedup short-circuit. Business-scoped; pgx.ErrNoRows ⇒ none yet.
	GetOutboundMessageByApproval(ctx context.Context, arg GetOutboundMessageByApprovalParams) (TicketMessage, error)
	GetPendingInvitation(ctx context.Context, arg GetPendingInvitationParams) (GetPendingInvitationRow, error)
	GetPrincipalByAccount(ctx context.Context, accountID pgtype.UUID) (Principal, error)
	// The kind ('human'|'agent') of a principal; ownership may pass only to a human.
	GetPrincipalKind(ctx context.Context, id uuid.UUID) (string, error)
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRepoConnector(ctx context.Context, id uuid.UUID) (RepoConnector, error)
	// GetRequester loads a single requester scoped to (id, business_id) — the
	// ownership predicate. pgx.ErrNoRows ⇒ ErrNotFound (no oracle).
	GetRequester(ctx context.Context, arg GetRequesterParams) (Requester, error)
	// GetRequesterForTicket loads the embedded Requester for a ticket via its
	// requester_id, scoped to the same business. Returned inline in the Ticket schema.
	GetRequesterForTicket(ctx context.Context, arg GetRequesterForTicketParams) (Requester, error)
	// A role assignable within the tenant (a preset, or one the tenant owns), with
	// the bits the assignment guard needs (is_locked marks the full-access Owner role).
	GetRoleInTenant(ctx context.Context, arg GetRoleInTenantParams) (GetRoleInTenantRow, error)
	GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error)
	// The acting agent principal + the run's correlation id, so an approval executes as
	// the agent and its audit rows join to the originating run by correlation.
	GetRunActorForApproval(ctx context.Context, arg GetRunActorForApprovalParams) (GetRunActorForApprovalRow, error)
	// GetSecret fetches one sealed secret scoped to (id, business). RLS + the business predicate
	// make a foreign/unknown id return no row (→ not-found).
	GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error)
	// ---- US2 write / threading queries ----
	// GetThreadingParent loads the latest message on a ticket (any direction) — its
	// message_id becomes the new outbound In-Reply-To; its references chain (+ its own
	// id) becomes References.
	GetThreadingParent(ctx context.Context, arg GetThreadingParentParams) (GetThreadingParentRow, error)
	// GetTicket loads a single ticket scoped to (id, business_id) — the service-layer
	// ownership predicate. RLS already scopes rows to the caller's authorized
	// businesses; the explicit business_id is defense in depth. pgx.ErrNoRows ⇒ the
	// service maps to ErrNotFound (unknown / other-business / unauthorized are all 404).
	GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error)
	// GetTicketConnectorRef returns the connector linkage (connector_id, external_id) for a
	// connector-linked ticket owned by the business. Ownership is pushed into SQL (id + business_id
	// + connector-linked); a cross-business or unknown id returns no row (pgx.ErrNoRows -> 404, no
	// UUID-existence oracle). The agent read/write tools resolve a native ticket's external handle
	// through this before calling the connector.
	GetTicketConnectorRef(ctx context.Context, arg GetTicketConnectorRefParams) (GetTicketConnectorRefRow, error)
	HasOwnerRole(ctx context.Context, arg HasOwnerRoleParams) (bool, error)
	// Agent runtime (spec 003 US1a) — per-business BYO provider credential queries.
	// Every query runs inside the caller's RLS principal context (db.WithPrincipal)
	// AND pushes the (business_id, …) ownership predicate into SQL (dual enforcement,
	// mirroring identity.sql). tenant_root_id is derived from the business row on
	// insert so the FK + tenant scope come from the parent row.
	// InsertAIProviderCredential creates a BYO credential for a business. tenant_root_id
	// is derived from the business row (RLS-scoped: a business the caller cannot see
	// returns no row, so the NOT NULL column rejects the insert → service maps to 404).
	// Duplicate (business_id, provider) → unique violation → 409.
	InsertAIProviderCredential(ctx context.Context, arg InsertAIProviderCredentialParams) (AiProviderCredential, error)
	// ---- activity ----
	// InsertActivityEntry is the idempotent recorder (mirrors audit.Write): it takes a tx and a
	// trusted tenant_root_id, running on an RLS-set (principal-scoped) or RLS-exempt (DEFINER) tx.
	// source_id-bearing events dedupe on activity_dedup_idx; NULL-source events always insert.
	InsertActivityEntry(ctx context.Context, arg InsertActivityEntryParams) error
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	// Link a new child ($1) under parent ($2): inherit the parent's ancestor chain
	// (+1 depth). The child's self row is inserted separately via InsertClosureSelf.
	InsertChildClosure(ctx context.Context, arg InsertChildClosureParams) error
	InsertClosureSelf(ctx context.Context, arg InsertClosureSelfParams) error
	InsertCodeReview(ctx context.Context, arg InsertCodeReviewParams) (CodeReview, error)
	// ---- companies ----
	// InsertCompany creates a company unconditionally (no upsert).
	InsertCompany(ctx context.Context, arg InsertCompanyParams) (Company, error)
	// InsertConnector derives tenant_root_id from the RLS-visible business AND requires secret_ref to
	// belong to the SAME business (defense-in-depth beyond the same-tenant FK). Unknown business or
	// foreign secret → zero rows.
	InsertConnector(ctx context.Context, arg InsertConnectorParams) (Connector, error)
	// CRM read/write queries (spec 005, Task 3). contact + company are tenant-wide tables
	// keyed on tenant_root_id (NOT business-scoped) — a contact/company is shared across
	// every business in the tenant tree (the CRM lives above the support-desk seam). Every
	// query runs inside the caller's RLS principal context (db.WithPrincipal); in addition,
	// every id-taking query also filters on tenant_root_id, pushing the ownership predicate
	// into SQL (dual enforcement) so a foreign-tenant id matches zero rows ⇒ ErrNotFound
	// (no existence oracle). The generated methods are consumed by ContactService/CompanyService
	// (Tasks 4-6).
	//
	// INSERTs pass id + created_at/updated_at explicitly (id = $1, timestamps = now()),
	// matching the dominant repo convention (db/query/account.sql, tenancy.sql, etc.) rather
	// than relying on column DEFAULTs — db/schema.sql (sqlc's input) carries no DEFAULTs even
	// though migration 0057 does, so explicit values keep the two from diverging.
	//
	// Keyset pagination follows ticketing.sql: a first-page query (no cursor) plus an *After
	// continuation that compares the full row-value (sort_col, id) tuple so non-unique sort
	// keys (company.name, and contact.primary_email under soft-delete reuse) never skip or
	// duplicate rows at a tie boundary. lim is the clamped limit + 1 so the service detects
	// a further page. The partial-index ON CONFLICT clauses mirror the partial UNIQUE indexes
	// from migration 0057 (contact_tenant_email_uq WHERE deleted_at IS NULL,
	// company_tenant_domain_uq WHERE domain IS NOT NULL) so Postgres can infer the arbiter.
	// ---- contacts ----
	// InsertContact creates a contact unconditionally (no upsert) — used when the caller
	// already knows the contact is new. Conflicts on the partial unique index surface as
	// an error the service maps to ErrConflict.
	InsertContact(ctx context.Context, arg InsertContactParams) (Contact, error)
	// ---- inbound_address ----
	// InsertCustomInboundAddress creates a kind='custom' inbound address bound to an
	// email_domain that MUST be owned by the business AND verified — both enforced in
	// this single statement: the SELECT joins the email_domain row scoped to
	// (id, business_id) with verified_at IS NOT NULL, so an unowned/unknown domain
	// yields zero rows (service → 404) and an owned-but-unverified domain also yields
	// zero rows (the service distinguishes the two with a prior GetEmailDomain to map
	// unverified → 409). tenant_root_id comes from the domain row (same tenant). A
	// duplicate (tenant_root_id, address) raises a unique violation → 409.
	InsertCustomInboundAddress(ctx context.Context, arg InsertCustomInboundAddressParams) (InboundAddress, error)
	// US4 inbox-management identity queries (spec 002, T055/T056/T058): custom email
	// domains, their DNS-verification lifecycle, and custom inbound addresses. Plain-table
	// CRUD only — every query runs inside the caller's RLS principal context
	// (db.WithPrincipal) AND pushes the (business_id, …) ownership predicate into SQL
	// (dual enforcement, mirroring ticketing.sql). The principal-less inbound routing /
	// send-identity primitives are SECURITY DEFINER functions (resolve_inbound_address /
	// get_send_identity) invoked via raw pgx — sqlc cannot type a function's RETURNS, so
	// they are NOT here. Keyset pagination uses limit+1 so the service detects a next page.
	// ---- email_domain ----
	// InsertEmailDomain creates a custom email domain for a business. tenant_root_id is
	// derived from the business row (RLS-scoped: the subselect returns no row for a
	// business the caller cannot see, so the NOT NULL column rejects the insert → the
	// service maps it to a no-oracle not-found). dkim_* are populated at create time
	// (the challenge shows both TXT records at once); verified_at stays NULL until the
	// TXT challenge passes. Duplicate (tenant_root_id, domain) → unique violation → 409.
	InsertEmailDomain(ctx context.Context, arg InsertEmailDomainParams) (EmailDomain, error)
	// Agent runtime (spec 003 US6) — per-business MCP server registry queries.
	// Every query runs inside the caller's RLS principal context (db.WithPrincipal)
	// AND pushes the (business_id, …) ownership predicate into SQL (dual enforcement,
	// mirroring identity.sql). tenant_root_id is derived from the business row on
	// insert so the FK + tenant scope come from the parent row.
	// InsertMCPServer creates an MCP server record for a business. tenant_root_id
	// is derived from the business row (RLS-scoped: a business the caller cannot see
	// returns no row, so the NOT NULL column rejects the insert → service maps to 404).
	// Duplicate (business_id, name) → unique violation → 409.
	InsertMCPServer(ctx context.Context, arg InsertMCPServerParams) (McpServer, error)
	// InsertNoteMessage persists an internal note (never delivered, delivery_state NULL).
	// source_approval_item_id (nullable) is the idempotency key for agent-driven notes:
	// a redelivered ApprovalExecutor replay supplies the same key, which the service
	// detects via GetOutboundMessageByApproval before inserting. Under a concurrent race
	// both pre-checks can miss; the partial UNIQUE index then makes the loser conflict and
	// insert no second row (returns 0 rows ⇒ pgx.ErrNoRows ⇒ the at-least-once executor
	// retries, and the retry's pre-check finds the winner — same semantics as Reply). NULL
	// for ordinary human notes — NULLs never conflict, so existing behavior holds.
	InsertNoteMessage(ctx context.Context, arg InsertNoteMessageParams) (TicketMessage, error)
	// ---- notification (SL-D) ----
	InsertNotification(ctx context.Context, arg InsertNotificationParams) error
	// InsertOutboundMessage persists an agent reply as a pending-delivery outbound row.
	// source_approval_item_id (nullable) is the approval-driven dedup key: a redelivered
	// approval execution conflicts on the partial UNIQUE index and inserts no second row
	// (NULL for ordinary human replies — NULLs never conflict, so existing behavior holds).
	InsertOutboundMessage(ctx context.Context, arg InsertOutboundMessageParams) (TicketMessage, error)
	InsertRepoConnector(ctx context.Context, arg InsertRepoConnectorParams) (RepoConnector, error)
	// InsertSecret seals-then-stores: caller passes a pre-generated id + the sealed ciphertext.
	// tenant_root_id is derived from the (RLS-visible) business, so an invisible business inserts zero rows.
	InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error)
	InsertSuppression(ctx context.Context, arg InsertSuppressionParams) error
	// InsertTicketTag inserts one tag for a ticket (the second half of tag
	// replacement). PK (ticket_id, tag); the service dedups before calling.
	InsertTicketTag(ctx context.Context, arg InsertTicketTagParams) error
	IsAccountVerifiedByPrincipal(ctx context.Context, id uuid.UUID) (bool, error)
	// True if candidate ($2) is the node ($1) itself or a descendant of it.
	IsDescendant(ctx context.Context, arg IsDescendantParams) (bool, error)
	// Email suppression queries (spec 001 email_suppression table, US2 outbound safety).
	// Table: email_suppression (email citext PK, reason text, created_at timestamptz).
	IsSuppressed(ctx context.Context, email string) (bool, error)
	// ListAIProviderCredentials lists all credentials for a business, ordered
	// by provider name for a stable, deterministic result.
	ListAIProviderCredentials(ctx context.Context, businessID uuid.UUID) ([]AiProviderCredential, error)
	// ListActivityForContact is the first timeline page: newest-first, tenant+contact scoped.
	ListActivityForContact(ctx context.Context, arg ListActivityForContactParams) ([]ActivityEntry, error)
	// ListActivityForContactAfter is the keyset continuation. Order is DESC, so the row-value
	// predicate is strictly-LESS-THAN (occurred_at, id) — the DESC mirror of the Phase A ASC '>'
	// cursors — avoiding skip/dupe at an occurred_at tie boundary.
	ListActivityForContactAfter(ctx context.Context, arg ListActivityForContactAfterParams) ([]ActivityEntry, error)
	// Keyset-paginated runs for one agent over [from_ts, to_ts), newest first. The cursor
	// tuple (cur_created_at, cur_id) is passed as a far-future sentinel for page 1. RLS
	// (under WithPrincipal) scopes to the caller's businesses; business_id+agent_id narrow.
	ListAgentRuns(ctx context.Context, arg ListAgentRunsParams) ([]AgentRun, error)
	// ListAgents lists all agents for a business, ordered by name for a stable result.
	ListAgents(ctx context.Context, businessID uuid.UUID) ([]Agent, error)
	// NOTE: the outbound delivery-state path (delivery_state read, system inbound
	// address lookup, mark sent/failed) is driven by the PRINCIPAL-LESS outbox-send /
	// bounce worker. Plain-table sqlc queries against the RLS-protected ticket_message /
	// inbound_address tables silently return/affect ZERO rows when run without a
	// principal (authorized_businesses(NULL) is empty), so they have been REPLACED by
	// the SECURITY DEFINER functions get_send_context + mark_message_delivery in
	// migration 0019 (called via raw pgx from internal/platform/notify). Do NOT re-add
	// GetMessageDeliveryState / GetBusinessSystemInboundAddress / MarkMessageDelivered /
	// MarkMessageFailed here — they were traps (manyforge-0fq).
	//
	// The hard-bounce path (T040) correlates a bounce to its outbound message by the
	// globally-unique Message-ID we minted (rfc_message_id) and marks it failed via the
	// SECURITY DEFINER mark_bounced_message (migration 0020), called raw from
	// internal/inbox. The earlier GetOutboundMessageForBounce plain-table query was
	// superseded by that DEFINER and removed — it was the same principal-less RLS trap as
	// the queries above (under RLS with no principal it returned zero rows).
	// ---- assignable members (assignee picker, FR-011) ----
	// ListAssignableMembers returns a business's human, active members ordered by display
	// name — the candidate ticket assignees for the picker. Single server-capped page.
	// Runs in the caller's RLS context, so membership is already scoped to a business the
	// caller is authorized over (the route is additionally gated on tickets.assign).
	ListAssignableMembers(ctx context.Context, arg ListAssignableMembersParams) ([]ListAssignableMembersRow, error)
	// ListAttachmentsForMessages fetches every attachment for a page of messages in
	// one round trip (avoids N+1). The service groups by ticket_message_id.
	ListAttachmentsForMessages(ctx context.Context, arg ListAttachmentsForMessagesParams) ([]Attachment, error)
	// A business's audit trail, newest first, keyset-paginated on (created_at, id).
	// The first page passes a far-future sentinel cursor so the predicate is uniform.
	// RLS scopes audit_entry to the caller's authorized businesses; the service
	// additionally gates on audit.read. Projection omits new_value/old_value.
	ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]ListAuditEntriesRow, error)
	// RLS scopes the result to businesses the caller can see.
	ListBusinesses(ctx context.Context) ([]Business, error)
	// ListCodeReviews returns the business's reviews newest-first for the history UI.
	ListCodeReviews(ctx context.Context, businessID uuid.UUID) ([]ListCodeReviewsRow, error)
	// ListCompanies is the first (unkeyed) page of a tenant's companies, ordered by name
	// for a stable keyset.
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error)
	// ListCompaniesAfter is the keyset continuation: rows strictly after the cursor tuple
	// (name, id) in the (ASC, ASC) order. The row-value comparison avoids the skip/dupe a
	// single-column name > cursor would cause on the non-unique company.name.
	ListCompaniesAfter(ctx context.Context, arg ListCompaniesAfterParams) ([]Company, error)
	// ListConnectorHealth returns per-connector sync-health aggregates for a business in one
	// round-trip (avoids N+1). Counts run under the caller's RLS context. last_error is the
	// most-recent failed outbound op's stored reason (already redacted at write time).
	ListConnectorHealth(ctx context.Context, businessID uuid.UUID) ([]ListConnectorHealthRow, error)
	// ListConnectors returns all connectors for a business, newest-stable order. RLS + the
	// business_id predicate scope this to the caller's tenant. Credentials are NOT joined —
	// only the connector row (which holds no plaintext secret, just secret_ref).
	ListConnectors(ctx context.Context, businessID uuid.UUID) ([]Connector, error)
	// ListContacts is the first (unkeyed) page of a tenant's live contacts, ordered by
	// primary_email for a stable keyset.
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	// ListContactsAfter is the keyset continuation: rows strictly after the cursor tuple
	// (primary_email, id) in the (ASC, ASC) order. The row-value comparison avoids the
	// skip/dupe a single-column primary_email > cursor would cause at a tie boundary.
	ListContactsAfter(ctx context.Context, arg ListContactsAfterParams) ([]Contact, error)
	// ListEmailDomains is the first (unkeyed) page of a business's email domains, oldest
	// first for a stable keyset. lim is the clamped limit + 1 so the service detects a
	// further page.
	ListEmailDomains(ctx context.Context, arg ListEmailDomainsParams) ([]EmailDomain, error)
	// ListEmailDomainsAfter is the keyset continuation: rows strictly after (created_at, id).
	ListEmailDomainsAfter(ctx context.Context, arg ListEmailDomainsAfterParams) ([]EmailDomain, error)
	// ListEnabledMCPServersByIDs returns the enabled MCP servers for a business
	// filtered to a specific set of IDs. Used at run-start to discover servers
	// the agent is allowed to use.
	ListEnabledMCPServersByIDs(ctx context.Context, arg ListEnabledMCPServersByIDsParams) ([]McpServer, error)
	// ListInboundAddresses is the first (unkeyed) page of a business's inbound addresses
	// (both system and custom), oldest first for a stable keyset. lim is the clamped
	// limit + 1.
	ListInboundAddresses(ctx context.Context, arg ListInboundAddressesParams) ([]InboundAddress, error)
	// ListInboundAddressesAfter is the keyset continuation: rows strictly after (created_at, id).
	ListInboundAddressesAfter(ctx context.Context, arg ListInboundAddressesAfterParams) ([]InboundAddress, error)
	ListInvitations(ctx context.Context, businessID uuid.UUID) ([]ListInvitationsRow, error)
	// ListMCPServers lists all MCP servers for a business, ordered by name for a
	// stable, deterministic result.
	ListMCPServers(ctx context.Context, businessID uuid.UUID) ([]McpServer, error)
	ListMCPToolPolicies(ctx context.Context, arg ListMCPToolPoliciesParams) ([]McpToolPolicy, error)
	// ---- ticket messages ----
	// ListMessages is the first page of a ticket's thread, oldest first, matching the
	// SC-010 ticket_message(ticket_id, created_at) index. Scoped to (ticket_id,
	// business_id) so a ticket id from another business yields zero rows (no leak).
	// lim is the clamped limit + 1.
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]TicketMessage, error)
	// ListMessagesAfter is the keyset continuation: rows strictly after (created_at, id).
	ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]TicketMessage, error)
	ListModelPricing(ctx context.Context) ([]ListModelPricingRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// Tenant roots where this principal directly holds the locked Owner role. RLS
	// always exposes the caller's own membership rows, so this is reliable under
	// WithPrincipal even before any cross-member visibility is established.
	ListOwnerRootMembershipsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]uuid.UUID, error)
	ListPendingApprovals(ctx context.Context, arg ListPendingApprovalsParams) ([]ApprovalItem, error)
	// Keyset pagination over the global catalog; pass '' as the cursor for the first
	// page and the last returned key thereafter. Fetch limit+1 to detect a next page.
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error)
	// ListRepoConnectors returns the caller's connectors (RLS-scoped). NEVER selects
	// secret_ref — the UI must not receive any credential handle.
	ListRepoConnectors(ctx context.Context, businessID uuid.UUID) ([]ListRepoConnectorsRow, error)
	// ---- requesters ----
	// ListRequesters is the first page of a business's requesters, ordered by
	// first_seen_at for a stable keyset. The optional email facet is an exact
	// (case-insensitive citext) match for lookup/dedup. lim is the clamped limit + 1.
	ListRequesters(ctx context.Context, arg ListRequestersParams) ([]Requester, error)
	// ListRequestersAfter is the keyset continuation: rows strictly after (first_seen_at, id).
	ListRequestersAfter(ctx context.Context, arg ListRequestersAfterParams) ([]Requester, error)
	// ListRequestersForContact returns every requester currently pointing at a contact —
	// the merge/repoint enumeration. Requester is business-scoped; RLS scopes the visible set.
	ListRequestersForContact(ctx context.Context, contactID pgtype.UUID) ([]Requester, error)
	// Presets (tenant_root_id IS NULL) plus the tenant's custom roles. RLS scopes
	// this to roles the caller may see; the predicate narrows to one tenant.
	ListTenantRoles(ctx context.Context, tenantRootID pgtype.UUID) ([]ListTenantRolesRow, error)
	// ListTicketAttachmentBlobs returns the blob key of every attachment on a ticket
	// (joined through its messages) so redact can enqueue one attachment.purge per blob.
	// The shared requester row is deliberately untouched (deduped across tickets).
	ListTicketAttachmentBlobs(ctx context.Context, arg ListTicketAttachmentBlobsParams) ([]string, error)
	// ListTicketTags returns the tags for one ticket (already business-scoped by the
	// caller having loaded the ticket under the same predicate), ordered for stable output.
	ListTicketTags(ctx context.Context, arg ListTicketTagsParams) ([]string, error)
	// Ticketing read-slice queries (spec 002, T031). Plain-table keyset reads only —
	// every query runs inside the caller's RLS principal context (db.WithPrincipal)
	// AND pushes the (business_id, …) ownership predicate into SQL (dual enforcement).
	// Keyset pagination uses limit+1 to detect a next page; the service trims the
	// extra row and mints an opaque cursor from the last kept row's keyset tuple.
	// The SECURITY DEFINER ingest/threading functions stay raw-pgx in internal/inbox;
	// nothing here writes — this is the authenticated read surface for US1.
	// ---- tickets ----
	// ListTickets is the first (unkeyed) page of a business's tickets, newest activity
	// first. Ordering + index match SC-010's ticket(business_id, status, last_message_at DESC).
	// All filters are optional: a NULL/empty arg disables that facet. The `assignee`
	// facet is tri-state — assignee_unassigned = TRUE lists only NULL assignees;
	// otherwise a non-NULL assignee_principal_id filters to that principal; both off =
	// no assignee filter. The tag facet is an exact (case-insensitive citext) match via
	// ticket_tag. lim is the clamped limit + 1 so the service can detect a further page.
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error)
	// ListTicketsAfter is the keyset continuation of ListTickets: the same filters,
	// but only rows strictly after the cursor tuple (last_message_at, id) in the
	// (DESC, DESC) order. The row-value comparison rides the same composite index.
	ListTicketsAfter(ctx context.Context, arg ListTicketsAfterParams) ([]ListTicketsAfterRow, error)
	// Run-path: the discovery loop reads this under the AGENT principal (RLS scopes it to the
	// agent's business) to classify discovered tools.
	ListToolPoliciesByServer(ctx context.Context, mcpServerID uuid.UUID) ([]ListToolPoliciesByServerRow, error)
	// Idempotency claim: flip approved -> executed iff still approved. Zero rows means a
	// prior delivery already executed it (or it was denied) -> the executor skips.
	MarkApprovalExecuted(ctx context.Context, arg MarkApprovalExecutedParams) (ApprovalItem, error)
	// Terminal-failure claim: flip approved -> failed iff still approved, recording the reason in
	// the error column. Zero rows means a prior delivery already executed/failed it -> the executor
	// skips (same idempotency contract as MarkApprovalExecuted).
	MarkApprovalFailed(ctx context.Context, arg MarkApprovalFailedParams) (ApprovalItem, error)
	// MarkEmailDomainVerified sets verified_at = now() ONLY when it is currently NULL —
	// idempotent (a re-verify of an already-verified domain is a no-op, leaving the
	// original timestamp untouched). Scoped to (id, business_id, tenant_root_id) for
	// dual enforcement; runs in the caller's tx. RETURNING the row lets the service
	// report the (possibly unchanged) state, but the audit/transition decision is made
	// by the service from the pre-update verified_at, not from rows-affected.
	MarkEmailDomainVerified(ctx context.Context, arg MarkEmailDomainVerifiedParams) error
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error
	OwnerRoleID(ctx context.Context) (uuid.UUID, error)
	// The id of a built-in preset role by key (owner/admin/member/viewer).
	PresetRoleID(ctx context.Context, key string) (uuid.UUID, error)
	// Relink the newest detached ticket per external_id (for this business + provider host) to the
	// new connector; duplicates (older rows sharing an external_id) stay detached so the
	// (connector_id, external_id) unique index is never violated. Returns the relinked ticket ids.
	ReadoptDetachedTickets(ctx context.Context, arg ReadoptDetachedTicketsParams) ([]uuid.UUID, error)
	// RecordWebhookDelivery dedupes inbound webhook deliveries per connector: ON CONFLICT
	// DO NOTHING means a replayed external_delivery_id inserts zero rows, which the caller
	// reads as "already seen". tenant_root derived from the RLS-visible business; the EXISTS
	// guard requires connector_id to belong to the SAME business (defense-in-depth).
	RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) (int64, error)
	// ---- US5 redact / soft-delete (T066) ----
	// RedactTicket soft-deletes a ticket in place: blanks its subject and stamps
	// redacted_at, scoped to (id, business_id) under the caller's RLS context. Idempotent —
	// a row already redacted (redacted_at IS NOT NULL) matches zero rows, so the service
	// maps pgx.ErrNoRows ⇒ ErrNotFound (already-gone / unknown / foreign: one no-oracle
	// shape). NEVER a hard DELETE (Principle VI / FR-014). Returns tenant_root_id +
	// redacted_at for the in-tx audit and the per-blob purge enqueue.
	RedactTicket(ctx context.Context, arg RedactTicketParams) (RedactTicketRow, error)
	// Restore connector_id on the re-adopted tickets' messages. Gated on external_id IS NOT NULL to
	// satisfy ticket_message_connector_external_chk (connector_id set ⇒ external_id present); messages
	// without an external id correctly stay native.
	RelinkReadoptedMessages(ctx context.Context, arg RelinkReadoptedMessagesParams) error
	// Subtree move is performed by the SECURITY DEFINER move_business() function
	// (migration 0009), invoked via tx.Exec from the service so the closure rewrite
	// is RLS-exempt (the moved subtree is transiently unauthorized mid-rewrite).
	RenameBusiness(ctx context.Context, arg RenameBusinessParams) error
	// RepointActivityEntries re-points a loser contact's activity to the winner on merge (same
	// tenant); completes the Phase A merge (which already re-points requesters + soft-deletes loser).
	RepointActivityEntries(ctx context.Context, arg RepointActivityEntriesParams) error
	// RepointRequesters moves every requester from the losing contact to the winning one
	// during a contact merge (runs in the same tx as the loser's soft-delete). Scoped by
	// contact_id, whose tenant ownership the service validates before calling.
	RepointRequesters(ctx context.Context, arg RepointRequestersParams) error
	// RetryFailedOps re-enqueues a connector's terminally-failed outbound ops for another dispatch
	// attempt: failed → pending, attempts reset to 0 (the maxOutboundAttempts cap starts fresh) and
	// last_error cleared. The dispatcher only claims status='pending', so this is the sole exit from
	// the terminal 'failed' state (manyforge-xfj). Scoped to (connector_id, business_id) — RLS plus
	// an explicit business_id predicate — so a foreign/unknown connector matches zero rows. Returns
	// the number of ops re-enqueued (0 is valid: nothing was failed).
	RetryFailedOps(ctx context.Context, arg RetryFailedOpsParams) (int64, error)
	// Cuts off every live session for a principal (account delete, T077).
	RevokeAllRefreshForPrincipal(ctx context.Context, principalID uuid.UUID) error
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (uuid.UUID, error)
	RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error
	// Invitation lifecycle queries. Create/list/revoke/resend run under the inviter's
	// principal (a member with members.manage), so RLS scopes them to the business.
	// Acceptance is handled by the accept_invitation() SECURITY DEFINER function
	// (invitees are not yet members), invoked via raw SQL in the service.
	// A role assignable within the tenant: a preset (NULL tenant) or the tenant's own.
	RoleVisibleInTenant(ctx context.Context, arg RoleVisibleInTenantParams) (uuid.UUID, error)
	// RotateConnectorSecretRef atomically swaps the sealed-credential pointer to new_secret_ref,
	// locking the connector row (FOR UPDATE) and RETURNING the OLD secret_ref it replaced — so the
	// caller deletes exactly the secret it displaced, with no TOCTOU against a concurrent rotation.
	// Scoped to (id, business_id); unknown/foreign id → no row → pgx.ErrNoRows → 404.
	RotateConnectorSecretRef(ctx context.Context, arg RotateConnectorSecretRefParams) (uuid.UUID, error)
	RotateInvitationToken(ctx context.Context, arg RotateInvitationTokenParams) (uuid.UUID, error)
	// Records the irreversible-purge schedule; idempotent so a repeated delete is safe.
	ScheduleErasure(ctx context.Context, arg ScheduleErasureParams) error
	SetSubtreeStatus(ctx context.Context, arg SetSubtreeStatusParams) error
	// Cuts off access immediately; PII anonymization is deferred to the purge worker.
	SoftDeleteAccount(ctx context.Context, id uuid.UUID) error
	SoftDeleteBusiness(ctx context.Context, id uuid.UUID) error
	// SoftDeleteContact stamps deleted_at (never a hard DELETE — Principle VI), scoped to
	// (id, tenant_root_id). Idempotent: an already-deleted / foreign-tenant row matches zero
	// rows, so the service maps pgx.ErrNoRows ⇒ ErrNotFound.
	SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error
	SubtreeHeight(ctx context.Context, ancestorID uuid.UUID) (int32, error)
	// UpdateAgent partially updates an agent (PATCH): COALESCE(narg, col) preserves any
	// field the caller omitted (narg NULL = absent). provider is immutable (not settable
	// here). No match → ErrNoRows → 404.
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	// Final/intermediate state write. status + token/cost totals + optional error.
	UpdateAgentRunProgress(ctx context.Context, arg UpdateAgentRunProgressParams) (AgentRun, error)
	UpdateCodeReviewResult(ctx context.Context, arg UpdateCodeReviewResultParams) (CodeReview, error)
	// UpdateCompany is a partial update: NULL nargs preserve the current value via COALESCE.
	// NOTE: COALESCE cannot clear domain to NULL (a NULL narg is read as "unchanged", not
	// "detach") — acceptable for Phase A. Scoped to (id, tenant_root_id).
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	// UpdateConnector applies a partial (PATCH) change scoped to (id, business_id). Omitted
	// fields (NULL narg) are preserved via COALESCE. base_url and type are intentionally NOT
	// updatable (they are part of the connector's identity). No matching row → no row returned
	// → pgx.ErrNoRows → 404 (no oracle). status is written as text exactly like InsertConnector.
	//
	// NOTE (manyforge-a7j.7): if base_url or allow_private_base_url ever become mutable here (or
	// via a new UpdateConnectorCredential query), the service MUST re-run validateBaseURL on the
	// new value AND re-audit the trust grant — create-time validation (credential.go) alone is
	// insufficient once these are mutable, or an update silently bypasses the SSRF/trust checks.
	// Pinned in internal/security_regression/connector_credential_update_pin_test.go.
	UpdateConnector(ctx context.Context, arg UpdateConnectorParams) (Connector, error)
	// UpdateContact is a partial update: a NULL narg preserves the current column value via
	// COALESCE. NOTE: COALESCE cannot clear company_id to NULL (a NULL narg is read as
	// "unchanged", not "detach") — acceptable for Phase A; detach is a future query if needed.
	// Touches updated_at; scoped to a live row (id, tenant_root_id, deleted_at IS NULL) so a
	// soft-deleted / foreign-tenant id matches zero rows ⇒ ErrNotFound.
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (Account, error)
	// Email is citext UNIQUE; a collision raises 23505, surfaced as a validation error.
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) error
	// UpdateMCPServer partially updates an MCP server (PATCH): COALESCE(narg, col)
	// preserves any field the caller omitted (narg NULL = absent).
	// No match → ErrNoRows → 404.
	UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error)
	// Reassigns a member's role at a business, recording who made the change. :exec
	// (no RETURNING): RLS can hide the just-updated row from the caller (42501).
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error
	// ---- Auth flows (T078) ----
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) error
	// UpdateTicketAssignee sets (or NULLs, for unassign) the assignee. The nullable
	// arg carries NULL for unassign and a principal id for assign — the service has
	// already verified eligibility via the is_eligible_assignee DEFINER (T048). Touches
	// updated_at but NEVER last_message_at (triage is not a message). Scoped to
	// (id, business_id, tenant_root_id) for dual enforcement; runs in the caller's tx.
	UpdateTicketAssignee(ctx context.Context, arg UpdateTicketAssigneeParams) error
	// UpdateTicketPriority sets a new priority (manual triage). Touches updated_at but
	// NEVER last_message_at. Scoped to (id, business_id, tenant_root_id).
	UpdateTicketPriority(ctx context.Context, arg UpdateTicketPriorityParams) error
	// ---- US3 triage queries (T047) ----
	// UpdateTicketStatus sets a new status (manual triage / yqi new→open). Touches
	// updated_at but NEVER last_message_at — triage is not a message. Scoped to
	// (id, business_id, tenant_root_id) for dual enforcement; runs in the caller's tx.
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error
	// MCP per-tool effect policy (manyforge-k0d). Every query runs in the caller's RLS principal
	// context AND pushes the (business_id, …) ownership predicate into SQL (dual enforcement).
	// Derives (business_id, tenant_root_id) from the RLS-visible mcp_server row, so an invisible or
	// foreign server yields no row → pgx.ErrNoRows → 404 (no oracle). Upsert on (mcp_server_id, tool_name).
	UpsertMCPToolPolicy(ctx context.Context, arg UpsertMCPToolPolicyParams) (McpToolPolicy, error)
	// ValidateMCPServerIDs returns the subset of the given UUIDs that exist and
	// are owned by the given business. Used by the agent service to validate
	// allowed_mcp_servers before persisting an agent.
	ValidateMCPServerIDs(ctx context.Context, arg ValidateMCPServerIDsParams) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
