// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenancy.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTenantLock = `-- name: AcquireTenantLock :exec
SELECT pg_advisory_xact_lock(hashtext($1))
`

// Serializes structural mutations within a tenant (research R5).
func (q *Queries) AcquireTenantLock(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, acquireTenantLock, hashtext)
	return err
}

const countActiveChildren = `-- name: CountActiveChildren :one
SELECT count(*) FROM business WHERE parent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountActiveChildren(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBusiness = `-- name: CreateBusiness :exec
INSERT INTO business (id, parent_id, tenant_root_id, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'active', now(), now())
`

type CreateBusinessParams struct {
	ID           uuid.UUID   `json:"id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	TenantRootID uuid.UUID   `json:"tenant_root_id"`
	Name         string      `json:"name"`
}

// CreateBusiness uses :exec (no RETURNING): under RLS, INSERT ... RETURNING
// applies the SELECT/USING policy to the returned row, which the creator cannot
// yet see (no membership at insert time). The caller builds the result from inputs.
func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) error {
	_, err := q.db.Exec(ctx, createBusiness,
		arg.ID,
		arg.ParentID,
		arg.TenantRootID,
		arg.Name,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO membership (id, principal_id, business_id, tenant_root_id, role_id, granted_by, granted_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
`

type CreateMembershipParams struct {
	ID           uuid.UUID   `json:"id"`
	PrincipalID  uuid.UUID   `json:"principal_id"`
	BusinessID   uuid.UUID   `json:"business_id"`
	TenantRootID uuid.UUID   `json:"tenant_root_id"`
	RoleID       uuid.UUID   `json:"role_id"`
	GrantedBy    pgtype.UUID `json:"granted_by"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership,
		arg.ID,
		arg.PrincipalID,
		arg.BusinessID,
		arg.TenantRootID,
		arg.RoleID,
		arg.GrantedBy,
	)
	return err
}

const depthFromRoot = `-- name: DepthFromRoot :one
SELECT depth FROM business_closure WHERE ancestor_id = $2 AND descendant_id = $1
`

type DepthFromRootParams struct {
	DescendantID uuid.UUID `json:"descendant_id"`
	AncestorID   uuid.UUID `json:"ancestor_id"`
}

func (q *Queries) DepthFromRoot(ctx context.Context, arg DepthFromRootParams) (int32, error) {
	row := q.db.QueryRow(ctx, depthFromRoot, arg.DescendantID, arg.AncestorID)
	var depth int32
	err := row.Scan(&depth)
	return depth, err
}

const getBusiness = `-- name: GetBusiness :one
SELECT id, parent_id, tenant_root_id, name, status, deleted_at, created_at, updated_at FROM business WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBusiness(ctx context.Context, id uuid.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, getBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.TenantRootID,
		&i.Name,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChildClosure = `-- name: InsertChildClosure :exec
INSERT INTO business_closure (ancestor_id, descendant_id, depth, tenant_root_id)
SELECT c.ancestor_id, $1, c.depth + 1, $3
FROM business_closure c
WHERE c.descendant_id = $2
`

type InsertChildClosureParams struct {
	DescendantID   uuid.UUID `json:"descendant_id"`
	DescendantID_2 uuid.UUID `json:"descendant_id_2"`
	TenantRootID   uuid.UUID `json:"tenant_root_id"`
}

// Link a new child ($1) under parent ($2): inherit the parent's ancestor chain
// (+1 depth). The child's self row is inserted separately via InsertClosureSelf.
func (q *Queries) InsertChildClosure(ctx context.Context, arg InsertChildClosureParams) error {
	_, err := q.db.Exec(ctx, insertChildClosure, arg.DescendantID, arg.DescendantID_2, arg.TenantRootID)
	return err
}

const insertClosureSelf = `-- name: InsertClosureSelf :exec
INSERT INTO business_closure (ancestor_id, descendant_id, depth, tenant_root_id)
VALUES ($1, $1, 0, $2)
`

type InsertClosureSelfParams struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	TenantRootID uuid.UUID `json:"tenant_root_id"`
}

func (q *Queries) InsertClosureSelf(ctx context.Context, arg InsertClosureSelfParams) error {
	_, err := q.db.Exec(ctx, insertClosureSelf, arg.AncestorID, arg.TenantRootID)
	return err
}

const isDescendant = `-- name: IsDescendant :one
SELECT EXISTS (
    SELECT 1 FROM business_closure WHERE ancestor_id = $1 AND descendant_id = $2
) AS is_descendant
`

type IsDescendantParams struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
}

// True if candidate ($2) is the node ($1) itself or a descendant of it.
func (q *Queries) IsDescendant(ctx context.Context, arg IsDescendantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDescendant, arg.AncestorID, arg.DescendantID)
	var is_descendant bool
	err := row.Scan(&is_descendant)
	return is_descendant, err
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, parent_id, tenant_root_id, name, status, deleted_at, created_at, updated_at FROM business WHERE deleted_at IS NULL ORDER BY created_at
`

// RLS scopes the result to businesses the caller can see.
func (q *Queries) ListBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.TenantRootID,
			&i.Name,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerRoleID = `-- name: OwnerRoleID :one
SELECT id FROM role WHERE tenant_root_id IS NULL AND key = 'owner'
`

func (q *Queries) OwnerRoleID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, ownerRoleID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const renameBusiness = `-- name: RenameBusiness :exec

UPDATE business SET name = $2, updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

type RenameBusinessParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// Subtree move is performed by the SECURITY DEFINER move_business() function
// (migration 0009), invoked via tx.Exec from the service so the closure rewrite
// is RLS-exempt (the moved subtree is transiently unauthorized mid-rewrite).
func (q *Queries) RenameBusiness(ctx context.Context, arg RenameBusinessParams) error {
	_, err := q.db.Exec(ctx, renameBusiness, arg.ID, arg.Name)
	return err
}

const setSubtreeStatus = `-- name: SetSubtreeStatus :exec
UPDATE business SET status = $2, updated_at = now()
WHERE id IN (SELECT descendant_id FROM business_closure WHERE ancestor_id = $1)
  AND deleted_at IS NULL
`

type SetSubtreeStatusParams struct {
	AncestorID uuid.UUID `json:"ancestor_id"`
	Status     string    `json:"status"`
}

func (q *Queries) SetSubtreeStatus(ctx context.Context, arg SetSubtreeStatusParams) error {
	_, err := q.db.Exec(ctx, setSubtreeStatus, arg.AncestorID, arg.Status)
	return err
}

const softDeleteBusiness = `-- name: SoftDeleteBusiness :exec
UPDATE business SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteBusiness(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteBusiness, id)
	return err
}

const subtreeHeight = `-- name: SubtreeHeight :one
SELECT COALESCE(max(depth), 0)::int AS height FROM business_closure WHERE ancestor_id = $1
`

func (q *Queries) SubtreeHeight(ctx context.Context, ancestorID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, subtreeHeight, ancestorID)
	var height int32
	err := row.Scan(&height)
	return height, err
}
