"""
    ManyForge API

    Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union
from collections.abc import Iterator, AsyncIterator, Mapping
from pydantic import TypeAdapter, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr
from manyforge.model_support import JsonValue, UNSET, UnsetType
from manyforge.transport import (SyncTransport, AsyncTransport, Request, RequestOptions, QueryParameter, Upload, ByteStream, AsyncByteStream, PaginationError)
from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from uuid import UUID
from manyforge.models.contact import Contact
from manyforge.models.contact_list import ContactList
from manyforge.models.create_contact import CreateContact
from manyforge.models.merge_request import MergeRequest
from manyforge.models.merge_result import MergeResult
from manyforge.models.update_contact import UpdateContact

from manyforge.models import Contact

class BusinessContactsResource:
    def __init__(self, transport: SyncTransport, bindings: Mapping[str, str] | None = None) -> None:
        self._transport = transport
        self._bindings = dict(bindings or {})

    def create(
        self,
        *,

        create_contact: CreateContact,

        request_options: RequestOptions | None = None,
    ) -> Contact:
        request = Request(
            operation_id="createContact",
            method="POST",
            path="/api/v1/businesses/{id}/contacts",
            authenticated=True,
            response=TypeAdapter(Contact),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
            ),
            headers={
            },
            body=create_contact,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def delete(
        self,
        *,

        cid: UUID,

        request_options: RequestOptions | None = None,
    ) -> None:
        request = Request(
            operation_id="deleteContact",
            method="DELETE",
            path="/api/v1/businesses/{id}/contacts/{cid}",
            authenticated=True,
            response=TypeAdapter(type(None)),
            path_parameters={
                "id": self._bindings["id"],
                "cid": cid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def get(
        self,
        *,

        cid: UUID,

        request_options: RequestOptions | None = None,
    ) -> Contact:
        request = Request(
            operation_id="getContact",
            method="GET",
            path="/api/v1/businesses/{id}/contacts/{cid}",
            authenticated=True,
            response=TypeAdapter(Contact),
            path_parameters={
                "id": self._bindings["id"],
                "cid": cid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def list(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> ContactList:
        request = Request(
            operation_id="listContacts",
            method="GET",
            path="/api/v1/businesses/{id}/contacts",
            authenticated=True,
            response=TypeAdapter(ContactList),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
                QueryParameter("cursor", cursor, "form", True),
                QueryParameter("limit", limit, "form", True),
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def iter(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> Iterator[Contact]:
        seen: set[str] = set()
        next_cursor = cursor
        if isinstance(next_cursor, str) and next_cursor:
            seen.add(next_cursor)
        while True:
            page = self.list(

                cursor=next_cursor,

                limit=limit,

                request_options=request_options,
            )
            for item in page.items:
                yield item
            next_cursor = page.next_cursor
            if isinstance(next_cursor, UnsetType) or not next_cursor:
                return
            if next_cursor in seen:
                raise PaginationError("Server returned a repeated cursor")
            seen.add(next_cursor)

    def merge(
        self,
        *,

        cid: UUID,

        merge_request: MergeRequest,

        request_options: RequestOptions | None = None,
    ) -> MergeResult:
        request = Request(
            operation_id="mergeContact",
            method="POST",
            path="/api/v1/businesses/{id}/contacts/{cid}/merge",
            authenticated=True,
            response=TypeAdapter(MergeResult),
            path_parameters={
                "id": self._bindings["id"],
                "cid": cid,
            },
            query=(
            ),
            headers={
            },
            body=merge_request,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def update(
        self,
        *,

        cid: UUID,

        update_contact: UpdateContact,

        request_options: RequestOptions | None = None,
    ) -> Contact:
        request = Request(
            operation_id="updateContact",
            method="PATCH",
            path="/api/v1/businesses/{id}/contacts/{cid}",
            authenticated=True,
            response=TypeAdapter(Contact),
            path_parameters={
                "id": self._bindings["id"],
                "cid": cid,
            },
            query=(
            ),
            headers={
            },
            body=update_contact,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

class AsyncBusinessContactsResource:
    def __init__(self, transport: AsyncTransport, bindings: Mapping[str, str] | None = None) -> None:
        self._transport = transport
        self._bindings = dict(bindings or {})

    async def create(
        self,
        *,

        create_contact: CreateContact,

        request_options: RequestOptions | None = None,
    ) -> Contact:
        request = Request(
            operation_id="createContact",
            method="POST",
            path="/api/v1/businesses/{id}/contacts",
            authenticated=True,
            response=TypeAdapter(Contact),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
            ),
            headers={
            },
            body=create_contact,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def delete(
        self,
        *,

        cid: UUID,

        request_options: RequestOptions | None = None,
    ) -> None:
        request = Request(
            operation_id="deleteContact",
            method="DELETE",
            path="/api/v1/businesses/{id}/contacts/{cid}",
            authenticated=True,
            response=TypeAdapter(type(None)),
            path_parameters={
                "id": self._bindings["id"],
                "cid": cid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def get(
        self,
        *,

        cid: UUID,

        request_options: RequestOptions | None = None,
    ) -> Contact:
        request = Request(
            operation_id="getContact",
            method="GET",
            path="/api/v1/businesses/{id}/contacts/{cid}",
            authenticated=True,
            response=TypeAdapter(Contact),
            path_parameters={
                "id": self._bindings["id"],
                "cid": cid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def list(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> ContactList:
        request = Request(
            operation_id="listContacts",
            method="GET",
            path="/api/v1/businesses/{id}/contacts",
            authenticated=True,
            response=TypeAdapter(ContactList),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
                QueryParameter("cursor", cursor, "form", True),
                QueryParameter("limit", limit, "form", True),
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def iter(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> AsyncIterator[Contact]:
        seen: set[str] = set()
        next_cursor = cursor
        if isinstance(next_cursor, str) and next_cursor:
            seen.add(next_cursor)
        while True:
            page = await self.list(

                cursor=next_cursor,

                limit=limit,

                request_options=request_options,
            )
            for item in page.items:
                yield item
            next_cursor = page.next_cursor
            if isinstance(next_cursor, UnsetType) or not next_cursor:
                return
            if next_cursor in seen:
                raise PaginationError("Server returned a repeated cursor")
            seen.add(next_cursor)

    async def merge(
        self,
        *,

        cid: UUID,

        merge_request: MergeRequest,

        request_options: RequestOptions | None = None,
    ) -> MergeResult:
        request = Request(
            operation_id="mergeContact",
            method="POST",
            path="/api/v1/businesses/{id}/contacts/{cid}/merge",
            authenticated=True,
            response=TypeAdapter(MergeResult),
            path_parameters={
                "id": self._bindings["id"],
                "cid": cid,
            },
            query=(
            ),
            headers={
            },
            body=merge_request,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def update(
        self,
        *,

        cid: UUID,

        update_contact: UpdateContact,

        request_options: RequestOptions | None = None,
    ) -> Contact:
        request = Request(
            operation_id="updateContact",
            method="PATCH",
            path="/api/v1/businesses/{id}/contacts/{cid}",
            authenticated=True,
            response=TypeAdapter(Contact),
            path_parameters={
                "id": self._bindings["id"],
                "cid": cid,
            },
            query=(
            ),
            headers={
            },
            body=update_contact,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

