"""
    ManyForge API

    Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union
from collections.abc import Iterator, AsyncIterator, Mapping
from pydantic import TypeAdapter, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr
from manyforge.model_support import JsonValue, UNSET, UnsetType
from manyforge.transport import (SyncTransport, AsyncTransport, Request, RequestOptions, QueryParameter, Upload, ByteStream, AsyncByteStream, PaginationError)
from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from uuid import UUID
from manyforge.models.preview_input import PreviewInput
from manyforge.models.preview_output import PreviewOutput
from manyforge.models.template import Template
from manyforge.models.template_input import TemplateInput
from manyforge.models.template_page import TemplatePage
from manyforge.models.template_patch import TemplatePatch

from manyforge.models import Template

class BusinessMailingTemplatesResource:
    def __init__(self, transport: SyncTransport, bindings: Mapping[str, str] | None = None) -> None:
        self._transport = transport
        self._bindings = dict(bindings or {})

    def create(
        self,
        *,

        template_input: TemplateInput,

        request_options: RequestOptions | None = None,
    ) -> Template:
        request = Request(
            operation_id="createMailingTemplate",
            method="POST",
            path="/api/v1/businesses/{id}/mailing/templates",
            authenticated=True,
            response=TypeAdapter(Template),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
            ),
            headers={
            },
            body=template_input,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def delete(
        self,
        *,

        tid: UUID,

        request_options: RequestOptions | None = None,
    ) -> None:
        request = Request(
            operation_id="deleteMailingTemplate",
            method="DELETE",
            path="/api/v1/businesses/{id}/mailing/templates/{tid}",
            authenticated=True,
            response=TypeAdapter(type(None)),
            path_parameters={
                "id": self._bindings["id"],
                "tid": tid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def get(
        self,
        *,

        tid: UUID,

        request_options: RequestOptions | None = None,
    ) -> Template:
        request = Request(
            operation_id="getMailingTemplate",
            method="GET",
            path="/api/v1/businesses/{id}/mailing/templates/{tid}",
            authenticated=True,
            response=TypeAdapter(Template),
            path_parameters={
                "id": self._bindings["id"],
                "tid": tid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def list(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> TemplatePage:
        request = Request(
            operation_id="listMailingTemplates",
            method="GET",
            path="/api/v1/businesses/{id}/mailing/templates",
            authenticated=True,
            response=TypeAdapter(TemplatePage),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
                QueryParameter("cursor", cursor, "form", True),
                QueryParameter("limit", limit, "form", True),
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def iter(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> Iterator[Template]:
        seen: set[str] = set()
        next_cursor = cursor
        if isinstance(next_cursor, str) and next_cursor:
            seen.add(next_cursor)
        while True:
            page = self.list(

                cursor=next_cursor,

                limit=limit,

                request_options=request_options,
            )
            for item in page.items:
                yield item
            next_cursor = page.next_cursor
            if isinstance(next_cursor, UnsetType) or not next_cursor:
                return
            if next_cursor in seen:
                raise PaginationError("Server returned a repeated cursor")
            seen.add(next_cursor)

    def preview(
        self,
        *,

        preview_input: PreviewInput,

        request_options: RequestOptions | None = None,
    ) -> PreviewOutput:
        request = Request(
            operation_id="previewMailingTemplate",
            method="POST",
            path="/api/v1/businesses/{id}/mailing/templates/preview",
            authenticated=True,
            response=TypeAdapter(PreviewOutput),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
            ),
            headers={
            },
            body=preview_input,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def update(
        self,
        *,

        tid: UUID,

        template_patch: TemplatePatch,

        request_options: RequestOptions | None = None,
    ) -> Template:
        request = Request(
            operation_id="updateMailingTemplate",
            method="PATCH",
            path="/api/v1/businesses/{id}/mailing/templates/{tid}",
            authenticated=True,
            response=TypeAdapter(Template),
            path_parameters={
                "id": self._bindings["id"],
                "tid": tid,
            },
            query=(
            ),
            headers={
            },
            body=template_patch,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

class AsyncBusinessMailingTemplatesResource:
    def __init__(self, transport: AsyncTransport, bindings: Mapping[str, str] | None = None) -> None:
        self._transport = transport
        self._bindings = dict(bindings or {})

    async def create(
        self,
        *,

        template_input: TemplateInput,

        request_options: RequestOptions | None = None,
    ) -> Template:
        request = Request(
            operation_id="createMailingTemplate",
            method="POST",
            path="/api/v1/businesses/{id}/mailing/templates",
            authenticated=True,
            response=TypeAdapter(Template),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
            ),
            headers={
            },
            body=template_input,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def delete(
        self,
        *,

        tid: UUID,

        request_options: RequestOptions | None = None,
    ) -> None:
        request = Request(
            operation_id="deleteMailingTemplate",
            method="DELETE",
            path="/api/v1/businesses/{id}/mailing/templates/{tid}",
            authenticated=True,
            response=TypeAdapter(type(None)),
            path_parameters={
                "id": self._bindings["id"],
                "tid": tid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def get(
        self,
        *,

        tid: UUID,

        request_options: RequestOptions | None = None,
    ) -> Template:
        request = Request(
            operation_id="getMailingTemplate",
            method="GET",
            path="/api/v1/businesses/{id}/mailing/templates/{tid}",
            authenticated=True,
            response=TypeAdapter(Template),
            path_parameters={
                "id": self._bindings["id"],
                "tid": tid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def list(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> TemplatePage:
        request = Request(
            operation_id="listMailingTemplates",
            method="GET",
            path="/api/v1/businesses/{id}/mailing/templates",
            authenticated=True,
            response=TypeAdapter(TemplatePage),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
                QueryParameter("cursor", cursor, "form", True),
                QueryParameter("limit", limit, "form", True),
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def iter(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> AsyncIterator[Template]:
        seen: set[str] = set()
        next_cursor = cursor
        if isinstance(next_cursor, str) and next_cursor:
            seen.add(next_cursor)
        while True:
            page = await self.list(

                cursor=next_cursor,

                limit=limit,

                request_options=request_options,
            )
            for item in page.items:
                yield item
            next_cursor = page.next_cursor
            if isinstance(next_cursor, UnsetType) or not next_cursor:
                return
            if next_cursor in seen:
                raise PaginationError("Server returned a repeated cursor")
            seen.add(next_cursor)

    async def preview(
        self,
        *,

        preview_input: PreviewInput,

        request_options: RequestOptions | None = None,
    ) -> PreviewOutput:
        request = Request(
            operation_id="previewMailingTemplate",
            method="POST",
            path="/api/v1/businesses/{id}/mailing/templates/preview",
            authenticated=True,
            response=TypeAdapter(PreviewOutput),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
            ),
            headers={
            },
            body=preview_input,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def update(
        self,
        *,

        tid: UUID,

        template_patch: TemplatePatch,

        request_options: RequestOptions | None = None,
    ) -> Template:
        request = Request(
            operation_id="updateMailingTemplate",
            method="PATCH",
            path="/api/v1/businesses/{id}/mailing/templates/{tid}",
            authenticated=True,
            response=TypeAdapter(Template),
            path_parameters={
                "id": self._bindings["id"],
                "tid": tid,
            },
            query=(
            ),
            headers={
            },
            body=template_patch,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

