"""
    ManyForge API

    Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union
from collections.abc import Iterator, AsyncIterator, Mapping
from pydantic import TypeAdapter, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr
from manyforge.model_support import JsonValue, UNSET, UnsetType
from manyforge.transport import (SyncTransport, AsyncTransport, Request, RequestOptions, QueryParameter, Upload, ByteStream, AsyncByteStream, PaginationError)
from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from uuid import UUID
from manyforge.models.company import Company
from manyforge.models.company_list import CompanyList
from manyforge.models.create_company import CreateCompany
from manyforge.models.update_company import UpdateCompany

from manyforge.models import Company

class BusinessCompaniesResource:
    def __init__(self, transport: SyncTransport, bindings: Mapping[str, str] | None = None) -> None:
        self._transport = transport
        self._bindings = dict(bindings or {})

    def create(
        self,
        *,

        create_company: CreateCompany,

        request_options: RequestOptions | None = None,
    ) -> Company:
        request = Request(
            operation_id="createCompany",
            method="POST",
            path="/api/v1/businesses/{id}/companies",
            authenticated=True,
            response=TypeAdapter(Company),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
            ),
            headers={
            },
            body=create_company,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def delete(
        self,
        *,

        coid: UUID,

        request_options: RequestOptions | None = None,
    ) -> None:
        request = Request(
            operation_id="deleteCompany",
            method="DELETE",
            path="/api/v1/businesses/{id}/companies/{coid}",
            authenticated=True,
            response=TypeAdapter(type(None)),
            path_parameters={
                "id": self._bindings["id"],
                "coid": coid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def get(
        self,
        *,

        coid: UUID,

        request_options: RequestOptions | None = None,
    ) -> Company:
        request = Request(
            operation_id="getCompany",
            method="GET",
            path="/api/v1/businesses/{id}/companies/{coid}",
            authenticated=True,
            response=TypeAdapter(Company),
            path_parameters={
                "id": self._bindings["id"],
                "coid": coid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def list(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> CompanyList:
        request = Request(
            operation_id="listCompanies",
            method="GET",
            path="/api/v1/businesses/{id}/companies",
            authenticated=True,
            response=TypeAdapter(CompanyList),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
                QueryParameter("cursor", cursor, "form", True),
                QueryParameter("limit", limit, "form", True),
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

    def iter(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> Iterator[Company]:
        seen: set[str] = set()
        next_cursor = cursor
        if isinstance(next_cursor, str) and next_cursor:
            seen.add(next_cursor)
        while True:
            page = self.list(

                cursor=next_cursor,

                limit=limit,

                request_options=request_options,
            )
            for item in page.items:
                yield item
            next_cursor = page.next_cursor
            if isinstance(next_cursor, UnsetType) or not next_cursor:
                return
            if next_cursor in seen:
                raise PaginationError("Server returned a repeated cursor")
            seen.add(next_cursor)

    def update(
        self,
        *,

        coid: UUID,

        update_company: UpdateCompany,

        request_options: RequestOptions | None = None,
    ) -> Company:
        request = Request(
            operation_id="updateCompany",
            method="PATCH",
            path="/api/v1/businesses/{id}/companies/{coid}",
            authenticated=True,
            response=TypeAdapter(Company),
            path_parameters={
                "id": self._bindings["id"],
                "coid": coid,
            },
            query=(
            ),
            headers={
            },
            body=update_company,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return self._transport.request(request, request_options=request_options)

class AsyncBusinessCompaniesResource:
    def __init__(self, transport: AsyncTransport, bindings: Mapping[str, str] | None = None) -> None:
        self._transport = transport
        self._bindings = dict(bindings or {})

    async def create(
        self,
        *,

        create_company: CreateCompany,

        request_options: RequestOptions | None = None,
    ) -> Company:
        request = Request(
            operation_id="createCompany",
            method="POST",
            path="/api/v1/businesses/{id}/companies",
            authenticated=True,
            response=TypeAdapter(Company),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
            ),
            headers={
            },
            body=create_company,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def delete(
        self,
        *,

        coid: UUID,

        request_options: RequestOptions | None = None,
    ) -> None:
        request = Request(
            operation_id="deleteCompany",
            method="DELETE",
            path="/api/v1/businesses/{id}/companies/{coid}",
            authenticated=True,
            response=TypeAdapter(type(None)),
            path_parameters={
                "id": self._bindings["id"],
                "coid": coid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def get(
        self,
        *,

        coid: UUID,

        request_options: RequestOptions | None = None,
    ) -> Company:
        request = Request(
            operation_id="getCompany",
            method="GET",
            path="/api/v1/businesses/{id}/companies/{coid}",
            authenticated=True,
            response=TypeAdapter(Company),
            path_parameters={
                "id": self._bindings["id"],
                "coid": coid,
            },
            query=(
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def list(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> CompanyList:
        request = Request(
            operation_id="listCompanies",
            method="GET",
            path="/api/v1/businesses/{id}/companies",
            authenticated=True,
            response=TypeAdapter(CompanyList),
            path_parameters={
                "id": self._bindings["id"],
            },
            query=(
                QueryParameter("cursor", cursor, "form", True),
                QueryParameter("limit", limit, "form", True),
            ),
            headers={
            },
            form={
            },


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

    async def iter(
        self,
        *,

        cursor: str | UnsetType = UNSET,

        limit: int | UnsetType = UNSET,

        request_options: RequestOptions | None = None,
    ) -> AsyncIterator[Company]:
        seen: set[str] = set()
        next_cursor = cursor
        if isinstance(next_cursor, str) and next_cursor:
            seen.add(next_cursor)
        while True:
            page = await self.list(

                cursor=next_cursor,

                limit=limit,

                request_options=request_options,
            )
            for item in page.items:
                yield item
            next_cursor = page.next_cursor
            if isinstance(next_cursor, UnsetType) or not next_cursor:
                return
            if next_cursor in seen:
                raise PaginationError("Server returned a repeated cursor")
            seen.add(next_cursor)

    async def update(
        self,
        *,

        coid: UUID,

        update_company: UpdateCompany,

        request_options: RequestOptions | None = None,
    ) -> Company:
        request = Request(
            operation_id="updateCompany",
            method="PATCH",
            path="/api/v1/businesses/{id}/companies/{coid}",
            authenticated=True,
            response=TypeAdapter(Company),
            path_parameters={
                "id": self._bindings["id"],
                "coid": coid,
            },
            query=(
            ),
            headers={
            },
            body=update_company,
            form={
            },

            content_type="application/json",


            accept="application/json",

        )
        return await self._transport.request(request, request_options=request_options)

