/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Focused OpenAPI Generator API template; native HTTP is owned by Transport.
import { Resource, PaginationError, type Transport, type RequestOptions, type ByteStream, type Upload } from '../transport.js';
import { decodeJSON, type JsonValue } from '../model-support.js';
import type { ConvertResult } from '../models/ConvertResult.js';
import type { Post } from '../models/Post.js';
import type { PostCreate } from '../models/PostCreate.js';
import type { PostPage } from '../models/PostPage.js';
import type { PostStatusUpdate } from '../models/PostStatusUpdate.js';
import type { VoteResult } from '../models/VoteResult.js';


export interface BusinessFeedbackPostsConvertParams {

    pid: string;

}


export interface BusinessFeedbackPostsCreateParams {

    bid: string;

    body: PostCreate;

}


export interface BusinessFeedbackPostsDeleteParams {

    pid: string;

}


export interface BusinessFeedbackPostsGetParams {

    pid: string;

}


export interface BusinessFeedbackPostsListParams {

    bid: string;

    cursor?: string;

    limit?: number;

}


export interface BusinessFeedbackPostsUpdateParams {

    pid: string;

    body: PostStatusUpdate;

}


export interface BusinessFeedbackPostsVoteParams {

    pid: string;

}


export class BusinessFeedbackPostsApi extends Resource {
    convert(params: BusinessFeedbackPostsConvertParams, options?: RequestOptions): Promise<ConvertResult> {
        return this.transport.request({
            operationId: 'convertFeedbackPost',
            method: 'POST',
            path: '/api/v1/businesses/{id}/feedback/posts/{pid}/convert',
            pathParams: { ...this.scope, 'pid': String(params.pid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/ConvertResult"},
            decode: (text: string) => decodeJSON<ConvertResult>(text, {"$ref":"#/components/schemas/ConvertResult"}),
        }, options);
    }
    create(params: BusinessFeedbackPostsCreateParams, options?: RequestOptions): Promise<Post> {
        return this.transport.request({
            operationId: 'createFeedbackPost',
            method: 'POST',
            path: '/api/v1/businesses/{id}/feedback/boards/{bid}/posts',
            pathParams: { ...this.scope, 'bid': String(params.bid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/PostCreate"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Post"},
            decode: (text: string) => decodeJSON<Post>(text, {"$ref":"#/components/schemas/Post"}),
        }, options);
    }
    delete(params: BusinessFeedbackPostsDeleteParams, options?: RequestOptions): Promise<void> {
        return this.transport.request({
            operationId: 'deleteFeedbackPost',
            method: 'DELETE',
            path: '/api/v1/businesses/{id}/feedback/posts/{pid}',
            pathParams: { ...this.scope, 'pid': String(params.pid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'empty',
            responseSchema: {},
            decode: (text: string) => undefined,
        }, options);
    }
    get(params: BusinessFeedbackPostsGetParams, options?: RequestOptions): Promise<Post> {
        return this.transport.request({
            operationId: 'getFeedbackPost',
            method: 'GET',
            path: '/api/v1/businesses/{id}/feedback/posts/{pid}',
            pathParams: { ...this.scope, 'pid': String(params.pid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Post"},
            decode: (text: string) => decodeJSON<Post>(text, {"$ref":"#/components/schemas/Post"}),
        }, options);
    }
    list(params: BusinessFeedbackPostsListParams, options?: RequestOptions): Promise<PostPage> {
        return this.transport.request({
            operationId: 'listFeedbackPosts',
            method: 'GET',
            path: '/api/v1/businesses/{id}/feedback/boards/{bid}/posts',
            pathParams: { ...this.scope, 'bid': String(params.bid),  },
            query: [{ name: 'cursor', value: params.cursor, style: 'form', explode: true }, { name: 'limit', value: params.limit, style: 'form', explode: true }, ],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/PostPage"},
            decode: (text: string) => decodeJSON<PostPage>(text, {"$ref":"#/components/schemas/PostPage"}),
        }, options);
    }

    async *iter(params: BusinessFeedbackPostsListParams, options?: RequestOptions): AsyncIterable<PostPage['items'][number]> {
        let cursor = params.cursor;
        const seen = new Set<string>();
        if (cursor) seen.add(cursor);
        while (true) {
            const page = await this.list({ ...params, cursor }, options);
            for (const item of page.items) yield item;
            const next = page.nextCursor;
            if (!next) return;
            if (seen.has(next)) throw new PaginationError();
            seen.add(next);
            cursor = next;
        }
    }
    update(params: BusinessFeedbackPostsUpdateParams, options?: RequestOptions): Promise<Post> {
        return this.transport.request({
            operationId: 'setFeedbackPostStatus',
            method: 'PATCH',
            path: '/api/v1/businesses/{id}/feedback/posts/{pid}',
            pathParams: { ...this.scope, 'pid': String(params.pid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/PostStatusUpdate"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Post"},
            decode: (text: string) => decodeJSON<Post>(text, {"$ref":"#/components/schemas/Post"}),
        }, options);
    }
    vote(params: BusinessFeedbackPostsVoteParams, options?: RequestOptions): Promise<VoteResult> {
        return this.transport.request({
            operationId: 'voteFeedbackPost',
            method: 'POST',
            path: '/api/v1/businesses/{id}/feedback/posts/{pid}/vote',
            pathParams: { ...this.scope, 'pid': String(params.pid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/VoteResult"},
            decode: (text: string) => decodeJSON<VoteResult>(text, {"$ref":"#/components/schemas/VoteResult"}),
        }, options);
    }
}
