/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Focused OpenAPI Generator API template; native HTTP is owned by Transport.
import { Resource, PaginationError, type Transport, type RequestOptions, type ByteStream, type Upload } from '../transport.js';
import { decodeJSON, type JsonValue } from '../model-support.js';
import type { Suppression } from '../models/Suppression.js';
import type { SuppressionInput } from '../models/SuppressionInput.js';
import type { SuppressionPage } from '../models/SuppressionPage.js';


export interface BusinessMailingSuppressionsCreateParams {

    body: SuppressionInput;

}


export interface BusinessMailingSuppressionsDeleteParams {

    sid: string;

}


export interface BusinessMailingSuppressionsListParams {

    cursor?: string;

    limit?: number;

}


export class BusinessMailingSuppressionsApi extends Resource {
    create(params: BusinessMailingSuppressionsCreateParams, options?: RequestOptions): Promise<Suppression> {
        return this.transport.request({
            operationId: 'createMailingSuppression',
            method: 'POST',
            path: '/api/v1/businesses/{id}/mailing/suppressions',
            pathParams: { ...this.scope,  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/SuppressionInput"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Suppression"},
            decode: (text: string) => decodeJSON<Suppression>(text, {"$ref":"#/components/schemas/Suppression"}),
        }, options);
    }
    delete(params: BusinessMailingSuppressionsDeleteParams, options?: RequestOptions): Promise<void> {
        return this.transport.request({
            operationId: 'deleteMailingSuppression',
            method: 'DELETE',
            path: '/api/v1/businesses/{id}/mailing/suppressions/{sid}',
            pathParams: { ...this.scope, 'sid': String(params.sid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'empty',
            responseSchema: {},
            decode: (text: string) => undefined,
        }, options);
    }
    list(params: BusinessMailingSuppressionsListParams = {}, options?: RequestOptions): Promise<SuppressionPage> {
        return this.transport.request({
            operationId: 'listMailingSuppressions',
            method: 'GET',
            path: '/api/v1/businesses/{id}/mailing/suppressions',
            pathParams: { ...this.scope,  },
            query: [{ name: 'cursor', value: params.cursor, style: 'form', explode: true }, { name: 'limit', value: params.limit, style: 'form', explode: true }, ],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/SuppressionPage"},
            decode: (text: string) => decodeJSON<SuppressionPage>(text, {"$ref":"#/components/schemas/SuppressionPage"}),
        }, options);
    }

    async *iter(params: BusinessMailingSuppressionsListParams = {}, options?: RequestOptions): AsyncIterable<SuppressionPage['items'][number]> {
        let cursor = params.cursor;
        const seen = new Set<string>();
        if (cursor) seen.add(cursor);
        while (true) {
            const page = await this.list({ ...params, cursor }, options);
            for (const item of page.items) yield item;
            const next = page.nextCursor;
            if (!next) return;
            if (seen.has(next)) throw new PaginationError();
            seen.add(next);
            cursor = next;
        }
    }
}
