/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Focused OpenAPI Generator API template; native HTTP is owned by Transport.
import { Resource, PaginationError, type Transport, type RequestOptions, type ByteStream, type Upload } from '../transport.js';
import { decodeJSON, type JsonValue } from '../model-support.js';
import type { NoteBody } from '../models/NoteBody.js';
import type { PatchTicket } from '../models/PatchTicket.js';
import type { ReplyBody } from '../models/ReplyBody.js';
import type { Ticket } from '../models/Ticket.js';
import type { TicketMessage } from '../models/TicketMessage.js';
import type { TicketPage } from '../models/TicketPage.js';
import type { TicketPriority } from '../models/TicketPriority.js';
import type { TicketStatus } from '../models/TicketStatus.js';


export interface BusinessTicketsAddNoteParams {

    tid: string;

    body: NoteBody;

}


export interface BusinessTicketsDeleteParams {

    tid: string;

}


export interface BusinessTicketsGetParams {

    tid: string;

}


export interface BusinessTicketsListParams {

    cursor?: string;

    limit?: number;

    status?: TicketStatus;

    priority?: TicketPriority;

    assignee?: string;

    tag?: string;

    search?: string;

}


export interface BusinessTicketsReplyParams {

    tid: string;

    body: ReplyBody;

}


export interface BusinessTicketsUpdateParams {

    tid: string;

    body: PatchTicket;

}


export class BusinessTicketsApi extends Resource {
    addNote(params: BusinessTicketsAddNoteParams, options?: RequestOptions): Promise<TicketMessage> {
        return this.transport.request({
            operationId: 'TicketsAddNote',
            method: 'POST',
            path: '/api/v1/businesses/{id}/tickets/{tid}/note',
            pathParams: { ...this.scope, 'tid': String(params.tid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/NoteBody"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/TicketMessage"},
            decode: (text: string) => decodeJSON<TicketMessage>(text, {"$ref":"#/components/schemas/TicketMessage"}),
        }, options);
    }
    delete(params: BusinessTicketsDeleteParams, options?: RequestOptions): Promise<void> {
        return this.transport.request({
            operationId: 'TicketsDelete',
            method: 'DELETE',
            path: '/api/v1/businesses/{id}/tickets/{tid}',
            pathParams: { ...this.scope, 'tid': String(params.tid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'empty',
            responseSchema: {},
            decode: (text: string) => undefined,
        }, options);
    }
    get(params: BusinessTicketsGetParams, options?: RequestOptions): Promise<Ticket> {
        return this.transport.request({
            operationId: 'TicketsGet',
            method: 'GET',
            path: '/api/v1/businesses/{id}/tickets/{tid}',
            pathParams: { ...this.scope, 'tid': String(params.tid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Ticket"},
            decode: (text: string) => decodeJSON<Ticket>(text, {"$ref":"#/components/schemas/Ticket"}),
        }, options);
    }
    list(params: BusinessTicketsListParams = {}, options?: RequestOptions): Promise<TicketPage> {
        return this.transport.request({
            operationId: 'TicketsList',
            method: 'GET',
            path: '/api/v1/businesses/{id}/tickets',
            pathParams: { ...this.scope,  },
            query: [{ name: 'cursor', value: params.cursor, style: 'form', explode: true }, { name: 'limit', value: params.limit, style: 'form', explode: true }, { name: 'status', value: params.status, style: 'form', explode: true }, { name: 'priority', value: params.priority, style: 'form', explode: true }, { name: 'assignee', value: params.assignee, style: 'form', explode: true }, { name: 'tag', value: params.tag, style: 'form', explode: true }, { name: 'search', value: params.search, style: 'form', explode: true }, ],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/TicketPage"},
            decode: (text: string) => decodeJSON<TicketPage>(text, {"$ref":"#/components/schemas/TicketPage"}),
        }, options);
    }

    async *iter(params: BusinessTicketsListParams = {}, options?: RequestOptions): AsyncIterable<TicketPage['items'][number]> {
        let cursor = params.cursor;
        const seen = new Set<string>();
        if (cursor) seen.add(cursor);
        while (true) {
            const page = await this.list({ ...params, cursor }, options);
            for (const item of page.items) yield item;
            const next = page.nextCursor;
            if (!next) return;
            if (seen.has(next)) throw new PaginationError();
            seen.add(next);
            cursor = next;
        }
    }
    reply(params: BusinessTicketsReplyParams, options?: RequestOptions): Promise<TicketMessage> {
        return this.transport.request({
            operationId: 'TicketsReply',
            method: 'POST',
            path: '/api/v1/businesses/{id}/tickets/{tid}/reply',
            pathParams: { ...this.scope, 'tid': String(params.tid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/ReplyBody"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/TicketMessage"},
            decode: (text: string) => decodeJSON<TicketMessage>(text, {"$ref":"#/components/schemas/TicketMessage"}),
        }, options);
    }
    update(params: BusinessTicketsUpdateParams, options?: RequestOptions): Promise<Ticket> {
        return this.transport.request({
            operationId: 'TicketsUpdate',
            method: 'PATCH',
            path: '/api/v1/businesses/{id}/tickets/{tid}',
            pathParams: { ...this.scope, 'tid': String(params.tid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/PatchTicket"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Ticket"},
            decode: (text: string) => decodeJSON<Ticket>(text, {"$ref":"#/components/schemas/Ticket"}),
        }, options);
    }
}
