/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Focused OpenAPI Generator API template; native HTTP is owned by Transport.
import { Resource, PaginationError, type Transport, type RequestOptions, type ByteStream, type Upload } from '../transport.js';
import { decodeJSON, type JsonValue } from '../model-support.js';
import type { Connector } from '../models/Connector.js';
import type { ConnectorList } from '../models/ConnectorList.js';
import type { ConnectorSyncAccepted } from '../models/ConnectorSyncAccepted.js';
import type { CreateConnector } from '../models/CreateConnector.js';
import type { TestResult } from '../models/TestResult.js';
import type { UpdateConnector } from '../models/UpdateConnector.js';


export interface BusinessConnectorsSyncParams {

    cid: string;

}


export interface BusinessConnectorsCreateParams {

    body: CreateConnector;

}


export interface BusinessConnectorsDeleteParams {

    cid: string;

}


export interface BusinessConnectorsGetParams {

    cid: string;

}


export interface BusinessConnectorsListParams {

}


export interface BusinessConnectorsTestParams {

    cid: string;

}


export interface BusinessConnectorsUpdateParams {

    cid: string;

    body: UpdateConnector;

}


export class BusinessConnectorsApi extends Resource {
    sync(params: BusinessConnectorsSyncParams, options?: RequestOptions): Promise<ConnectorSyncAccepted> {
        return this.transport.request({
            operationId: 'ConnectorsSync',
            method: 'POST',
            path: '/api/v1/businesses/{id}/connectors/{cid}/sync',
            pathParams: { ...this.scope, 'cid': String(params.cid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/ConnectorSyncAccepted"},
            decode: (text: string) => decodeJSON<ConnectorSyncAccepted>(text, {"$ref":"#/components/schemas/ConnectorSyncAccepted"}),
        }, options);
    }
    create(params: BusinessConnectorsCreateParams, options?: RequestOptions): Promise<Connector> {
        return this.transport.request({
            operationId: 'createConnector',
            method: 'POST',
            path: '/api/v1/businesses/{id}/connectors',
            pathParams: { ...this.scope,  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/CreateConnector"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Connector"},
            decode: (text: string) => decodeJSON<Connector>(text, {"$ref":"#/components/schemas/Connector"}),
        }, options);
    }
    delete(params: BusinessConnectorsDeleteParams, options?: RequestOptions): Promise<void> {
        return this.transport.request({
            operationId: 'deleteConnector',
            method: 'DELETE',
            path: '/api/v1/businesses/{id}/connectors/{cid}',
            pathParams: { ...this.scope, 'cid': String(params.cid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'empty',
            responseSchema: {},
            decode: (text: string) => undefined,
        }, options);
    }
    get(params: BusinessConnectorsGetParams, options?: RequestOptions): Promise<Connector> {
        return this.transport.request({
            operationId: 'getConnector',
            method: 'GET',
            path: '/api/v1/businesses/{id}/connectors/{cid}',
            pathParams: { ...this.scope, 'cid': String(params.cid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Connector"},
            decode: (text: string) => decodeJSON<Connector>(text, {"$ref":"#/components/schemas/Connector"}),
        }, options);
    }
    list(params: BusinessConnectorsListParams = {}, options?: RequestOptions): Promise<ConnectorList> {
        return this.transport.request({
            operationId: 'listConnectors',
            method: 'GET',
            path: '/api/v1/businesses/{id}/connectors',
            pathParams: { ...this.scope,  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/ConnectorList"},
            decode: (text: string) => decodeJSON<ConnectorList>(text, {"$ref":"#/components/schemas/ConnectorList"}),
        }, options);
    }
    test(params: BusinessConnectorsTestParams, options?: RequestOptions): Promise<TestResult> {
        return this.transport.request({
            operationId: 'testConnector',
            method: 'POST',
            path: '/api/v1/businesses/{id}/connectors/{cid}/test',
            pathParams: { ...this.scope, 'cid': String(params.cid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/TestResult"},
            decode: (text: string) => decodeJSON<TestResult>(text, {"$ref":"#/components/schemas/TestResult"}),
        }, options);
    }
    update(params: BusinessConnectorsUpdateParams, options?: RequestOptions): Promise<Connector> {
        return this.transport.request({
            operationId: 'updateConnector',
            method: 'PATCH',
            path: '/api/v1/businesses/{id}/connectors/{cid}',
            pathParams: { ...this.scope, 'cid': String(params.cid),  },
            query: [],
            headers: {  },
            authenticated: true,
            audience: 'management',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/UpdateConnector"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/Connector"},
            decode: (text: string) => decodeJSON<Connector>(text, {"$ref":"#/components/schemas/Connector"}),
        }, options);
    }
}
