/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Focused OpenAPI Generator API template; native HTTP is owned by Transport.
import { Resource, PaginationError, type Transport, type RequestOptions, type ByteStream, type Upload } from '../transport.js';
import { decodeJSON, type JsonValue } from '../model-support.js';
import type { MailingIngressError } from '../models/MailingIngressError.js';
import type { PublicError } from '../models/PublicError.js';
import type { PublicSubscriptionAccepted } from '../models/PublicSubscriptionAccepted.js';
import type { PublicSubscriptionForm } from '../models/PublicSubscriptionForm.js';
import type { PublicSubscriptionInput } from '../models/PublicSubscriptionInput.js';


export interface MailingMailingSubscribeParams {

    body: PublicSubscriptionInput;

}


export class MailingMailingApi extends Resource {
    subscribe(params: MailingMailingSubscribeParams, options?: RequestOptions): Promise<PublicSubscriptionAccepted> {
        return this.transport.request({
            operationId: 'subscribeMailingPublic',
            method: 'POST',
            path: '/api/v1/mailing/public/{key}/subscribe',
            pathParams: { ...this.scope,  },
            query: [],
            headers: {  },
            authenticated: false,
            audience: 'public',
            body: params.body,
            bodySchema: {"$ref":"#/components/schemas/PublicSubscriptionInput"},
            contentType: 'application/json',

            response: 'json',
            responseSchema: {"$ref":"#/components/schemas/PublicSubscriptionAccepted"},
            decode: (text: string) => decodeJSON<PublicSubscriptionAccepted>(text, {"$ref":"#/components/schemas/PublicSubscriptionAccepted"}),
        }, options);
    }
}
