/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import (
	"context"
	"fmt"

	"net/url"
	"strings"
)

type BusinessMcpServersResource struct {
	transport Transport
	binding   string

	ToolPolicies *BusinessMcpServersToolPoliciesResource

	Tools *BusinessMcpServersToolsResource
}

// Create invokes createMCPServer.
func (r *BusinessMcpServersResource) Create(ctx context.Context, body CreateMCPServerRequest, options ...RequestOption) (MCPServer, error) {
	path := "/api/v1/businesses/{id}/mcp_servers"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	request := Request{OperationID: "createMCPServer", Method: "POST", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}
	request.Body = body

	var result MCPServer
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}

// Delete invokes deleteMCPServer.
func (r *BusinessMcpServersResource) Delete(ctx context.Context, serverID string, options ...RequestOption) error {
	path := "/api/v1/businesses/{id}/mcp_servers/{serverID}"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	path = strings.ReplaceAll(path, "{"+"serverID"+"}", url.PathEscape(fmt.Sprint(serverID)))
	request := Request{OperationID: "deleteMCPServer", Method: "DELETE", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}

	return r.transport.Do(ctx, request, nil, options...)

}

// Get invokes getMCPServer.
func (r *BusinessMcpServersResource) Get(ctx context.Context, serverID string, options ...RequestOption) (MCPServer, error) {
	path := "/api/v1/businesses/{id}/mcp_servers/{serverID}"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	path = strings.ReplaceAll(path, "{"+"serverID"+"}", url.PathEscape(fmt.Sprint(serverID)))
	request := Request{OperationID: "getMCPServer", Method: "GET", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}

	var result MCPServer
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}

// List invokes listMCPServers.
func (r *BusinessMcpServersResource) List(ctx context.Context, options ...RequestOption) (MCPServerList, error) {
	path := "/api/v1/businesses/{id}/mcp_servers"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	request := Request{OperationID: "listMCPServers", Method: "GET", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}

	var result MCPServerList
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}

// Update invokes updateMCPServer.
func (r *BusinessMcpServersResource) Update(ctx context.Context, serverID string, body UpdateMCPServerRequest, options ...RequestOption) (MCPServer, error) {
	path := "/api/v1/businesses/{id}/mcp_servers/{serverID}"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	path = strings.ReplaceAll(path, "{"+"serverID"+"}", url.PathEscape(fmt.Sprint(serverID)))
	request := Request{OperationID: "updateMCPServer", Method: "PATCH", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}
	request.Body = body

	var result MCPServer
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}
