/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import (
	"context"
	"fmt"

	"net/url"
	"strings"
)

type BusinessFeedbackBoardsResource struct {
	transport Transport
	binding   string
}

// Create invokes createFeedbackBoard.
func (r *BusinessFeedbackBoardsResource) Create(ctx context.Context, body BoardCreate, options ...RequestOption) (Board, error) {
	path := "/api/v1/businesses/{id}/feedback/boards"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	request := Request{OperationID: "createFeedbackBoard", Method: "POST", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}
	request.Body = body

	var result Board
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}

// Get invokes getFeedbackBoard.
func (r *BusinessFeedbackBoardsResource) Get(ctx context.Context, bid string, options ...RequestOption) (Board, error) {
	path := "/api/v1/businesses/{id}/feedback/boards/{bid}"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	path = strings.ReplaceAll(path, "{"+"bid"+"}", url.PathEscape(fmt.Sprint(bid)))
	request := Request{OperationID: "getFeedbackBoard", Method: "GET", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}

	var result Board
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}

type BusinessFeedbackBoardsListParams struct {
	Cursor string
	Limit  int32
}

// List invokes listFeedbackBoards.
func (r *BusinessFeedbackBoardsResource) List(ctx context.Context, params BusinessFeedbackBoardsListParams, options ...RequestOption) (BoardPage, error) {
	path := "/api/v1/businesses/{id}/feedback/boards"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	request := Request{OperationID: "listFeedbackBoards", Method: "GET", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}

	if params.Cursor != "" {
		addQuery(request.Query, "cursor", params.Cursor, "form", true)
	}

	if params.Limit != 0 {
		addQuery(request.Query, "limit", params.Limit, "form", true)
	}

	var result BoardPage
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}

func (r *BusinessFeedbackBoardsResource) Iter(ctx context.Context, params BusinessFeedbackBoardsListParams, options ...RequestOption) *Iterator[Board] {
	return newIterator(params.Cursor, func(cursor string) ([]Board, string, error) {
		params.Cursor = cursor
		page, err := r.List(ctx, params, options...)
		if err != nil {
			return nil, "", err
		}
		next, _ := page.NextCursor.Get()
		return page.Items, next, nil
	})
}

// Update invokes updateFeedbackBoard.
func (r *BusinessFeedbackBoardsResource) Update(ctx context.Context, bid string, body BoardUpdate, options ...RequestOption) (Board, error) {
	path := "/api/v1/businesses/{id}/feedback/boards/{bid}"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	path = strings.ReplaceAll(path, "{"+"bid"+"}", url.PathEscape(fmt.Sprint(bid)))
	request := Request{OperationID: "updateFeedbackBoard", Method: "PATCH", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}
	request.Body = body

	var result Board
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}
