/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import (
	"context"
	"fmt"

	"net/url"
	"strings"
)

type BusinessAuditResource struct {
	transport Transport
	binding   string
}
type BusinessAuditListParams struct {
	Cursor string
	Limit  int32
}

// List invokes AuditList.
func (r *BusinessAuditResource) List(ctx context.Context, params BusinessAuditListParams, options ...RequestOption) (AuditPage, error) {
	path := "/api/v1/businesses/{id}/audit"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	request := Request{OperationID: "AuditList", Method: "GET", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}

	if params.Cursor != "" {
		addQuery(request.Query, "cursor", params.Cursor, "form", true)
	}

	if params.Limit != 0 {
		addQuery(request.Query, "limit", params.Limit, "form", true)
	}

	var result AuditPage
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}

func (r *BusinessAuditResource) Iter(ctx context.Context, params BusinessAuditListParams, options ...RequestOption) *Iterator[AuditEntry] {
	return newIterator(params.Cursor, func(cursor string) ([]AuditEntry, string, error) {
		params.Cursor = cursor
		page, err := r.List(ctx, params, options...)
		if err != nil {
			return nil, "", err
		}
		next, _ := page.NextCursor.Get()
		return page.Items, next, nil
	})
}
