/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import (
	"context"
	"fmt"

	"net/url"
	"strings"
)

type BusinessMcpServersToolPoliciesResource struct {
	transport Transport
	binding   string
}

// Delete invokes clearMCPToolPolicy.
func (r *BusinessMcpServersToolPoliciesResource) Delete(ctx context.Context, serverID string, toolName string, options ...RequestOption) error {
	path := "/api/v1/businesses/{id}/mcp_servers/{serverID}/tool_policies/{toolName}"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	path = strings.ReplaceAll(path, "{"+"serverID"+"}", url.PathEscape(fmt.Sprint(serverID)))
	path = strings.ReplaceAll(path, "{"+"toolName"+"}", url.PathEscape(fmt.Sprint(toolName)))
	request := Request{OperationID: "clearMCPToolPolicy", Method: "DELETE", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}

	return r.transport.Do(ctx, request, nil, options...)

}

// List invokes listMCPToolPolicies.
func (r *BusinessMcpServersToolPoliciesResource) List(ctx context.Context, serverID string, options ...RequestOption) (MCPToolPolicyList, error) {
	path := "/api/v1/businesses/{id}/mcp_servers/{serverID}/tool_policies"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	path = strings.ReplaceAll(path, "{"+"serverID"+"}", url.PathEscape(fmt.Sprint(serverID)))
	request := Request{OperationID: "listMCPToolPolicies", Method: "GET", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}

	var result MCPToolPolicyList
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}

// Replace invokes setMCPToolPolicy.
func (r *BusinessMcpServersToolPoliciesResource) Replace(ctx context.Context, serverID string, toolName string, body SetMCPToolPolicyRequest, options ...RequestOption) (MCPToolPolicy, error) {
	path := "/api/v1/businesses/{id}/mcp_servers/{serverID}/tool_policies/{toolName}"
	path = strings.ReplaceAll(path, "{"+"id"+"}", url.PathEscape(fmt.Sprint(r.binding)))
	path = strings.ReplaceAll(path, "{"+"serverID"+"}", url.PathEscape(fmt.Sprint(serverID)))
	path = strings.ReplaceAll(path, "{"+"toolName"+"}", url.PathEscape(fmt.Sprint(toolName)))
	request := Request{OperationID: "setMCPToolPolicy", Method: "PUT", Path: path, Query: url.Values{}, Headers: map[string]string{}, Authenticated: true, Audience: "management", Signing: "", BodyKey: ""}
	request.Body = body

	var result MCPToolPolicy
	err := r.transport.Do(ctx, request, &result, options...)
	return result, err

}
