/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type ReplyBody struct {
	BodyHtml Optional[string] `json:"body_html,omitzero"`
	BodyText string           `json:"body_text"`
}

// NewReplyBody assigns only the supplied required fields, never schema defaults.
func NewReplyBody(bodyText string) *ReplyBody {
	return &ReplyBody{
		BodyText: bodyText,
	}
}

func (o *ReplyBody) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "body_text")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "body_text"); err != nil {
		return err
	}
	type plain ReplyBody
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = ReplyBody(value)
	return nil
}
