/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type TenantMergeReconciliationPlan struct {
	Access            TenantMergeReconciliationAccess           `json:"access"`
	Conflicts         []TenantMergeFinding                      `json:"conflicts"`
	DestinationRootId string                                    `json:"destination_root_id"`
	Mode              string                                    `json:"mode"`
	Policies          []TenantMergeReconciliationPolicy         `json:"policies"`
	SourceRootId      string                                    `json:"source_root_id"`
	Tables            map[string]TenantMergeReconciliationTable `json:"tables"`
	Version           int32                                     `json:"version"`
}

// NewTenantMergeReconciliationPlan assigns only the supplied required fields, never schema defaults.
func NewTenantMergeReconciliationPlan(access TenantMergeReconciliationAccess, conflicts []TenantMergeFinding, destinationRootId string, mode string, policies []TenantMergeReconciliationPolicy, sourceRootId string, tables map[string]TenantMergeReconciliationTable, version int32) *TenantMergeReconciliationPlan {
	return &TenantMergeReconciliationPlan{
		Access:            access,
		Conflicts:         conflicts,
		DestinationRootId: destinationRootId,
		Mode:              mode,
		Policies:          policies,
		SourceRootId:      sourceRootId,
		Tables:            tables,
		Version:           version,
	}
}

func (o *TenantMergeReconciliationPlan) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "access", "conflicts", "destination_root_id", "mode", "policies", "source_root_id", "tables", "version")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "access", "conflicts", "destination_root_id", "mode", "policies", "source_root_id", "tables", "version"); err != nil {
		return err
	}
	type plain TenantMergeReconciliationPlan
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = TenantMergeReconciliationPlan(value)
	return nil
}
