/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type TenantMergeFinding struct {
	Bytes   Optional[int64]                  `json:"bytes,omitzero"`
	Code    string                           `json:"code"`
	Count   int64                            `json:"count"`
	Details Optional[map[string]interface{}] `json:"details,omitzero"`
	Limit   Optional[int64]                  `json:"limit,omitzero"`
	Module  string                           `json:"module"`
	Object  string                           `json:"object"`
}

// NewTenantMergeFinding assigns only the supplied required fields, never schema defaults.
func NewTenantMergeFinding(code string, count int64, module string, object string) *TenantMergeFinding {
	return &TenantMergeFinding{
		Code:   code,
		Count:  count,
		Module: module,
		Object: object,
	}
}

func (o *TenantMergeFinding) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "code", "count", "module", "object")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "bytes", "code", "count", "details", "limit", "module", "object"); err != nil {
		return err
	}
	type plain TenantMergeFinding
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = TenantMergeFinding(value)
	return nil
}
