/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type SubscriberPatch struct {
	Attributes   Optional[map[string]interface{}] `json:"attributes,omitzero"`
	FirstName    Optional[string]                 `json:"first_name,omitzero"`
	LastName     Optional[string]                 `json:"last_name,omitzero"`
	Status       Optional[SubscriberPatchStatus]  `json:"status,omitzero"`
	StatusReason Optional[string]                 `json:"status_reason,omitzero"`
	Tags         Optional[[]string]               `json:"tags,omitzero"`
}

// NewSubscriberPatch assigns only the supplied required fields, never schema defaults.
func NewSubscriberPatch() *SubscriberPatch {
	return &SubscriberPatch{}
}

func (o *SubscriberPatch) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data)
	if err != nil {
		return err
	}
	if err := nonNullFields(fields); err != nil {
		return err
	}
	type plain SubscriberPatch
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = SubscriberPatch(value)
	return nil
}
