/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type BusinessPage struct {
	Items      []Business       `json:"items"`
	NextCursor Optional[string] `json:"next_cursor,omitzero"`
}

// NewBusinessPage assigns only the supplied required fields, never schema defaults.
func NewBusinessPage(items []Business, nextCursor Optional[string]) *BusinessPage {
	return &BusinessPage{
		Items:      items,
		NextCursor: nextCursor,
	}
}

func (o *BusinessPage) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "items", "next_cursor")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "items"); err != nil {
		return err
	}
	type plain BusinessPage
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = BusinessPage(value)
	return nil
}
