/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type CreateTenantMerge struct {
	DestinationParentId string `json:"destination_parent_id"`
}

// NewCreateTenantMerge assigns only the supplied required fields, never schema defaults.
func NewCreateTenantMerge(destinationParentId string) *CreateTenantMerge {
	return &CreateTenantMerge{
		DestinationParentId: destinationParentId,
	}
}

func (o *CreateTenantMerge) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "destination_parent_id")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "destination_parent_id"); err != nil {
		return err
	}
	type plain CreateTenantMerge
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = CreateTenantMerge(value)
	return nil
}
