/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type TemplateInput struct {
	BodyMarkdown Optional[string] `json:"body_markdown,omitzero"`
	Name         string           `json:"name"`
	Preheader    Optional[string] `json:"preheader,omitzero"`
	Subject      string           `json:"subject"`
	TrackClicks  Optional[bool]   `json:"track_clicks,omitzero"`
	TrackOpens   Optional[bool]   `json:"track_opens,omitzero"`
}

// NewTemplateInput assigns only the supplied required fields, never schema defaults.
func NewTemplateInput(name string, subject string) *TemplateInput {
	return &TemplateInput{
		Name:    name,
		Subject: subject,
	}
}

func (o *TemplateInput) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "name", "subject")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "name", "subject"); err != nil {
		return err
	}
	type plain TemplateInput
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = TemplateInput(value)
	return nil
}
