/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type Role struct {
	Builtin     bool     `json:"builtin"`
	Id          string   `json:"id"`
	Key         string   `json:"key"`
	Locked      bool     `json:"locked"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
}

// NewRole assigns only the supplied required fields, never schema defaults.
func NewRole(builtin bool, id string, key string, locked bool, name string, permissions []string) *Role {
	return &Role{
		Builtin:     builtin,
		Id:          id,
		Key:         key,
		Locked:      locked,
		Name:        name,
		Permissions: permissions,
	}
}

func (o *Role) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "builtin", "id", "key", "locked", "name", "permissions")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "builtin", "id", "key", "locked", "name", "permissions"); err != nil {
		return err
	}
	type plain Role
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = Role(value)
	return nil
}
