/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type SubscriberInput struct {
	Attributes       Optional[map[string]interface{}] `json:"attributes,omitzero"`
	Email            string                           `json:"email"`
	FirstName        Optional[string]                 `json:"first_name,omitzero"`
	LastName         Optional[string]                 `json:"last_name,omitzero"`
	SkipConfirmation Optional[bool]                   `json:"skip_confirmation,omitzero"`
	Tags             Optional[[]string]               `json:"tags,omitzero"`
}

// NewSubscriberInput assigns only the supplied required fields, never schema defaults.
func NewSubscriberInput(email string) *SubscriberInput {
	return &SubscriberInput{
		Email: email,
	}
}

func (o *SubscriberInput) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "email")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "email", "skip_confirmation", "tags"); err != nil {
		return err
	}
	type plain SubscriberInput
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = SubscriberInput(value)
	return nil
}
