/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// NewError assigns only the supplied required fields, never schema defaults.
func NewError(code string, message string) *Error {
	return &Error{
		Code:    code,
		Message: message,
	}
}

func (o *Error) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "code", "message")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "code", "message"); err != nil {
		return err
	}
	type plain Error
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = Error(value)
	return nil
}
