/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type EnrollmentCounts struct {
	Active    int64 `json:"active"`
	Completed int64 `json:"completed"`
	Errored   int64 `json:"errored"`
	Exited    int64 `json:"exited"`
}

// NewEnrollmentCounts assigns only the supplied required fields, never schema defaults.
func NewEnrollmentCounts(active int64, completed int64, errored int64, exited int64) *EnrollmentCounts {
	return &EnrollmentCounts{
		Active:    active,
		Completed: completed,
		Errored:   errored,
		Exited:    exited,
	}
}

func (o *EnrollmentCounts) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "active", "completed", "errored", "exited")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "active", "completed", "errored", "exited"); err != nil {
		return err
	}
	type plain EnrollmentCounts
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = EnrollmentCounts(value)
	return nil
}
