/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type SendEmailConfig struct {
	TemplateId  string `json:"template_id"`
	TrackClicks bool   `json:"track_clicks"`
	TrackOpens  bool   `json:"track_opens"`
}

// NewSendEmailConfig assigns only the supplied required fields, never schema defaults.
func NewSendEmailConfig(templateId string, trackClicks bool, trackOpens bool) *SendEmailConfig {
	return &SendEmailConfig{
		TemplateId:  templateId,
		TrackClicks: trackClicks,
		TrackOpens:  trackOpens,
	}
}

func (o *SendEmailConfig) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "template_id", "track_clicks", "track_opens")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "template_id", "track_clicks", "track_opens"); err != nil {
		return err
	}
	type plain SendEmailConfig
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = SendEmailConfig(value)
	return nil
}
