/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import "time"

type EmailAutomationEventInput struct {
	Email          string                           `json:"email"`
	IdempotencyKey Optional[string]                 `json:"idempotency_key,omitzero"`
	Name           string                           `json:"name"`
	OccurredAt     Optional[time.Time]              `json:"occurred_at,omitzero"`
	Properties     Optional[map[string]interface{}] `json:"properties,omitzero"`
	SubscriberId   Optional[string]                 `json:"subscriber_id,omitzero"`
}

// NewEmailAutomationEventInput assigns only the supplied required fields, never schema defaults.
func NewEmailAutomationEventInput(email string, name string) *EmailAutomationEventInput {
	return &EmailAutomationEventInput{
		Email: email,
		Name:  name,
	}
}

func (o *EmailAutomationEventInput) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "email", "name")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "email", "name"); err != nil {
		return err
	}
	type plain EmailAutomationEventInput
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = EmailAutomationEventInput(value)
	return nil
}
