/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import (
	"encoding/json"
	"fmt"
)

type Node struct {
	ValidNode *ValidNode
	DraftNode *DraftNode
}

func ValidNodeAsNode(value *ValidNode) Node { return Node{ValidNode: value} }
func DraftNodeAsNode(value *DraftNode) Node { return Node{DraftNode: value} }
func (o *Node) UnmarshalJSON(data []byte) error {
	var result Node
	matches := 0
	if unionShape(data, []string{}, map[string][]string{}) {
		var value ValidNode
		if err := decodeJSON(data, &value); err == nil {
			result.ValidNode = &value
			matches++
			*o = result
			return nil
		}
	}
	if unionShape(data, []string{"config", "id", "kind"}, map[string][]string{}) {
		var value DraftNode
		if err := decodeJSON(data, &value); err == nil {
			result.DraftNode = &value
			matches++
			*o = result
			return nil
		}
	}
	if matches != 1 {
		return fmt.Errorf("JSON does not match exactly one Node alternative")
	}
	*o = result
	return nil
}
func (o Node) MarshalJSON() ([]byte, error) {
	var selected any
	matches := 0
	if o.ValidNode != nil {
		selected = o.ValidNode
		matches++
	}
	if o.DraftNode != nil {
		selected = o.DraftNode
		matches++
	}
	if matches != 1 {
		return nil, fmt.Errorf("select exactly one Node alternative")
	}
	return json.Marshal(selected)
}
