/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import "time"

type ListKey struct {
	BusinessId     string              `json:"business_id"`
	CreatedAt      time.Time           `json:"created_at"`
	HasSecret      bool                `json:"has_secret"`
	Id             string              `json:"id"`
	Label          Optional[string]    `json:"label,omitzero"`
	ListId         string              `json:"list_id"`
	PublishableKey string              `json:"publishable_key"`
	RevokedAt      Optional[time.Time] `json:"revoked_at,omitzero"`
	Status         ListKeyStatus       `json:"status"`
	TenantRootId   string              `json:"tenant_root_id"`
}

// NewListKey assigns only the supplied required fields, never schema defaults.
func NewListKey(businessId string, createdAt time.Time, hasSecret bool, id string, label Optional[string], listId string, publishableKey string, revokedAt Optional[time.Time], status ListKeyStatus, tenantRootId string) *ListKey {
	return &ListKey{
		BusinessId:     businessId,
		CreatedAt:      createdAt,
		HasSecret:      hasSecret,
		Id:             id,
		Label:          label,
		ListId:         listId,
		PublishableKey: publishableKey,
		RevokedAt:      revokedAt,
		Status:         status,
		TenantRootId:   tenantRootId,
	}
}

func (o *ListKey) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "business_id", "created_at", "has_secret", "id", "label", "list_id", "publishable_key", "revoked_at", "status", "tenant_root_id")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "business_id", "created_at", "has_secret", "id", "list_id", "publishable_key", "status", "tenant_root_id"); err != nil {
		return err
	}
	type plain ListKey
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = ListKey(value)
	return nil
}
