/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import (
	"encoding/json"
	"fmt"
)

type SendingProfileInput struct {
	RelaySendingProfileInput  *RelaySendingProfileInput
	ResendSendingProfileInput *ResendSendingProfileInput
	SESSendingProfileInput    *SESSendingProfileInput
}

func RelaySendingProfileInputAsSendingProfileInput(value *RelaySendingProfileInput) SendingProfileInput {
	return SendingProfileInput{RelaySendingProfileInput: value}
}
func ResendSendingProfileInputAsSendingProfileInput(value *ResendSendingProfileInput) SendingProfileInput {
	return SendingProfileInput{ResendSendingProfileInput: value}
}
func SESSendingProfileInputAsSendingProfileInput(value *SESSendingProfileInput) SendingProfileInput {
	return SendingProfileInput{SESSendingProfileInput: value}
}
func (o *SendingProfileInput) UnmarshalJSON(data []byte) error {
	var result SendingProfileInput
	matches := 0
	if unionShape(data, []string{"email_domain_id", "from_email", "from_name", "mode"}, map[string][]string{"mode": {"relay"}}) {
		var value RelaySendingProfileInput
		if err := decodeJSON(data, &value); err == nil {
			result.RelaySendingProfileInput = &value
			matches++
		}
	}
	if unionShape(data, []string{"from_email", "from_name", "mode"}, map[string][]string{"mode": {"resend"}}) {
		var value ResendSendingProfileInput
		if err := decodeJSON(data, &value); err == nil {
			result.ResendSendingProfileInput = &value
			matches++
		}
	}
	if unionShape(data, []string{"from_email", "from_name", "mode", "ses_configuration_set", "ses_region", "sns_topic_arn"}, map[string][]string{"mode": {"ses"}}) {
		var value SESSendingProfileInput
		if err := decodeJSON(data, &value); err == nil {
			result.SESSendingProfileInput = &value
			matches++
		}
	}
	if matches != 1 {
		return fmt.Errorf("JSON does not match exactly one SendingProfileInput alternative")
	}
	*o = result
	return nil
}
func (o SendingProfileInput) MarshalJSON() ([]byte, error) {
	var selected any
	matches := 0
	if o.RelaySendingProfileInput != nil {
		selected = o.RelaySendingProfileInput
		matches++
	}
	if o.ResendSendingProfileInput != nil {
		selected = o.ResendSendingProfileInput
		matches++
	}
	if o.SESSendingProfileInput != nil {
		selected = o.SESSendingProfileInput
		matches++
	}
	if matches != 1 {
		return nil, fmt.Errorf("select exactly one SendingProfileInput alternative")
	}
	return json.Marshal(selected)
}
