/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type MCPToolPolicy struct {
	Effect   MCPToolPolicyEffect `json:"effect"`
	ToolName string              `json:"tool_name"`
}

// NewMCPToolPolicy assigns only the supplied required fields, never schema defaults.
func NewMCPToolPolicy(effect MCPToolPolicyEffect, toolName string) *MCPToolPolicy {
	return &MCPToolPolicy{
		Effect:   effect,
		ToolName: toolName,
	}
}

func (o *MCPToolPolicy) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "effect", "tool_name")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "effect", "tool_name"); err != nil {
		return err
	}
	type plain MCPToolPolicy
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = MCPToolPolicy(value)
	return nil
}
