/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

import "time"

type RepoConnectorSummary struct {
	AllowPrivateBaseUrl bool      `json:"allow_private_base_url"`
	AutoManaged         bool      `json:"auto_managed"`
	BaseUrl             string    `json:"base_url"`
	CreatedAt           time.Time `json:"created_at"`
	DisplayName         string    `json:"display_name"`
	Id                  string    `json:"id"`
	Repo                string    `json:"repo"`
	Status              string    `json:"status"`
	Type                string    `json:"type"`
}

// NewRepoConnectorSummary assigns only the supplied required fields, never schema defaults.
func NewRepoConnectorSummary(allowPrivateBaseUrl bool, autoManaged bool, baseUrl string, createdAt time.Time, displayName string, id string, repo string, status string, type_ string) *RepoConnectorSummary {
	return &RepoConnectorSummary{
		AllowPrivateBaseUrl: allowPrivateBaseUrl,
		AutoManaged:         autoManaged,
		BaseUrl:             baseUrl,
		CreatedAt:           createdAt,
		DisplayName:         displayName,
		Id:                  id,
		Repo:                repo,
		Status:              status,
		Type:                type_,
	}
}

func (o *RepoConnectorSummary) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "allow_private_base_url", "auto_managed", "base_url", "created_at", "display_name", "id", "repo", "status", "type")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "allow_private_base_url", "auto_managed", "base_url", "created_at", "display_name", "id", "repo", "status", "type"); err != nil {
		return err
	}
	type plain RepoConnectorSummary
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = RepoConnectorSummary(value)
	return nil
}
