/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type RelaySendingProfileInput struct {
	EmailDomainId string                       `json:"email_domain_id"`
	FromEmail     string                       `json:"from_email"`
	FromName      string                       `json:"from_name"`
	Mode          RelaySendingProfileInputMode `json:"mode"`
	PostalAddress Optional[string]             `json:"postal_address,omitzero"`
	ReplyTo       Optional[string]             `json:"reply_to,omitzero"`
}

// NewRelaySendingProfileInput assigns only the supplied required fields, never schema defaults.
func NewRelaySendingProfileInput(emailDomainId string, fromEmail string, fromName string, mode RelaySendingProfileInputMode) *RelaySendingProfileInput {
	return &RelaySendingProfileInput{
		EmailDomainId: emailDomainId,
		FromEmail:     fromEmail,
		FromName:      fromName,
		Mode:          mode,
	}
}

func (o *RelaySendingProfileInput) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data, "email_domain_id", "from_email", "from_name", "mode")
	if err != nil {
		return err
	}
	if err := nonNullFields(fields, "email_domain_id", "from_email", "from_name", "mode"); err != nil {
		return err
	}
	type plain RelaySendingProfileInput
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = RelaySendingProfileInput(value)
	return nil
}
