/*
ManyForge API

Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package manyforge

type CampaignPatch struct {
	BodyMarkdown Optional[string]   `json:"body_markdown,omitzero"`
	ListId       Optional[string]   `json:"list_id,omitzero"`
	Name         Optional[string]   `json:"name,omitzero"`
	Preheader    Optional[string]   `json:"preheader,omitzero"`
	Subject      Optional[string]   `json:"subject,omitzero"`
	TagFilter    Optional[[]string] `json:"tag_filter,omitzero"`
	TrackClicks  Optional[bool]     `json:"track_clicks,omitzero"`
	TrackOpens   Optional[bool]     `json:"track_opens,omitzero"`
}

// NewCampaignPatch assigns only the supplied required fields, never schema defaults.
func NewCampaignPatch() *CampaignPatch {
	return &CampaignPatch{}
}

func (o *CampaignPatch) UnmarshalJSON(data []byte) error {
	fields, err := objectFields(data)
	if err != nil {
		return err
	}
	if err := nonNullFields(fields); err != nil {
		return err
	}
	type plain CampaignPatch
	var value plain
	if err := decodeJSON(data, &value); err != nil {
		return err
	}
	*o = CampaignPatch(value)
	return nil
}
