// Code generated by OpenAPI Generator; DO NOT EDIT.
// Copyright (c) 2026 ManyForge contributors. SPDX-License-Identifier: MIT
package manyforge

const Version = "1.202609.1"
const ReleaseVersion = "2026.9.1"
