/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Template derived from OpenAPI Generator 7.25.0 (Apache-2.0).
import { convertModel, type JsonValue } from '../model-support.js';

import type { AccountExportMembership } from './AccountExportMembership.js';
import type { Account } from './Account.js';


export interface AccountExport {
    account: Account;
    memberships: Array<AccountExportMembership>;
}



export function AccountExportFromJSON(value: unknown): AccountExport {
    return convertModel('AccountExport', value, 'decode') as AccountExport;
}

export function AccountExportToJSON(value: AccountExport): JsonValue {
    return convertModel('AccountExport', value, 'encode') as JsonValue;
}

