/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Template derived from OpenAPI Generator 7.25.0 (Apache-2.0).
import { convertModel, type JsonValue } from '../model-support.js';



export interface AnalyticsPropertyValueCount {
    events: bigint;
    value: string;
    visitors: bigint;
}



export function AnalyticsPropertyValueCountFromJSON(value: unknown): AnalyticsPropertyValueCount {
    return convertModel('AnalyticsPropertyValueCount', value, 'decode') as AnalyticsPropertyValueCount;
}

export function AnalyticsPropertyValueCountToJSON(value: AnalyticsPropertyValueCount): JsonValue {
    return convertModel('AnalyticsPropertyValueCount', value, 'encode') as JsonValue;
}

