/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Template derived from OpenAPI Generator 7.25.0 (Apache-2.0).
import { convertModel, type JsonValue } from '../model-support.js';



export interface Automation {
    activeVersionId: string | null;
    allowReenroll: boolean;
    businessId: string;
    createdAt: string;
    createdByPrincipalId: string | null;
    description: string | null;
    draftVersionId: string | null;
    id: string;
    name: string;
    status: AutomationStatusEnum;
    tenantRootId: string;
    updatedAt: string;
}

export const AutomationStatusEnum = {
    Draft: 'draft',
    Active: 'active',
    Paused: 'paused',
    Archived: 'archived',

} as const;
export type AutomationStatusEnum = typeof AutomationStatusEnum[keyof typeof AutomationStatusEnum] | (string & {});



export function AutomationFromJSON(value: unknown): Automation {
    return convertModel('Automation', value, 'decode') as Automation;
}

export function AutomationToJSON(value: Automation): JsonValue {
    return convertModel('Automation', value, 'encode') as JsonValue;
}

