/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Template derived from OpenAPI Generator 7.25.0 (Apache-2.0).
import { convertModel, type JsonValue } from '../model-support.js';

import type { CampaignStatus } from './CampaignStatus.js';


export interface Campaign {
    bodyMarkdown: string;
    bouncedCount: number;
    businessId: string;
    clickedCount: number;
    complainedCount: number;
    completedAt: string | null;
    createdAt: string;
    createdBy: string | null;
    deliveredCount: number;
    failedCount: number;
    id: string;
    lastError: string | null;
    listId: string;
    name: string;
    openedCount: number;
    preheader: string | null;
    profileId: string | null;
    recipientCount: number;
    scheduledAt: string | null;
    sentCount: number;
    startedAt: string | null;
    status: CampaignStatus;
    subject: string;
    tagFilter: Array<string>;
    tenantRootId: string;
    trackClicks: boolean;
    trackOpens: boolean;
    unsubscribedCount: number;
    updatedAt: string;
}



export function CampaignFromJSON(value: unknown): Campaign {
    return convertModel('Campaign', value, 'decode') as Campaign;
}

export function CampaignToJSON(value: Campaign): JsonValue {
    return convertModel('Campaign', value, 'encode') as JsonValue;
}

