/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Template derived from OpenAPI Generator 7.25.0 (Apache-2.0).
import { convertModel, type JsonValue } from '../model-support.js';



export interface Enrollment {
    automationId: string;
    businessId: string;
    currentNodeId: string | null;
    enrolledAt: string;
    exitReason: string | null;
    finishedAt: string | null;
    id: string;
    lastError: string | null;
    nodeAttempts: number;
    sourceEventId: string | null;
    status: EnrollmentStatusEnum;
    subscriberId: string;
    tenantRootId: string;
    updatedAt: string;
    versionId: string;
    wakeAt: string | null;
}

export const EnrollmentStatusEnum = {
    Active: 'active',
    Completed: 'completed',
    Exited: 'exited',
    Errored: 'errored',

} as const;
export type EnrollmentStatusEnum = typeof EnrollmentStatusEnum[keyof typeof EnrollmentStatusEnum] | (string & {});



export function EnrollmentFromJSON(value: unknown): Enrollment {
    return convertModel('Enrollment', value, 'decode') as Enrollment;
}

export function EnrollmentToJSON(value: Enrollment): JsonValue {
    return convertModel('Enrollment', value, 'encode') as JsonValue;
}

