/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Template derived from OpenAPI Generator 7.25.0 (Apache-2.0).
import { convertModel, type JsonValue } from '../model-support.js';

import type { Status } from './Status.js';


export interface Post {
    authorIdentity: string | null;
    authorKind: PostAuthorKindEnum;
    authorPrincipalId: string | null;
    boardId: string;
    body: string | null;
    businessId: string;
    createdAt: string;
    id: string;
    identityVerified: boolean;
    status: Status;
    tenantRootId: string;
    ticketId: string | null;
    title: string;
    updatedAt: string;
    voteCount: number;
}

export const PostAuthorKindEnum = {
    Principal: 'principal',
    Public: 'public',

} as const;
export type PostAuthorKindEnum = typeof PostAuthorKindEnum[keyof typeof PostAuthorKindEnum] | (string & {});



export function PostFromJSON(value: unknown): Post {
    return convertModel('Post', value, 'decode') as Post;
}

export function PostToJSON(value: Post): JsonValue {
    return convertModel('Post', value, 'encode') as JsonValue;
}

