/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Template derived from OpenAPI Generator 7.25.0 (Apache-2.0).
import { convertModel, type JsonValue } from '../model-support.js';



export interface PublicSubmitResult {
    deduped: boolean;
    id: string;
    identityVerified: boolean;
    status: PublicSubmitResultStatusEnum;
    title: string;
    voteCount: PublicSubmitResultVoteCountEnum;
}

export const PublicSubmitResultStatusEnum = {
    Open: 'open',

} as const;
export type PublicSubmitResultStatusEnum = typeof PublicSubmitResultStatusEnum[keyof typeof PublicSubmitResultStatusEnum] | (string & {});

export const PublicSubmitResultVoteCountEnum = {
    NUMBER_0: 0,

} as const;
export type PublicSubmitResultVoteCountEnum = typeof PublicSubmitResultVoteCountEnum[keyof typeof PublicSubmitResultVoteCountEnum];



export function PublicSubmitResultFromJSON(value: unknown): PublicSubmitResult {
    return convertModel('PublicSubmitResult', value, 'decode') as PublicSubmitResult;
}

export function PublicSubmitResultToJSON(value: PublicSubmitResult): JsonValue {
    return convertModel('PublicSubmitResult', value, 'encode') as JsonValue;
}

