/**
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// Template derived from OpenAPI Generator 7.25.0 (Apache-2.0).
import { convertModel, type JsonValue } from '../model-support.js';



export interface SignedEmailAutomationEventInput {
    email: string;
    idempotencyKey: string;
    name: string;
    occurredAt?: string | null;
    properties?: { [key: string]: JsonValue; } | null;
    subscriberId?: SignedEmailAutomationEventInputSubscriberIdEnum | null;
}

export const SignedEmailAutomationEventInputSubscriberIdEnum = {

} as const;
export type SignedEmailAutomationEventInputSubscriberIdEnum = typeof SignedEmailAutomationEventInputSubscriberIdEnum[keyof typeof SignedEmailAutomationEventInputSubscriberIdEnum] | (string & {});



export function SignedEmailAutomationEventInputFromJSON(value: unknown): SignedEmailAutomationEventInput {
    return convertModel('SignedEmailAutomationEventInput', value, 'decode') as SignedEmailAutomationEventInput;
}

export function SignedEmailAutomationEventInputToJSON(value: SignedEmailAutomationEventInput): JsonValue {
    return convertModel('SignedEmailAutomationEventInput', value, 'encode') as JsonValue;
}

