/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.AccountingTotals;
import com.manyforge.sdk.models.AccountingWindow;
import com.manyforge.sdk.models.AgentUsage;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "agents", "totals", "window" })
@com.manyforge.sdk.ModelShape(required = { "agents", "totals", "window",  }, nonNullable = { "totals", "window",  })
public class AccountingSummary {

  @JsonProperty("agents")
  private JsonNullable<List<AgentUsage>> agents = JsonNullable.undefined();

  public List<AgentUsage> getAgents() { return agents.orElse(null); }
  public JsonNullable<List<AgentUsage>> agentsPresence() { return agents; }
  public AccountingSummary agents(List<AgentUsage> value) { this.agents = JsonNullable.of(value); return this; }

  @JsonProperty("totals")
  private JsonNullable<AccountingTotals> totals = JsonNullable.undefined();

  public AccountingTotals getTotals() { return totals.orElse(null); }
  public JsonNullable<AccountingTotals> totalsPresence() { return totals; }
  public AccountingSummary totals(AccountingTotals value) { this.totals = JsonNullable.of(value); return this; }

  @JsonProperty("window")
  private JsonNullable<AccountingWindow> window = JsonNullable.undefined();

  public AccountingWindow getWindow() { return window.orElse(null); }
  public JsonNullable<AccountingWindow> windowPresence() { return window; }
  public AccountingSummary window(AccountingWindow value) { this.window = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final AccountingSummary value = new AccountingSummary();
    public Builder agents(List<AgentUsage> field) { value.agents(field); return this; }
    public Builder totals(AccountingTotals field) { value.totals(field); return this; }
    public Builder window(AccountingWindow field) { value.window(field); return this; }
    public AccountingSummary build() { return value; }
  }
}


