/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "events", "value", "visitors" })
@com.manyforge.sdk.ModelShape(required = { "events", "value", "visitors",  }, nonNullable = { "events", "value", "visitors",  })
public class AnalyticsPropertyValueCount {

  @JsonProperty("events")
  private JsonNullable<Long> events = JsonNullable.undefined();

  public Long getEvents() { return events.orElse(null); }
  public JsonNullable<Long> eventsPresence() { return events; }
  public AnalyticsPropertyValueCount events(Long value) { this.events = JsonNullable.of(value); return this; }

  @JsonProperty("value")
  private JsonNullable<String> value = JsonNullable.undefined();

  public String getValue() { return value.orElse(null); }
  public JsonNullable<String> valuePresence() { return value; }
  public AnalyticsPropertyValueCount value(String value) { this.value = JsonNullable.of(value); return this; }

  @JsonProperty("visitors")
  private JsonNullable<Long> visitors = JsonNullable.undefined();

  public Long getVisitors() { return visitors.orElse(null); }
  public JsonNullable<Long> visitorsPresence() { return visitors; }
  public AnalyticsPropertyValueCount visitors(Long value) { this.visitors = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final AnalyticsPropertyValueCount value = new AnalyticsPropertyValueCount();
    public Builder events(Long field) { value.events(field); return this; }
    public Builder value(String field) { value.value(field); return this; }
    public Builder visitors(Long field) { value.visitors(field); return this; }
    public AnalyticsPropertyValueCount build() { return value; }
  }
}


