/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "blob_key", "content_type", "filename", "id", "size" })
@com.manyforge.sdk.ModelShape(required = { "blob_key", "content_type", "filename", "id", "size",  }, nonNullable = { "blob_key", "content_type", "filename", "id", "size",  })
public class Attachment {

  @JsonProperty("blob_key")
  private JsonNullable<String> blobKey = JsonNullable.undefined();

  public String getBlobKey() { return blobKey.orElse(null); }
  public JsonNullable<String> blobKeyPresence() { return blobKey; }
  public Attachment blobKey(String value) { this.blobKey = JsonNullable.of(value); return this; }

  @JsonProperty("content_type")
  private JsonNullable<String> contentType = JsonNullable.undefined();

  public String getContentType() { return contentType.orElse(null); }
  public JsonNullable<String> contentTypePresence() { return contentType; }
  public Attachment contentType(String value) { this.contentType = JsonNullable.of(value); return this; }

  @JsonProperty("filename")
  private JsonNullable<String> filename = JsonNullable.undefined();

  public String getFilename() { return filename.orElse(null); }
  public JsonNullable<String> filenamePresence() { return filename; }
  public Attachment filename(String value) { this.filename = JsonNullable.of(value); return this; }

  @JsonProperty("id")
  private JsonNullable<UUID> id = JsonNullable.undefined();

  public UUID getId() { return id.orElse(null); }
  public JsonNullable<UUID> idPresence() { return id; }
  public Attachment id(UUID value) { this.id = JsonNullable.of(value); return this; }

  @JsonProperty("size")
  private JsonNullable<Long> size = JsonNullable.undefined();

  public Long getSize() { return size.orElse(null); }
  public JsonNullable<Long> sizePresence() { return size; }
  public Attachment size(Long value) { this.size = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final Attachment value = new Attachment();
    public Builder blobKey(String field) { value.blobKey(field); return this; }
    public Builder contentType(String field) { value.contentType(field); return this; }
    public Builder filename(String field) { value.filename(field); return this; }
    public Builder id(UUID field) { value.id(field); return this; }
    public Builder size(Long field) { value.size(field); return this; }
    public Attachment build() { return value; }
  }
}


