/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.Business;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "items", "next_cursor" })
@com.manyforge.sdk.ModelShape(required = { "items", "next_cursor",  }, nonNullable = { "items",  })
public class BusinessPage {

  @JsonProperty("items")
  private JsonNullable<List<Business>> items = JsonNullable.undefined();

  public List<Business> getItems() { return items.orElse(null); }
  public JsonNullable<List<Business>> itemsPresence() { return items; }
  public BusinessPage items(List<Business> value) { this.items = JsonNullable.of(value); return this; }
@JsonDeserialize(using = NextCursorEnum.Deserializer.class)
public static final class NextCursorEnum {

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public NextCursorEnum(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static NextCursorEnum fromValue(String value) { return new NextCursorEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof NextCursorEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<NextCursorEnum> {
    @Override public NextCursorEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new NextCursorEnum(context.readValue(parser, String.class));
    }
  }
}

  @JsonProperty("next_cursor")
  private JsonNullable<NextCursorEnum> nextCursor = JsonNullable.undefined();

  public NextCursorEnum getNextCursor() { return nextCursor.orElse(null); }
  public JsonNullable<NextCursorEnum> nextCursorPresence() { return nextCursor; }
  public BusinessPage nextCursor(NextCursorEnum value) { this.nextCursor = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final BusinessPage value = new BusinessPage();
    public Builder items(List<Business> field) { value.items(field); return this; }
    public Builder nextCursor(NextCursorEnum field) { value.nextCursor(field); return this; }
    public BusinessPage build() { return value; }
  }
}


