/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "click_count", "unique_click_count", "url" })
@com.manyforge.sdk.ModelShape(required = { "click_count", "unique_click_count", "url",  }, nonNullable = { "click_count", "unique_click_count", "url",  })
public class CampaignLinkStat {

  @JsonProperty("click_count")
  private JsonNullable<Long> clickCount = JsonNullable.undefined();

  public Long getClickCount() { return clickCount.orElse(null); }
  public JsonNullable<Long> clickCountPresence() { return clickCount; }
  public CampaignLinkStat clickCount(Long value) { this.clickCount = JsonNullable.of(value); return this; }

  @JsonProperty("unique_click_count")
  private JsonNullable<Long> uniqueClickCount = JsonNullable.undefined();

  public Long getUniqueClickCount() { return uniqueClickCount.orElse(null); }
  public JsonNullable<Long> uniqueClickCountPresence() { return uniqueClickCount; }
  public CampaignLinkStat uniqueClickCount(Long value) { this.uniqueClickCount = JsonNullable.of(value); return this; }

  @JsonProperty("url")
  private JsonNullable<URI> url = JsonNullable.undefined();

  public URI getUrl() { return url.orElse(null); }
  public JsonNullable<URI> urlPresence() { return url; }
  public CampaignLinkStat url(URI value) { this.url = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final CampaignLinkStat value = new CampaignLinkStat();
    public Builder clickCount(Long field) { value.clickCount(field); return this; }
    public Builder uniqueClickCount(Long field) { value.uniqueClickCount(field); return this; }
    public Builder url(URI field) { value.url(field); return this; }
    public CampaignLinkStat build() { return value; }
  }
}


