/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.CampaignStatus;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "body_markdown", "bounced_count", "business_id", "clicked_count", "complained_count", "completed_at", "created_at", "created_by", "delivered_count", "failed_count", "id", "last_error", "list_id", "name", "opened_count", "preheader", "profile_id", "recipient_count", "scheduled_at", "sent_count", "started_at", "status", "subject", "tag_filter", "tenant_root_id", "track_clicks", "track_opens", "unsubscribed_count", "updated_at" })
@com.manyforge.sdk.ModelShape(required = { "body_markdown", "bounced_count", "business_id", "clicked_count", "complained_count", "completed_at", "created_at", "created_by", "delivered_count", "failed_count", "id", "last_error", "list_id", "name", "opened_count", "preheader", "profile_id", "recipient_count", "scheduled_at", "sent_count", "started_at", "status", "subject", "tag_filter", "tenant_root_id", "track_clicks", "track_opens", "unsubscribed_count", "updated_at",  }, nonNullable = { "body_markdown", "bounced_count", "business_id", "clicked_count", "complained_count", "created_at", "delivered_count", "failed_count", "id", "list_id", "name", "opened_count", "recipient_count", "sent_count", "status", "subject", "tag_filter", "tenant_root_id", "track_clicks", "track_opens", "unsubscribed_count", "updated_at",  })
public class Campaign {

  @JsonProperty("body_markdown")
  private JsonNullable<String> bodyMarkdown = JsonNullable.undefined();

  public String getBodyMarkdown() { return bodyMarkdown.orElse(null); }
  public JsonNullable<String> bodyMarkdownPresence() { return bodyMarkdown; }
  public Campaign bodyMarkdown(String value) { this.bodyMarkdown = JsonNullable.of(value); return this; }

  @JsonProperty("bounced_count")
  private JsonNullable<Integer> bouncedCount = JsonNullable.undefined();

  public Integer getBouncedCount() { return bouncedCount.orElse(null); }
  public JsonNullable<Integer> bouncedCountPresence() { return bouncedCount; }
  public Campaign bouncedCount(Integer value) { this.bouncedCount = JsonNullable.of(value); return this; }

  @JsonProperty("business_id")
  private JsonNullable<UUID> businessId = JsonNullable.undefined();

  public UUID getBusinessId() { return businessId.orElse(null); }
  public JsonNullable<UUID> businessIdPresence() { return businessId; }
  public Campaign businessId(UUID value) { this.businessId = JsonNullable.of(value); return this; }

  @JsonProperty("clicked_count")
  private JsonNullable<Integer> clickedCount = JsonNullable.undefined();

  public Integer getClickedCount() { return clickedCount.orElse(null); }
  public JsonNullable<Integer> clickedCountPresence() { return clickedCount; }
  public Campaign clickedCount(Integer value) { this.clickedCount = JsonNullable.of(value); return this; }

  @JsonProperty("complained_count")
  private JsonNullable<Integer> complainedCount = JsonNullable.undefined();

  public Integer getComplainedCount() { return complainedCount.orElse(null); }
  public JsonNullable<Integer> complainedCountPresence() { return complainedCount; }
  public Campaign complainedCount(Integer value) { this.complainedCount = JsonNullable.of(value); return this; }

  @JsonProperty("completed_at")
  private JsonNullable<OffsetDateTime> completedAt = JsonNullable.undefined();

  public OffsetDateTime getCompletedAt() { return completedAt.orElse(null); }
  public JsonNullable<OffsetDateTime> completedAtPresence() { return completedAt; }
  public Campaign completedAt(OffsetDateTime value) { this.completedAt = JsonNullable.of(value); return this; }

  @JsonProperty("created_at")
  private JsonNullable<OffsetDateTime> createdAt = JsonNullable.undefined();

  public OffsetDateTime getCreatedAt() { return createdAt.orElse(null); }
  public JsonNullable<OffsetDateTime> createdAtPresence() { return createdAt; }
  public Campaign createdAt(OffsetDateTime value) { this.createdAt = JsonNullable.of(value); return this; }

  @JsonProperty("created_by")
  private JsonNullable<UUID> createdBy = JsonNullable.undefined();

  public UUID getCreatedBy() { return createdBy.orElse(null); }
  public JsonNullable<UUID> createdByPresence() { return createdBy; }
  public Campaign createdBy(UUID value) { this.createdBy = JsonNullable.of(value); return this; }

  @JsonProperty("delivered_count")
  private JsonNullable<Integer> deliveredCount = JsonNullable.undefined();

  public Integer getDeliveredCount() { return deliveredCount.orElse(null); }
  public JsonNullable<Integer> deliveredCountPresence() { return deliveredCount; }
  public Campaign deliveredCount(Integer value) { this.deliveredCount = JsonNullable.of(value); return this; }

  @JsonProperty("failed_count")
  private JsonNullable<Integer> failedCount = JsonNullable.undefined();

  public Integer getFailedCount() { return failedCount.orElse(null); }
  public JsonNullable<Integer> failedCountPresence() { return failedCount; }
  public Campaign failedCount(Integer value) { this.failedCount = JsonNullable.of(value); return this; }

  @JsonProperty("id")
  private JsonNullable<UUID> id = JsonNullable.undefined();

  public UUID getId() { return id.orElse(null); }
  public JsonNullable<UUID> idPresence() { return id; }
  public Campaign id(UUID value) { this.id = JsonNullable.of(value); return this; }

  @JsonProperty("last_error")
  private JsonNullable<String> lastError = JsonNullable.undefined();

  public String getLastError() { return lastError.orElse(null); }
  public JsonNullable<String> lastErrorPresence() { return lastError; }
  public Campaign lastError(String value) { this.lastError = JsonNullable.of(value); return this; }

  @JsonProperty("list_id")
  private JsonNullable<UUID> listId = JsonNullable.undefined();

  public UUID getListId() { return listId.orElse(null); }
  public JsonNullable<UUID> listIdPresence() { return listId; }
  public Campaign listId(UUID value) { this.listId = JsonNullable.of(value); return this; }

  @JsonProperty("name")
  private JsonNullable<String> name = JsonNullable.undefined();

  public String getName() { return name.orElse(null); }
  public JsonNullable<String> namePresence() { return name; }
  public Campaign name(String value) { this.name = JsonNullable.of(value); return this; }

  @JsonProperty("opened_count")
  private JsonNullable<Integer> openedCount = JsonNullable.undefined();

  public Integer getOpenedCount() { return openedCount.orElse(null); }
  public JsonNullable<Integer> openedCountPresence() { return openedCount; }
  public Campaign openedCount(Integer value) { this.openedCount = JsonNullable.of(value); return this; }

  @JsonProperty("preheader")
  private JsonNullable<String> preheader = JsonNullable.undefined();

  public String getPreheader() { return preheader.orElse(null); }
  public JsonNullable<String> preheaderPresence() { return preheader; }
  public Campaign preheader(String value) { this.preheader = JsonNullable.of(value); return this; }

  @JsonProperty("profile_id")
  private JsonNullable<UUID> profileId = JsonNullable.undefined();

  public UUID getProfileId() { return profileId.orElse(null); }
  public JsonNullable<UUID> profileIdPresence() { return profileId; }
  public Campaign profileId(UUID value) { this.profileId = JsonNullable.of(value); return this; }

  @JsonProperty("recipient_count")
  private JsonNullable<Integer> recipientCount = JsonNullable.undefined();

  public Integer getRecipientCount() { return recipientCount.orElse(null); }
  public JsonNullable<Integer> recipientCountPresence() { return recipientCount; }
  public Campaign recipientCount(Integer value) { this.recipientCount = JsonNullable.of(value); return this; }

  @JsonProperty("scheduled_at")
  private JsonNullable<OffsetDateTime> scheduledAt = JsonNullable.undefined();

  public OffsetDateTime getScheduledAt() { return scheduledAt.orElse(null); }
  public JsonNullable<OffsetDateTime> scheduledAtPresence() { return scheduledAt; }
  public Campaign scheduledAt(OffsetDateTime value) { this.scheduledAt = JsonNullable.of(value); return this; }

  @JsonProperty("sent_count")
  private JsonNullable<Integer> sentCount = JsonNullable.undefined();

  public Integer getSentCount() { return sentCount.orElse(null); }
  public JsonNullable<Integer> sentCountPresence() { return sentCount; }
  public Campaign sentCount(Integer value) { this.sentCount = JsonNullable.of(value); return this; }

  @JsonProperty("started_at")
  private JsonNullable<OffsetDateTime> startedAt = JsonNullable.undefined();

  public OffsetDateTime getStartedAt() { return startedAt.orElse(null); }
  public JsonNullable<OffsetDateTime> startedAtPresence() { return startedAt; }
  public Campaign startedAt(OffsetDateTime value) { this.startedAt = JsonNullable.of(value); return this; }

  @JsonProperty("status")
  private JsonNullable<CampaignStatus> status = JsonNullable.undefined();

  public CampaignStatus getStatus() { return status.orElse(null); }
  public JsonNullable<CampaignStatus> statusPresence() { return status; }
  public Campaign status(CampaignStatus value) { this.status = JsonNullable.of(value); return this; }

  @JsonProperty("subject")
  private JsonNullable<String> subject = JsonNullable.undefined();

  public String getSubject() { return subject.orElse(null); }
  public JsonNullable<String> subjectPresence() { return subject; }
  public Campaign subject(String value) { this.subject = JsonNullable.of(value); return this; }

  @JsonProperty("tag_filter")
  private JsonNullable<List<String>> tagFilter = JsonNullable.undefined();

  public List<String> getTagFilter() { return tagFilter.orElse(null); }
  public JsonNullable<List<String>> tagFilterPresence() { return tagFilter; }
  public Campaign tagFilter(List<String> value) { this.tagFilter = JsonNullable.of(value); return this; }

  @JsonProperty("tenant_root_id")
  private JsonNullable<UUID> tenantRootId = JsonNullable.undefined();

  public UUID getTenantRootId() { return tenantRootId.orElse(null); }
  public JsonNullable<UUID> tenantRootIdPresence() { return tenantRootId; }
  public Campaign tenantRootId(UUID value) { this.tenantRootId = JsonNullable.of(value); return this; }

  @JsonProperty("track_clicks")
  private JsonNullable<Boolean> trackClicks = JsonNullable.undefined();

  public Boolean getTrackClicks() { return trackClicks.orElse(null); }
  public JsonNullable<Boolean> trackClicksPresence() { return trackClicks; }
  public Campaign trackClicks(Boolean value) { this.trackClicks = JsonNullable.of(value); return this; }

  @JsonProperty("track_opens")
  private JsonNullable<Boolean> trackOpens = JsonNullable.undefined();

  public Boolean getTrackOpens() { return trackOpens.orElse(null); }
  public JsonNullable<Boolean> trackOpensPresence() { return trackOpens; }
  public Campaign trackOpens(Boolean value) { this.trackOpens = JsonNullable.of(value); return this; }

  @JsonProperty("unsubscribed_count")
  private JsonNullable<Integer> unsubscribedCount = JsonNullable.undefined();

  public Integer getUnsubscribedCount() { return unsubscribedCount.orElse(null); }
  public JsonNullable<Integer> unsubscribedCountPresence() { return unsubscribedCount; }
  public Campaign unsubscribedCount(Integer value) { this.unsubscribedCount = JsonNullable.of(value); return this; }

  @JsonProperty("updated_at")
  private JsonNullable<OffsetDateTime> updatedAt = JsonNullable.undefined();

  public OffsetDateTime getUpdatedAt() { return updatedAt.orElse(null); }
  public JsonNullable<OffsetDateTime> updatedAtPresence() { return updatedAt; }
  public Campaign updatedAt(OffsetDateTime value) { this.updatedAt = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final Campaign value = new Campaign();
    public Builder bodyMarkdown(String field) { value.bodyMarkdown(field); return this; }
    public Builder bouncedCount(Integer field) { value.bouncedCount(field); return this; }
    public Builder businessId(UUID field) { value.businessId(field); return this; }
    public Builder clickedCount(Integer field) { value.clickedCount(field); return this; }
    public Builder complainedCount(Integer field) { value.complainedCount(field); return this; }
    public Builder completedAt(OffsetDateTime field) { value.completedAt(field); return this; }
    public Builder createdAt(OffsetDateTime field) { value.createdAt(field); return this; }
    public Builder createdBy(UUID field) { value.createdBy(field); return this; }
    public Builder deliveredCount(Integer field) { value.deliveredCount(field); return this; }
    public Builder failedCount(Integer field) { value.failedCount(field); return this; }
    public Builder id(UUID field) { value.id(field); return this; }
    public Builder lastError(String field) { value.lastError(field); return this; }
    public Builder listId(UUID field) { value.listId(field); return this; }
    public Builder name(String field) { value.name(field); return this; }
    public Builder openedCount(Integer field) { value.openedCount(field); return this; }
    public Builder preheader(String field) { value.preheader(field); return this; }
    public Builder profileId(UUID field) { value.profileId(field); return this; }
    public Builder recipientCount(Integer field) { value.recipientCount(field); return this; }
    public Builder scheduledAt(OffsetDateTime field) { value.scheduledAt(field); return this; }
    public Builder sentCount(Integer field) { value.sentCount(field); return this; }
    public Builder startedAt(OffsetDateTime field) { value.startedAt(field); return this; }
    public Builder status(CampaignStatus field) { value.status(field); return this; }
    public Builder subject(String field) { value.subject(field); return this; }
    public Builder tagFilter(List<String> field) { value.tagFilter(field); return this; }
    public Builder tenantRootId(UUID field) { value.tenantRootId(field); return this; }
    public Builder trackClicks(Boolean field) { value.trackClicks(field); return this; }
    public Builder trackOpens(Boolean field) { value.trackOpens(field); return this; }
    public Builder unsubscribedCount(Integer field) { value.unsubscribedCount(field); return this; }
    public Builder updatedAt(OffsetDateTime field) { value.updatedAt(field); return this; }
    public Campaign build() { return value; }
  }
}


