/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;

@JsonDeserialize(using = CampaignStatus.Deserializer.class)
public final class CampaignStatus {

  public static final CampaignStatus DRAFT = new CampaignStatus("draft");

  public static final CampaignStatus SCHEDULED = new CampaignStatus("scheduled");

  public static final CampaignStatus SENDING = new CampaignStatus("sending");

  public static final CampaignStatus SENT = new CampaignStatus("sent");

  public static final CampaignStatus CANCELLED = new CampaignStatus("cancelled");

  public static final CampaignStatus FAILED = new CampaignStatus("failed");

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public CampaignStatus(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static CampaignStatus fromValue(String value) { return new CampaignStatus(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof CampaignStatus e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<CampaignStatus> {
    @Override public CampaignStatus deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new CampaignStatus(context.readValue(parser, String.class));
    }
  }
}


