/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.Health;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "allow_private_base_url", "base_url", "business_id", "config", "created_at", "display_name", "health", "id", "last_reconciled_at", "status", "suppress_native_notifications", "type", "updated_at" })
@com.manyforge.sdk.ModelShape(required = { "allow_private_base_url", "base_url", "business_id", "config", "created_at", "display_name", "health", "id", "last_reconciled_at", "status", "suppress_native_notifications", "type", "updated_at",  }, nonNullable = { "allow_private_base_url", "base_url", "business_id", "config", "created_at", "display_name", "health", "id", "status", "suppress_native_notifications", "type", "updated_at",  })
public class Connector {

  @JsonProperty("allow_private_base_url")
  private JsonNullable<Boolean> allowPrivateBaseUrl = JsonNullable.undefined();

  public Boolean getAllowPrivateBaseUrl() { return allowPrivateBaseUrl.orElse(null); }
  public JsonNullable<Boolean> allowPrivateBaseUrlPresence() { return allowPrivateBaseUrl; }
  public Connector allowPrivateBaseUrl(Boolean value) { this.allowPrivateBaseUrl = JsonNullable.of(value); return this; }

  @JsonProperty("base_url")
  private JsonNullable<URI> baseUrl = JsonNullable.undefined();

  public URI getBaseUrl() { return baseUrl.orElse(null); }
  public JsonNullable<URI> baseUrlPresence() { return baseUrl; }
  public Connector baseUrl(URI value) { this.baseUrl = JsonNullable.of(value); return this; }

  @JsonProperty("business_id")
  private JsonNullable<UUID> businessId = JsonNullable.undefined();

  public UUID getBusinessId() { return businessId.orElse(null); }
  public JsonNullable<UUID> businessIdPresence() { return businessId; }
  public Connector businessId(UUID value) { this.businessId = JsonNullable.of(value); return this; }

  @JsonProperty("config")
  private JsonNullable<Map<String, Object>> config = JsonNullable.undefined();

  public Map<String, Object> getConfig() { return config.orElse(null); }
  public JsonNullable<Map<String, Object>> configPresence() { return config; }
  public Connector config(Map<String, Object> value) { this.config = JsonNullable.of(value); return this; }

  @JsonProperty("created_at")
  private JsonNullable<OffsetDateTime> createdAt = JsonNullable.undefined();

  public OffsetDateTime getCreatedAt() { return createdAt.orElse(null); }
  public JsonNullable<OffsetDateTime> createdAtPresence() { return createdAt; }
  public Connector createdAt(OffsetDateTime value) { this.createdAt = JsonNullable.of(value); return this; }

  @JsonProperty("display_name")
  private JsonNullable<String> displayName = JsonNullable.undefined();

  public String getDisplayName() { return displayName.orElse(null); }
  public JsonNullable<String> displayNamePresence() { return displayName; }
  public Connector displayName(String value) { this.displayName = JsonNullable.of(value); return this; }

  @JsonProperty("health")
  private JsonNullable<Health> health = JsonNullable.undefined();

  public Health getHealth() { return health.orElse(null); }
  public JsonNullable<Health> healthPresence() { return health; }
  public Connector health(Health value) { this.health = JsonNullable.of(value); return this; }

  @JsonProperty("id")
  private JsonNullable<UUID> id = JsonNullable.undefined();

  public UUID getId() { return id.orElse(null); }
  public JsonNullable<UUID> idPresence() { return id; }
  public Connector id(UUID value) { this.id = JsonNullable.of(value); return this; }

  @JsonProperty("last_reconciled_at")
  private JsonNullable<OffsetDateTime> lastReconciledAt = JsonNullable.undefined();

  public OffsetDateTime getLastReconciledAt() { return lastReconciledAt.orElse(null); }
  public JsonNullable<OffsetDateTime> lastReconciledAtPresence() { return lastReconciledAt; }
  public Connector lastReconciledAt(OffsetDateTime value) { this.lastReconciledAt = JsonNullable.of(value); return this; }
@JsonDeserialize(using = StatusEnum.Deserializer.class)
public static final class StatusEnum {

  public static final StatusEnum ENABLED = new StatusEnum("enabled");

  public static final StatusEnum DISABLED = new StatusEnum("disabled");

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public StatusEnum(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static StatusEnum fromValue(String value) { return new StatusEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof StatusEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<StatusEnum> {
    @Override public StatusEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new StatusEnum(context.readValue(parser, String.class));
    }
  }
}

  @JsonProperty("status")
  private JsonNullable<StatusEnum> status = JsonNullable.undefined();

  public StatusEnum getStatus() { return status.orElse(null); }
  public JsonNullable<StatusEnum> statusPresence() { return status; }
  public Connector status(StatusEnum value) { this.status = JsonNullable.of(value); return this; }

  @JsonProperty("suppress_native_notifications")
  private JsonNullable<Boolean> suppressNativeNotifications = JsonNullable.undefined();

  public Boolean getSuppressNativeNotifications() { return suppressNativeNotifications.orElse(null); }
  public JsonNullable<Boolean> suppressNativeNotificationsPresence() { return suppressNativeNotifications; }
  public Connector suppressNativeNotifications(Boolean value) { this.suppressNativeNotifications = JsonNullable.of(value); return this; }
@JsonDeserialize(using = TypeEnum.Deserializer.class)
public static final class TypeEnum {

  public static final TypeEnum JIRA = new TypeEnum("jira");

  public static final TypeEnum ZENDESK = new TypeEnum("zendesk");

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public TypeEnum(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static TypeEnum fromValue(String value) { return new TypeEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof TypeEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<TypeEnum> {
    @Override public TypeEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new TypeEnum(context.readValue(parser, String.class));
    }
  }
}

  @JsonProperty("type")
  private JsonNullable<TypeEnum> type = JsonNullable.undefined();

  public TypeEnum getType() { return type.orElse(null); }
  public JsonNullable<TypeEnum> typePresence() { return type; }
  public Connector type(TypeEnum value) { this.type = JsonNullable.of(value); return this; }

  @JsonProperty("updated_at")
  private JsonNullable<OffsetDateTime> updatedAt = JsonNullable.undefined();

  public OffsetDateTime getUpdatedAt() { return updatedAt.orElse(null); }
  public JsonNullable<OffsetDateTime> updatedAtPresence() { return updatedAt; }
  public Connector updatedAt(OffsetDateTime value) { this.updatedAt = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final Connector value = new Connector();
    public Builder allowPrivateBaseUrl(Boolean field) { value.allowPrivateBaseUrl(field); return this; }
    public Builder baseUrl(URI field) { value.baseUrl(field); return this; }
    public Builder businessId(UUID field) { value.businessId(field); return this; }
    public Builder config(Map<String, Object> field) { value.config(field); return this; }
    public Builder createdAt(OffsetDateTime field) { value.createdAt(field); return this; }
    public Builder displayName(String field) { value.displayName(field); return this; }
    public Builder health(Health field) { value.health(field); return this; }
    public Builder id(UUID field) { value.id(field); return this; }
    public Builder lastReconciledAt(OffsetDateTime field) { value.lastReconciledAt(field); return this; }
    public Builder status(StatusEnum field) { value.status(field); return this; }
    public Builder suppressNativeNotifications(Boolean field) { value.suppressNativeNotifications(field); return this; }
    public Builder type(TypeEnum field) { value.type(field); return this; }
    public Builder updatedAt(OffsetDateTime field) { value.updatedAt(field); return this; }
    public Connector build() { return value; }
  }
}


