/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "allow_private_base_url", "api_key", "base_url", "chatgpt_account_id", "default_model", "provider" })
@com.manyforge.sdk.ModelShape(required = { "chatgpt_account_id", "default_model", "provider",  }, nonNullable = { "allow_private_base_url", "api_key", "base_url", "chatgpt_account_id", "default_model", "provider",  })
public class CreateCodexTokenAICredentialRequest {

  @JsonProperty("allow_private_base_url")
  private JsonNullable<Boolean> allowPrivateBaseUrl = JsonNullable.undefined();

  public Boolean getAllowPrivateBaseUrl() { return allowPrivateBaseUrl.orElse(null); }
  public JsonNullable<Boolean> allowPrivateBaseUrlPresence() { return allowPrivateBaseUrl; }
  public CreateCodexTokenAICredentialRequest allowPrivateBaseUrl(Boolean value) { this.allowPrivateBaseUrl = JsonNullable.of(value); return this; }

  @JsonProperty("api_key")
  private JsonNullable<String> apiKey = JsonNullable.undefined();

  public String getApiKey() { return apiKey.orElse(null); }
  public JsonNullable<String> apiKeyPresence() { return apiKey; }
  public CreateCodexTokenAICredentialRequest apiKey(String value) { this.apiKey = JsonNullable.of(value); return this; }

  @JsonProperty("base_url")
  private JsonNullable<String> baseUrl = JsonNullable.undefined();

  public String getBaseUrl() { return baseUrl.orElse(null); }
  public JsonNullable<String> baseUrlPresence() { return baseUrl; }
  public CreateCodexTokenAICredentialRequest baseUrl(String value) { this.baseUrl = JsonNullable.of(value); return this; }

  @JsonProperty("chatgpt_account_id")
  private JsonNullable<String> chatgptAccountId = JsonNullable.undefined();

  public String getChatgptAccountId() { return chatgptAccountId.orElse(null); }
  public JsonNullable<String> chatgptAccountIdPresence() { return chatgptAccountId; }
  public CreateCodexTokenAICredentialRequest chatgptAccountId(String value) { this.chatgptAccountId = JsonNullable.of(value); return this; }

  @JsonProperty("default_model")
  private JsonNullable<String> defaultModel = JsonNullable.undefined();

  public String getDefaultModel() { return defaultModel.orElse(null); }
  public JsonNullable<String> defaultModelPresence() { return defaultModel; }
  public CreateCodexTokenAICredentialRequest defaultModel(String value) { this.defaultModel = JsonNullable.of(value); return this; }
@JsonDeserialize(using = ProviderEnum.Deserializer.class)
public static final class ProviderEnum {

  public static final ProviderEnum OPENAI_CODEX = new ProviderEnum("openai_codex");

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public ProviderEnum(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static ProviderEnum fromValue(String value) { return new ProviderEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof ProviderEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<ProviderEnum> {
    @Override public ProviderEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new ProviderEnum(context.readValue(parser, String.class));
    }
  }
}

  @JsonProperty("provider")
  private JsonNullable<ProviderEnum> provider = JsonNullable.undefined();

  public ProviderEnum getProvider() { return provider.orElse(null); }
  public JsonNullable<ProviderEnum> providerPresence() { return provider; }
  public CreateCodexTokenAICredentialRequest provider(ProviderEnum value) { this.provider = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final CreateCodexTokenAICredentialRequest value = new CreateCodexTokenAICredentialRequest();
    public Builder allowPrivateBaseUrl(Boolean field) { value.allowPrivateBaseUrl(field); return this; }
    public Builder apiKey(String field) { value.apiKey(field); return this; }
    public Builder baseUrl(String field) { value.baseUrl(field); return this; }
    public Builder chatgptAccountId(String field) { value.chatgptAccountId(field); return this; }
    public Builder defaultModel(String field) { value.defaultModel(field); return this; }
    public Builder provider(ProviderEnum field) { value.provider(field); return this; }
    public CreateCodexTokenAICredentialRequest build() { return value; }
  }
}


