/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.DnsTxtRecord;
import java.util.Arrays;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "dkim_record", "mx_hint", "spf_hint", "verification_txt" })
@com.manyforge.sdk.ModelShape(required = { "dkim_record", "mx_hint", "spf_hint", "verification_txt",  }, nonNullable = { "dkim_record", "spf_hint", "verification_txt",  })
public class EmailDomainDnsChallenge {

  @JsonProperty("dkim_record")
  private JsonNullable<DnsTxtRecord> dkimRecord = JsonNullable.undefined();

  public DnsTxtRecord getDkimRecord() { return dkimRecord.orElse(null); }
  public JsonNullable<DnsTxtRecord> dkimRecordPresence() { return dkimRecord; }
  public EmailDomainDnsChallenge dkimRecord(DnsTxtRecord value) { this.dkimRecord = JsonNullable.of(value); return this; }

  @JsonProperty("mx_hint")
  private JsonNullable<String> mxHint = JsonNullable.undefined();

  public String getMxHint() { return mxHint.orElse(null); }
  public JsonNullable<String> mxHintPresence() { return mxHint; }
  public EmailDomainDnsChallenge mxHint(String value) { this.mxHint = JsonNullable.of(value); return this; }

  @JsonProperty("spf_hint")
  private JsonNullable<String> spfHint = JsonNullable.undefined();

  public String getSpfHint() { return spfHint.orElse(null); }
  public JsonNullable<String> spfHintPresence() { return spfHint; }
  public EmailDomainDnsChallenge spfHint(String value) { this.spfHint = JsonNullable.of(value); return this; }

  @JsonProperty("verification_txt")
  private JsonNullable<DnsTxtRecord> verificationTxt = JsonNullable.undefined();

  public DnsTxtRecord getVerificationTxt() { return verificationTxt.orElse(null); }
  public JsonNullable<DnsTxtRecord> verificationTxtPresence() { return verificationTxt; }
  public EmailDomainDnsChallenge verificationTxt(DnsTxtRecord value) { this.verificationTxt = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final EmailDomainDnsChallenge value = new EmailDomainDnsChallenge();
    public Builder dkimRecord(DnsTxtRecord field) { value.dkimRecord(field); return this; }
    public Builder mxHint(String field) { value.mxHint(field); return this; }
    public Builder spfHint(String field) { value.spfHint(field); return this; }
    public Builder verificationTxt(DnsTxtRecord field) { value.verificationTxt(field); return this; }
    public EmailDomainDnsChallenge build() { return value; }
  }
}


