/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.EnrollmentStepDetail;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "attempt", "completed_at", "delivery_id", "detail", "entered_at", "id", "node_id", "node_kind", "outcome" })
@com.manyforge.sdk.ModelShape(required = { "attempt", "completed_at", "delivery_id", "detail", "entered_at", "id", "node_id", "node_kind", "outcome",  }, nonNullable = { "attempt", "detail", "entered_at", "id", "node_id", "node_kind", "outcome",  })
public class EnrollmentStep {

  @JsonProperty("attempt")
  private JsonNullable<Integer> attempt = JsonNullable.undefined();

  public Integer getAttempt() { return attempt.orElse(null); }
  public JsonNullable<Integer> attemptPresence() { return attempt; }
  public EnrollmentStep attempt(Integer value) { this.attempt = JsonNullable.of(value); return this; }

  @JsonProperty("completed_at")
  private JsonNullable<OffsetDateTime> completedAt = JsonNullable.undefined();

  public OffsetDateTime getCompletedAt() { return completedAt.orElse(null); }
  public JsonNullable<OffsetDateTime> completedAtPresence() { return completedAt; }
  public EnrollmentStep completedAt(OffsetDateTime value) { this.completedAt = JsonNullable.of(value); return this; }

  @JsonProperty("delivery_id")
  private JsonNullable<UUID> deliveryId = JsonNullable.undefined();

  public UUID getDeliveryId() { return deliveryId.orElse(null); }
  public JsonNullable<UUID> deliveryIdPresence() { return deliveryId; }
  public EnrollmentStep deliveryId(UUID value) { this.deliveryId = JsonNullable.of(value); return this; }

  @JsonProperty("detail")
  private JsonNullable<EnrollmentStepDetail> detail = JsonNullable.undefined();

  public EnrollmentStepDetail getDetail() { return detail.orElse(null); }
  public JsonNullable<EnrollmentStepDetail> detailPresence() { return detail; }
  public EnrollmentStep detail(EnrollmentStepDetail value) { this.detail = JsonNullable.of(value); return this; }

  @JsonProperty("entered_at")
  private JsonNullable<OffsetDateTime> enteredAt = JsonNullable.undefined();

  public OffsetDateTime getEnteredAt() { return enteredAt.orElse(null); }
  public JsonNullable<OffsetDateTime> enteredAtPresence() { return enteredAt; }
  public EnrollmentStep enteredAt(OffsetDateTime value) { this.enteredAt = JsonNullable.of(value); return this; }

  @JsonProperty("id")
  private JsonNullable<UUID> id = JsonNullable.undefined();

  public UUID getId() { return id.orElse(null); }
  public JsonNullable<UUID> idPresence() { return id; }
  public EnrollmentStep id(UUID value) { this.id = JsonNullable.of(value); return this; }

  @JsonProperty("node_id")
  private JsonNullable<String> nodeId = JsonNullable.undefined();

  public String getNodeId() { return nodeId.orElse(null); }
  public JsonNullable<String> nodeIdPresence() { return nodeId; }
  public EnrollmentStep nodeId(String value) { this.nodeId = JsonNullable.of(value); return this; }

  @JsonProperty("node_kind")
  private JsonNullable<String> nodeKind = JsonNullable.undefined();

  public String getNodeKind() { return nodeKind.orElse(null); }
  public JsonNullable<String> nodeKindPresence() { return nodeKind; }
  public EnrollmentStep nodeKind(String value) { this.nodeKind = JsonNullable.of(value); return this; }
@JsonDeserialize(using = OutcomeEnum.Deserializer.class)
public static final class OutcomeEnum {

  public static final OutcomeEnum ENTERED = new OutcomeEnum("entered");

  public static final OutcomeEnum WAITING = new OutcomeEnum("waiting");

  public static final OutcomeEnum ADVANCED = new OutcomeEnum("advanced");

  public static final OutcomeEnum SENT = new OutcomeEnum("sent");

  public static final OutcomeEnum BRANCH_YES = new OutcomeEnum("branch_yes");

  public static final OutcomeEnum BRANCH_NO = new OutcomeEnum("branch_no");

  public static final OutcomeEnum EXITED = new OutcomeEnum("exited");

  public static final OutcomeEnum ERROR = new OutcomeEnum("error");

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public OutcomeEnum(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static OutcomeEnum fromValue(String value) { return new OutcomeEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof OutcomeEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<OutcomeEnum> {
    @Override public OutcomeEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new OutcomeEnum(context.readValue(parser, String.class));
    }
  }
}

  @JsonProperty("outcome")
  private JsonNullable<OutcomeEnum> outcome = JsonNullable.undefined();

  public OutcomeEnum getOutcome() { return outcome.orElse(null); }
  public JsonNullable<OutcomeEnum> outcomePresence() { return outcome; }
  public EnrollmentStep outcome(OutcomeEnum value) { this.outcome = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final EnrollmentStep value = new EnrollmentStep();
    public Builder attempt(Integer field) { value.attempt(field); return this; }
    public Builder completedAt(OffsetDateTime field) { value.completedAt(field); return this; }
    public Builder deliveryId(UUID field) { value.deliveryId(field); return this; }
    public Builder detail(EnrollmentStepDetail field) { value.detail(field); return this; }
    public Builder enteredAt(OffsetDateTime field) { value.enteredAt(field); return this; }
    public Builder id(UUID field) { value.id(field); return this; }
    public Builder nodeId(String field) { value.nodeId(field); return this; }
    public Builder nodeKind(String field) { value.nodeKind(field); return this; }
    public Builder outcome(OutcomeEnum field) { value.outcome(field); return this; }
    public EnrollmentStep build() { return value; }
  }
}


