/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({  })
@com.manyforge.sdk.ModelShape(required = {  }, nonNullable = {  })
public class ExitConfig {
  private Map<String, Object> additionalProperties;
  @JsonAnyGetter public Map<String, Object> getAdditionalProperties() {
    return additionalProperties == null ? Collections.emptyMap() : Collections.unmodifiableMap(additionalProperties);
  }
  @JsonAnySetter public void putAdditionalProperty(String name, Object value) {
    if (additionalProperties == null) additionalProperties = new LinkedHashMap<>();
    additionalProperties.put(name, value);
  }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final ExitConfig value = new ExitConfig();
    public Builder additionalProperty(String name, Object field) { value.putAdditionalProperty(name, field); return this; }
    public ExitConfig build() { return value; }
  }
}


