/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.InboundAddressKind;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "active", "address", "business_id", "created_at", "email_domain_id", "id", "kind", "tenant_root_id" })
@com.manyforge.sdk.ModelShape(required = { "active", "address", "business_id", "created_at", "email_domain_id", "id", "kind", "tenant_root_id",  }, nonNullable = { "active", "address", "business_id", "created_at", "id", "kind", "tenant_root_id",  })
public class InboundAddress {

  @JsonProperty("active")
  private JsonNullable<Boolean> active = JsonNullable.undefined();

  public Boolean getActive() { return active.orElse(null); }
  public JsonNullable<Boolean> activePresence() { return active; }
  public InboundAddress active(Boolean value) { this.active = JsonNullable.of(value); return this; }

  @JsonProperty("address")
  private JsonNullable<String> address = JsonNullable.undefined();

  public String getAddress() { return address.orElse(null); }
  public JsonNullable<String> addressPresence() { return address; }
  public InboundAddress address(String value) { this.address = JsonNullable.of(value); return this; }

  @JsonProperty("business_id")
  private JsonNullable<UUID> businessId = JsonNullable.undefined();

  public UUID getBusinessId() { return businessId.orElse(null); }
  public JsonNullable<UUID> businessIdPresence() { return businessId; }
  public InboundAddress businessId(UUID value) { this.businessId = JsonNullable.of(value); return this; }

  @JsonProperty("created_at")
  private JsonNullable<OffsetDateTime> createdAt = JsonNullable.undefined();

  public OffsetDateTime getCreatedAt() { return createdAt.orElse(null); }
  public JsonNullable<OffsetDateTime> createdAtPresence() { return createdAt; }
  public InboundAddress createdAt(OffsetDateTime value) { this.createdAt = JsonNullable.of(value); return this; }

  @JsonProperty("email_domain_id")
  private JsonNullable<UUID> emailDomainId = JsonNullable.undefined();

  public UUID getEmailDomainId() { return emailDomainId.orElse(null); }
  public JsonNullable<UUID> emailDomainIdPresence() { return emailDomainId; }
  public InboundAddress emailDomainId(UUID value) { this.emailDomainId = JsonNullable.of(value); return this; }

  @JsonProperty("id")
  private JsonNullable<UUID> id = JsonNullable.undefined();

  public UUID getId() { return id.orElse(null); }
  public JsonNullable<UUID> idPresence() { return id; }
  public InboundAddress id(UUID value) { this.id = JsonNullable.of(value); return this; }

  @JsonProperty("kind")
  private JsonNullable<InboundAddressKind> kind = JsonNullable.undefined();

  public InboundAddressKind getKind() { return kind.orElse(null); }
  public JsonNullable<InboundAddressKind> kindPresence() { return kind; }
  public InboundAddress kind(InboundAddressKind value) { this.kind = JsonNullable.of(value); return this; }

  @JsonProperty("tenant_root_id")
  private JsonNullable<UUID> tenantRootId = JsonNullable.undefined();

  public UUID getTenantRootId() { return tenantRootId.orElse(null); }
  public JsonNullable<UUID> tenantRootIdPresence() { return tenantRootId; }
  public InboundAddress tenantRootId(UUID value) { this.tenantRootId = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final InboundAddress value = new InboundAddress();
    public Builder active(Boolean field) { value.active(field); return this; }
    public Builder address(String field) { value.address(field); return this; }
    public Builder businessId(UUID field) { value.businessId(field); return this; }
    public Builder createdAt(OffsetDateTime field) { value.createdAt(field); return this; }
    public Builder emailDomainId(UUID field) { value.emailDomainId(field); return this; }
    public Builder id(UUID field) { value.id(field); return this; }
    public Builder kind(InboundAddressKind field) { value.kind(field); return this; }
    public Builder tenantRootId(UUID field) { value.tenantRootId(field); return this; }
    public InboundAddress build() { return value; }
  }
}


