/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "action", "message", "ready" })
@com.manyforge.sdk.ModelShape(required = { "action", "message", "ready",  }, nonNullable = { "action", "message", "ready",  })
public class MailingLogoStorage {

  @JsonProperty("action")
  private JsonNullable<String> action = JsonNullable.undefined();

  public String getAction() { return action.orElse(null); }
  public JsonNullable<String> actionPresence() { return action; }
  public MailingLogoStorage action(String value) { this.action = JsonNullable.of(value); return this; }

  @JsonProperty("message")
  private JsonNullable<String> message = JsonNullable.undefined();

  public String getMessage() { return message.orElse(null); }
  public JsonNullable<String> messagePresence() { return message; }
  public MailingLogoStorage message(String value) { this.message = JsonNullable.of(value); return this; }

  @JsonProperty("ready")
  private JsonNullable<Boolean> ready = JsonNullable.undefined();

  public Boolean getReady() { return ready.orElse(null); }
  public JsonNullable<Boolean> readyPresence() { return ready; }
  public MailingLogoStorage ready(Boolean value) { this.ready = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final MailingLogoStorage value = new MailingLogoStorage();
    public Builder action(String field) { value.action(field); return this; }
    public Builder message(String field) { value.message(field); return this; }
    public Builder ready(Boolean field) { value.ready(field); return this; }
    public MailingLogoStorage build() { return value; }
  }
}


