/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.MailingBrandColors;
import com.manyforge.sdk.models.MailingBrandLogo;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "business_id", "colors", "created_at", "font_stack", "footer_markdown", "id", "logo", "logo_width", "name", "tenant_root_id", "updated_at" })
@com.manyforge.sdk.ModelShape(required = { "business_id", "colors", "created_at", "font_stack", "footer_markdown", "id", "logo", "logo_width", "name", "tenant_root_id", "updated_at",  }, nonNullable = { "business_id", "colors", "created_at", "font_stack", "footer_markdown", "id", "logo_width", "name", "tenant_root_id", "updated_at",  })
public class MailingBrand {

  @JsonProperty("business_id")
  private JsonNullable<UUID> businessId = JsonNullable.undefined();

  public UUID getBusinessId() { return businessId.orElse(null); }
  public JsonNullable<UUID> businessIdPresence() { return businessId; }
  public MailingBrand businessId(UUID value) { this.businessId = JsonNullable.of(value); return this; }

  @JsonProperty("colors")
  private JsonNullable<MailingBrandColors> colors = JsonNullable.undefined();

  public MailingBrandColors getColors() { return colors.orElse(null); }
  public JsonNullable<MailingBrandColors> colorsPresence() { return colors; }
  public MailingBrand colors(MailingBrandColors value) { this.colors = JsonNullable.of(value); return this; }

  @JsonProperty("created_at")
  private JsonNullable<OffsetDateTime> createdAt = JsonNullable.undefined();

  public OffsetDateTime getCreatedAt() { return createdAt.orElse(null); }
  public JsonNullable<OffsetDateTime> createdAtPresence() { return createdAt; }
  public MailingBrand createdAt(OffsetDateTime value) { this.createdAt = JsonNullable.of(value); return this; }
@JsonDeserialize(using = FontStackEnum.Deserializer.class)
public static final class FontStackEnum {

  public static final FontStackEnum SYSTEM = new FontStackEnum("system");

  public static final FontStackEnum SERIF = new FontStackEnum("serif");

  public static final FontStackEnum MONO = new FontStackEnum("mono");

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public FontStackEnum(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static FontStackEnum fromValue(String value) { return new FontStackEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof FontStackEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<FontStackEnum> {
    @Override public FontStackEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new FontStackEnum(context.readValue(parser, String.class));
    }
  }
}

  @JsonProperty("font_stack")
  private JsonNullable<FontStackEnum> fontStack = JsonNullable.undefined();

  public FontStackEnum getFontStack() { return fontStack.orElse(null); }
  public JsonNullable<FontStackEnum> fontStackPresence() { return fontStack; }
  public MailingBrand fontStack(FontStackEnum value) { this.fontStack = JsonNullable.of(value); return this; }

  @JsonProperty("footer_markdown")
  private JsonNullable<String> footerMarkdown = JsonNullable.undefined();

  public String getFooterMarkdown() { return footerMarkdown.orElse(null); }
  public JsonNullable<String> footerMarkdownPresence() { return footerMarkdown; }
  public MailingBrand footerMarkdown(String value) { this.footerMarkdown = JsonNullable.of(value); return this; }

  @JsonProperty("id")
  private JsonNullable<UUID> id = JsonNullable.undefined();

  public UUID getId() { return id.orElse(null); }
  public JsonNullable<UUID> idPresence() { return id; }
  public MailingBrand id(UUID value) { this.id = JsonNullable.of(value); return this; }

  @JsonProperty("logo")
  private JsonNullable<MailingBrandLogo> logo = JsonNullable.undefined();

  public MailingBrandLogo getLogo() { return logo.orElse(null); }
  public JsonNullable<MailingBrandLogo> logoPresence() { return logo; }
  public MailingBrand logo(MailingBrandLogo value) { this.logo = JsonNullable.of(value); return this; }

  @JsonProperty("logo_width")
  private JsonNullable<Integer> logoWidth = JsonNullable.undefined();

  public Integer getLogoWidth() { return logoWidth.orElse(null); }
  public JsonNullable<Integer> logoWidthPresence() { return logoWidth; }
  public MailingBrand logoWidth(Integer value) { this.logoWidth = JsonNullable.of(value); return this; }

  @JsonProperty("name")
  private JsonNullable<String> name = JsonNullable.undefined();

  public String getName() { return name.orElse(null); }
  public JsonNullable<String> namePresence() { return name; }
  public MailingBrand name(String value) { this.name = JsonNullable.of(value); return this; }

  @JsonProperty("tenant_root_id")
  private JsonNullable<UUID> tenantRootId = JsonNullable.undefined();

  public UUID getTenantRootId() { return tenantRootId.orElse(null); }
  public JsonNullable<UUID> tenantRootIdPresence() { return tenantRootId; }
  public MailingBrand tenantRootId(UUID value) { this.tenantRootId = JsonNullable.of(value); return this; }

  @JsonProperty("updated_at")
  private JsonNullable<OffsetDateTime> updatedAt = JsonNullable.undefined();

  public OffsetDateTime getUpdatedAt() { return updatedAt.orElse(null); }
  public JsonNullable<OffsetDateTime> updatedAtPresence() { return updatedAt; }
  public MailingBrand updatedAt(OffsetDateTime value) { this.updatedAt = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final MailingBrand value = new MailingBrand();
    public Builder businessId(UUID field) { value.businessId(field); return this; }
    public Builder colors(MailingBrandColors field) { value.colors(field); return this; }
    public Builder createdAt(OffsetDateTime field) { value.createdAt(field); return this; }
    public Builder fontStack(FontStackEnum field) { value.fontStack(field); return this; }
    public Builder footerMarkdown(String field) { value.footerMarkdown(field); return this; }
    public Builder id(UUID field) { value.id(field); return this; }
    public Builder logo(MailingBrandLogo field) { value.logo(field); return this; }
    public Builder logoWidth(Integer field) { value.logoWidth(field); return this; }
    public Builder name(String field) { value.name(field); return this; }
    public Builder tenantRootId(UUID field) { value.tenantRootId(field); return this; }
    public Builder updatedAt(OffsetDateTime field) { value.updatedAt(field); return this; }
    public MailingBrand build() { return value; }
  }
}


