/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "html", "text" })
@com.manyforge.sdk.ModelShape(required = { "html", "text",  }, nonNullable = { "html", "text",  })
public class PreviewOutput {

  @JsonProperty("html")
  private JsonNullable<String> html = JsonNullable.undefined();

  public String getHtml() { return html.orElse(null); }
  public JsonNullable<String> htmlPresence() { return html; }
  public PreviewOutput html(String value) { this.html = JsonNullable.of(value); return this; }

  @JsonProperty("text")
  private JsonNullable<String> text = JsonNullable.undefined();

  public String getText() { return text.orElse(null); }
  public JsonNullable<String> textPresence() { return text; }
  public PreviewOutput text(String value) { this.text = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final PreviewOutput value = new PreviewOutput();
    public Builder html(String field) { value.html(field); return this; }
    public Builder text(String field) { value.text(field); return this; }
    public PreviewOutput build() { return value; }
  }
}


