/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "phase", "preview", "tokens" })
@com.manyforge.sdk.ModelShape(required = { "phase", "preview", "tokens",  }, nonNullable = { "phase", "preview", "tokens",  })
public class ReviewProgress {

  @JsonProperty("phase")
  private JsonNullable<String> phase = JsonNullable.undefined();

  public String getPhase() { return phase.orElse(null); }
  public JsonNullable<String> phasePresence() { return phase; }
  public ReviewProgress phase(String value) { this.phase = JsonNullable.of(value); return this; }

  @JsonProperty("preview")
  private JsonNullable<String> preview = JsonNullable.undefined();

  public String getPreview() { return preview.orElse(null); }
  public JsonNullable<String> previewPresence() { return preview; }
  public ReviewProgress preview(String value) { this.preview = JsonNullable.of(value); return this; }

  @JsonProperty("tokens")
  private JsonNullable<Integer> tokens = JsonNullable.undefined();

  public Integer getTokens() { return tokens.orElse(null); }
  public JsonNullable<Integer> tokensPresence() { return tokens; }
  public ReviewProgress tokens(Integer value) { this.tokens = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final ReviewProgress value = new ReviewProgress();
    public Builder phase(String field) { value.phase(field); return this; }
    public Builder preview(String field) { value.preview(field); return this; }
    public Builder tokens(Integer field) { value.tokens(field); return this; }
    public ReviewProgress build() { return value; }
  }
}


