/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "attributes", "email", "first_name", "last_name", "skip_confirmation", "tags" })
@com.manyforge.sdk.ModelShape(required = { "email",  }, nonNullable = { "email", "skip_confirmation", "tags",  })
public class SubscriberInput {

  @JsonProperty("attributes")
  private JsonNullable<Map<String, Object>> attributes = JsonNullable.undefined();

  public Map<String, Object> getAttributes() { return attributes.orElse(null); }
  public JsonNullable<Map<String, Object>> attributesPresence() { return attributes; }
  public SubscriberInput attributes(Map<String, Object> value) { this.attributes = JsonNullable.of(value); return this; }

  @JsonProperty("email")
  private JsonNullable<String> email = JsonNullable.undefined();

  public String getEmail() { return email.orElse(null); }
  public JsonNullable<String> emailPresence() { return email; }
  public SubscriberInput email(String value) { this.email = JsonNullable.of(value); return this; }

  @JsonProperty("first_name")
  private JsonNullable<String> firstName = JsonNullable.undefined();

  public String getFirstName() { return firstName.orElse(null); }
  public JsonNullable<String> firstNamePresence() { return firstName; }
  public SubscriberInput firstName(String value) { this.firstName = JsonNullable.of(value); return this; }

  @JsonProperty("last_name")
  private JsonNullable<String> lastName = JsonNullable.undefined();

  public String getLastName() { return lastName.orElse(null); }
  public JsonNullable<String> lastNamePresence() { return lastName; }
  public SubscriberInput lastName(String value) { this.lastName = JsonNullable.of(value); return this; }

  @JsonProperty("skip_confirmation")
  private JsonNullable<Boolean> skipConfirmation = JsonNullable.undefined();

  public Boolean getSkipConfirmation() { return skipConfirmation.orElse(null); }
  public JsonNullable<Boolean> skipConfirmationPresence() { return skipConfirmation; }
  public SubscriberInput skipConfirmation(Boolean value) { this.skipConfirmation = JsonNullable.of(value); return this; }

  @JsonProperty("tags")
  private JsonNullable<List<String>> tags = JsonNullable.undefined();

  public List<String> getTags() { return tags.orElse(null); }
  public JsonNullable<List<String>> tagsPresence() { return tags; }
  public SubscriberInput tags(List<String> value) { this.tags = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final SubscriberInput value = new SubscriberInput();
    public Builder attributes(Map<String, Object> field) { value.attributes(field); return this; }
    public Builder email(String field) { value.email(field); return this; }
    public Builder firstName(String field) { value.firstName(field); return this; }
    public Builder lastName(String field) { value.lastName(field); return this; }
    public Builder skipConfirmation(Boolean field) { value.skipConfirmation(field); return this; }
    public Builder tags(List<String> field) { value.tags(field); return this; }
    public SubscriberInput build() { return value; }
  }
}


