/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.SuppressionReason;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "business_id", "created_at", "email", "id", "reason", "source", "tenant_root_id" })
@com.manyforge.sdk.ModelShape(required = { "business_id", "created_at", "email", "id", "reason", "source", "tenant_root_id",  }, nonNullable = { "business_id", "created_at", "email", "id", "reason", "source", "tenant_root_id",  })
public class Suppression {

  @JsonProperty("business_id")
  private JsonNullable<UUID> businessId = JsonNullable.undefined();

  public UUID getBusinessId() { return businessId.orElse(null); }
  public JsonNullable<UUID> businessIdPresence() { return businessId; }
  public Suppression businessId(UUID value) { this.businessId = JsonNullable.of(value); return this; }

  @JsonProperty("created_at")
  private JsonNullable<OffsetDateTime> createdAt = JsonNullable.undefined();

  public OffsetDateTime getCreatedAt() { return createdAt.orElse(null); }
  public JsonNullable<OffsetDateTime> createdAtPresence() { return createdAt; }
  public Suppression createdAt(OffsetDateTime value) { this.createdAt = JsonNullable.of(value); return this; }

  @JsonProperty("email")
  private JsonNullable<String> email = JsonNullable.undefined();

  public String getEmail() { return email.orElse(null); }
  public JsonNullable<String> emailPresence() { return email; }
  public Suppression email(String value) { this.email = JsonNullable.of(value); return this; }

  @JsonProperty("id")
  private JsonNullable<UUID> id = JsonNullable.undefined();

  public UUID getId() { return id.orElse(null); }
  public JsonNullable<UUID> idPresence() { return id; }
  public Suppression id(UUID value) { this.id = JsonNullable.of(value); return this; }

  @JsonProperty("reason")
  private JsonNullable<SuppressionReason> reason = JsonNullable.undefined();

  public SuppressionReason getReason() { return reason.orElse(null); }
  public JsonNullable<SuppressionReason> reasonPresence() { return reason; }
  public Suppression reason(SuppressionReason value) { this.reason = JsonNullable.of(value); return this; }

  @JsonProperty("source")
  private JsonNullable<String> source = JsonNullable.undefined();

  public String getSource() { return source.orElse(null); }
  public JsonNullable<String> sourcePresence() { return source; }
  public Suppression source(String value) { this.source = JsonNullable.of(value); return this; }

  @JsonProperty("tenant_root_id")
  private JsonNullable<UUID> tenantRootId = JsonNullable.undefined();

  public UUID getTenantRootId() { return tenantRootId.orElse(null); }
  public JsonNullable<UUID> tenantRootIdPresence() { return tenantRootId; }
  public Suppression tenantRootId(UUID value) { this.tenantRootId = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final Suppression value = new Suppression();
    public Builder businessId(UUID field) { value.businessId(field); return this; }
    public Builder createdAt(OffsetDateTime field) { value.createdAt(field); return this; }
    public Builder email(String field) { value.email(field); return this; }
    public Builder id(UUID field) { value.id(field); return this; }
    public Builder reason(SuppressionReason field) { value.reason(field); return this; }
    public Builder source(String field) { value.source(field); return this; }
    public Builder tenantRootId(UUID field) { value.tenantRootId(field); return this; }
    public Suppression build() { return value; }
  }
}


