/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "action", "count", "identity_digest", "key", "permission_count", "permission_digest" })
@com.manyforge.sdk.ModelShape(required = { "action", "count", "key",  }, nonNullable = { "action", "count", "identity_digest", "key", "permission_count", "permission_digest",  })
public class TenantMergeReconciliationPolicy {

  @JsonProperty("action")
  private JsonNullable<String> action = JsonNullable.undefined();

  public String getAction() { return action.orElse(null); }
  public JsonNullable<String> actionPresence() { return action; }
  public TenantMergeReconciliationPolicy action(String value) { this.action = JsonNullable.of(value); return this; }

  @JsonProperty("count")
  private JsonNullable<Long> count = JsonNullable.undefined();

  public Long getCount() { return count.orElse(null); }
  public JsonNullable<Long> countPresence() { return count; }
  public TenantMergeReconciliationPolicy count(Long value) { this.count = JsonNullable.of(value); return this; }

  @JsonProperty("identity_digest")
  private JsonNullable<String> identityDigest = JsonNullable.undefined();

  public String getIdentityDigest() { return identityDigest.orElse(null); }
  public JsonNullable<String> identityDigestPresence() { return identityDigest; }
  public TenantMergeReconciliationPolicy identityDigest(String value) { this.identityDigest = JsonNullable.of(value); return this; }

  @JsonProperty("key")
  private JsonNullable<String> key = JsonNullable.undefined();

  public String getKey() { return key.orElse(null); }
  public JsonNullable<String> keyPresence() { return key; }
  public TenantMergeReconciliationPolicy key(String value) { this.key = JsonNullable.of(value); return this; }

  @JsonProperty("permission_count")
  private JsonNullable<Long> permissionCount = JsonNullable.undefined();

  public Long getPermissionCount() { return permissionCount.orElse(null); }
  public JsonNullable<Long> permissionCountPresence() { return permissionCount; }
  public TenantMergeReconciliationPolicy permissionCount(Long value) { this.permissionCount = JsonNullable.of(value); return this; }

  @JsonProperty("permission_digest")
  private JsonNullable<String> permissionDigest = JsonNullable.undefined();

  public String getPermissionDigest() { return permissionDigest.orElse(null); }
  public JsonNullable<String> permissionDigestPresence() { return permissionDigest; }
  public TenantMergeReconciliationPolicy permissionDigest(String value) { this.permissionDigest = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final TenantMergeReconciliationPolicy value = new TenantMergeReconciliationPolicy();
    public Builder action(String field) { value.action(field); return this; }
    public Builder count(Long field) { value.count(field); return this; }
    public Builder identityDigest(String field) { value.identityDigest(field); return this; }
    public Builder key(String field) { value.key(field); return this; }
    public Builder permissionCount(Long field) { value.permissionCount(field); return this; }
    public Builder permissionDigest(String field) { value.permissionDigest(field); return this; }
    public TenantMergeReconciliationPolicy build() { return value; }
  }
}


