/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.TenantMergeDestination;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "destinations", "source_root_id", "source_root_name" })
@com.manyforge.sdk.ModelShape(required = { "destinations", "source_root_id", "source_root_name",  }, nonNullable = { "destinations", "source_root_id", "source_root_name",  })
public class TenantMergeSourceOptions {

  @JsonProperty("destinations")
  private JsonNullable<List<TenantMergeDestination>> destinations = JsonNullable.undefined();

  public List<TenantMergeDestination> getDestinations() { return destinations.orElse(null); }
  public JsonNullable<List<TenantMergeDestination>> destinationsPresence() { return destinations; }
  public TenantMergeSourceOptions destinations(List<TenantMergeDestination> value) { this.destinations = JsonNullable.of(value); return this; }

  @JsonProperty("source_root_id")
  private JsonNullable<UUID> sourceRootId = JsonNullable.undefined();

  public UUID getSourceRootId() { return sourceRootId.orElse(null); }
  public JsonNullable<UUID> sourceRootIdPresence() { return sourceRootId; }
  public TenantMergeSourceOptions sourceRootId(UUID value) { this.sourceRootId = JsonNullable.of(value); return this; }

  @JsonProperty("source_root_name")
  private JsonNullable<String> sourceRootName = JsonNullable.undefined();

  public String getSourceRootName() { return sourceRootName.orElse(null); }
  public JsonNullable<String> sourceRootNamePresence() { return sourceRootName; }
  public TenantMergeSourceOptions sourceRootName(String value) { this.sourceRootName = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final TenantMergeSourceOptions value = new TenantMergeSourceOptions();
    public Builder destinations(List<TenantMergeDestination> field) { value.destinations(field); return this; }
    public Builder sourceRootId(UUID field) { value.sourceRootId(field); return this; }
    public Builder sourceRootName(String field) { value.sourceRootName(field); return this; }
    public TenantMergeSourceOptions build() { return value; }
  }
}


