/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manyforge.sdk.models.Attachment;
import com.manyforge.sdk.models.DnsRecordState;
import com.manyforge.sdk.models.MessageDirection;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "attachments", "author_principal_id", "body_html", "body_text", "created_at", "delivery_state", "direction", "dkim_result", "dmarc_result", "id", "in_reply_to", "message_id", "references", "spf_result", "ticket_id" })
@com.manyforge.sdk.ModelShape(required = { "attachments", "author_principal_id", "body_html", "body_text", "created_at", "delivery_state", "direction", "dkim_result", "dmarc_result", "id", "in_reply_to", "message_id", "references", "spf_result", "ticket_id",  }, nonNullable = { "attachments", "created_at", "direction", "dkim_result", "dmarc_result", "id", "references", "spf_result", "ticket_id",  })
public class TicketMessage {

  @JsonProperty("attachments")
  private JsonNullable<List<Attachment>> attachments = JsonNullable.undefined();

  public List<Attachment> getAttachments() { return attachments.orElse(null); }
  public JsonNullable<List<Attachment>> attachmentsPresence() { return attachments; }
  public TicketMessage attachments(List<Attachment> value) { this.attachments = JsonNullable.of(value); return this; }

  @JsonProperty("author_principal_id")
  private JsonNullable<UUID> authorPrincipalId = JsonNullable.undefined();

  public UUID getAuthorPrincipalId() { return authorPrincipalId.orElse(null); }
  public JsonNullable<UUID> authorPrincipalIdPresence() { return authorPrincipalId; }
  public TicketMessage authorPrincipalId(UUID value) { this.authorPrincipalId = JsonNullable.of(value); return this; }

  @JsonProperty("body_html")
  private JsonNullable<String> bodyHtml = JsonNullable.undefined();

  public String getBodyHtml() { return bodyHtml.orElse(null); }
  public JsonNullable<String> bodyHtmlPresence() { return bodyHtml; }
  public TicketMessage bodyHtml(String value) { this.bodyHtml = JsonNullable.of(value); return this; }

  @JsonProperty("body_text")
  private JsonNullable<String> bodyText = JsonNullable.undefined();

  public String getBodyText() { return bodyText.orElse(null); }
  public JsonNullable<String> bodyTextPresence() { return bodyText; }
  public TicketMessage bodyText(String value) { this.bodyText = JsonNullable.of(value); return this; }

  @JsonProperty("created_at")
  private JsonNullable<OffsetDateTime> createdAt = JsonNullable.undefined();

  public OffsetDateTime getCreatedAt() { return createdAt.orElse(null); }
  public JsonNullable<OffsetDateTime> createdAtPresence() { return createdAt; }
  public TicketMessage createdAt(OffsetDateTime value) { this.createdAt = JsonNullable.of(value); return this; }
@JsonDeserialize(using = DeliveryStateEnum.Deserializer.class)
public static final class DeliveryStateEnum {

  public static final DeliveryStateEnum PENDING = new DeliveryStateEnum("pending");

  public static final DeliveryStateEnum SENT = new DeliveryStateEnum("sent");

  public static final DeliveryStateEnum FAILED = new DeliveryStateEnum("failed");

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public DeliveryStateEnum(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static DeliveryStateEnum fromValue(String value) { return new DeliveryStateEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof DeliveryStateEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<DeliveryStateEnum> {
    @Override public DeliveryStateEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new DeliveryStateEnum(context.readValue(parser, String.class));
    }
  }
}

  @JsonProperty("delivery_state")
  private JsonNullable<DeliveryStateEnum> deliveryState = JsonNullable.undefined();

  public DeliveryStateEnum getDeliveryState() { return deliveryState.orElse(null); }
  public JsonNullable<DeliveryStateEnum> deliveryStatePresence() { return deliveryState; }
  public TicketMessage deliveryState(DeliveryStateEnum value) { this.deliveryState = JsonNullable.of(value); return this; }

  @JsonProperty("direction")
  private JsonNullable<MessageDirection> direction = JsonNullable.undefined();

  public MessageDirection getDirection() { return direction.orElse(null); }
  public JsonNullable<MessageDirection> directionPresence() { return direction; }
  public TicketMessage direction(MessageDirection value) { this.direction = JsonNullable.of(value); return this; }

  @JsonProperty("dkim_result")
  private JsonNullable<DnsRecordState> dkimResult = JsonNullable.undefined();

  public DnsRecordState getDkimResult() { return dkimResult.orElse(null); }
  public JsonNullable<DnsRecordState> dkimResultPresence() { return dkimResult; }
  public TicketMessage dkimResult(DnsRecordState value) { this.dkimResult = JsonNullable.of(value); return this; }

  @JsonProperty("dmarc_result")
  private JsonNullable<DnsRecordState> dmarcResult = JsonNullable.undefined();

  public DnsRecordState getDmarcResult() { return dmarcResult.orElse(null); }
  public JsonNullable<DnsRecordState> dmarcResultPresence() { return dmarcResult; }
  public TicketMessage dmarcResult(DnsRecordState value) { this.dmarcResult = JsonNullable.of(value); return this; }

  @JsonProperty("id")
  private JsonNullable<UUID> id = JsonNullable.undefined();

  public UUID getId() { return id.orElse(null); }
  public JsonNullable<UUID> idPresence() { return id; }
  public TicketMessage id(UUID value) { this.id = JsonNullable.of(value); return this; }

  @JsonProperty("in_reply_to")
  private JsonNullable<String> inReplyTo = JsonNullable.undefined();

  public String getInReplyTo() { return inReplyTo.orElse(null); }
  public JsonNullable<String> inReplyToPresence() { return inReplyTo; }
  public TicketMessage inReplyTo(String value) { this.inReplyTo = JsonNullable.of(value); return this; }

  @JsonProperty("message_id")
  private JsonNullable<String> messageId = JsonNullable.undefined();

  public String getMessageId() { return messageId.orElse(null); }
  public JsonNullable<String> messageIdPresence() { return messageId; }
  public TicketMessage messageId(String value) { this.messageId = JsonNullable.of(value); return this; }

  @JsonProperty("references")
  private JsonNullable<List<String>> references = JsonNullable.undefined();

  public List<String> getReferences() { return references.orElse(null); }
  public JsonNullable<List<String>> referencesPresence() { return references; }
  public TicketMessage references(List<String> value) { this.references = JsonNullable.of(value); return this; }

  @JsonProperty("spf_result")
  private JsonNullable<DnsRecordState> spfResult = JsonNullable.undefined();

  public DnsRecordState getSpfResult() { return spfResult.orElse(null); }
  public JsonNullable<DnsRecordState> spfResultPresence() { return spfResult; }
  public TicketMessage spfResult(DnsRecordState value) { this.spfResult = JsonNullable.of(value); return this; }

  @JsonProperty("ticket_id")
  private JsonNullable<UUID> ticketId = JsonNullable.undefined();

  public UUID getTicketId() { return ticketId.orElse(null); }
  public JsonNullable<UUID> ticketIdPresence() { return ticketId; }
  public TicketMessage ticketId(UUID value) { this.ticketId = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final TicketMessage value = new TicketMessage();
    public Builder attachments(List<Attachment> field) { value.attachments(field); return this; }
    public Builder authorPrincipalId(UUID field) { value.authorPrincipalId(field); return this; }
    public Builder bodyHtml(String field) { value.bodyHtml(field); return this; }
    public Builder bodyText(String field) { value.bodyText(field); return this; }
    public Builder createdAt(OffsetDateTime field) { value.createdAt(field); return this; }
    public Builder deliveryState(DeliveryStateEnum field) { value.deliveryState(field); return this; }
    public Builder direction(MessageDirection field) { value.direction(field); return this; }
    public Builder dkimResult(DnsRecordState field) { value.dkimResult(field); return this; }
    public Builder dmarcResult(DnsRecordState field) { value.dmarcResult(field); return this; }
    public Builder id(UUID field) { value.id(field); return this; }
    public Builder inReplyTo(String field) { value.inReplyTo(field); return this; }
    public Builder messageId(String field) { value.messageId(field); return this; }
    public Builder references(List<String> field) { value.references(field); return this; }
    public Builder spfResult(DnsRecordState field) { value.spfResult(field); return this; }
    public Builder ticketId(UUID field) { value.ticketId(field); return this; }
    public TicketMessage build() { return value; }
  }
}


