/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "mode", "time", "timezone", "weekday" })
@com.manyforge.sdk.ModelShape(required = { "mode", "time",  }, nonNullable = { "mode", "time", "timezone",  })
public class UntilWaitConfig {
@JsonDeserialize(using = ModeEnum.Deserializer.class)
public static final class ModeEnum {

  public static final ModeEnum UNTIL = new ModeEnum("until");

  private final String value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public ModeEnum(String value) { this.value = value; }
  @JsonValue public String getValue() { return value; }
  public static ModeEnum fromValue(String value) { return new ModeEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof ModeEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<ModeEnum> {
    @Override public ModeEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new ModeEnum(context.readValue(parser, String.class));
    }
  }
}

  @JsonProperty("mode")
  private JsonNullable<ModeEnum> mode = JsonNullable.undefined();

  public ModeEnum getMode() { return mode.orElse(null); }
  public JsonNullable<ModeEnum> modePresence() { return mode; }
  public UntilWaitConfig mode(ModeEnum value) { this.mode = JsonNullable.of(value); return this; }

  @JsonProperty("time")
  private JsonNullable<String> time = JsonNullable.undefined();

  public String getTime() { return time.orElse(null); }
  public JsonNullable<String> timePresence() { return time; }
  public UntilWaitConfig time(String value) { this.time = JsonNullable.of(value); return this; }

  @JsonProperty("timezone")
  private JsonNullable<String> timezone = JsonNullable.undefined();

  public String getTimezone() { return timezone.orElse(null); }
  public JsonNullable<String> timezonePresence() { return timezone; }
  public UntilWaitConfig timezone(String value) { this.timezone = JsonNullable.of(value); return this; }

  @JsonProperty("weekday")
  private JsonNullable<Integer> weekday = JsonNullable.undefined();

  public Integer getWeekday() { return weekday.orElse(null); }
  public JsonNullable<Integer> weekdayPresence() { return weekday; }
  public UntilWaitConfig weekday(Integer value) { this.weekday = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final UntilWaitConfig value = new UntilWaitConfig();
    public Builder mode(ModeEnum field) { value.mode(field); return this; }
    public Builder time(String field) { value.time(field); return this; }
    public Builder timezone(String field) { value.timezone(field); return this; }
    public Builder weekday(Integer field) { value.weekday(field); return this; }
    public UntilWaitConfig build() { return value; }
  }
}


