/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.*;
import java.io.IOException;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import com.manyforge.sdk.ModelJson;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;



@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
@JsonPropertyOrder({ "allowed_mcp_servers", "allowed_tools", "autonomy_mode", "enabled", "model", "monthly_budget_cents", "name", "retriage_on_reply", "system_prompt", "web_allowed_domains" })
@com.manyforge.sdk.ModelShape(required = {  }, nonNullable = {  })
public class UpdateAgentRequest {

  @JsonProperty("allowed_mcp_servers")
  private JsonNullable<List<UUID>> allowedMcpServers = JsonNullable.undefined();

  public List<UUID> getAllowedMcpServers() { return allowedMcpServers.orElse(null); }
  public JsonNullable<List<UUID>> allowedMcpServersPresence() { return allowedMcpServers; }
  public UpdateAgentRequest allowedMcpServers(List<UUID> value) { this.allowedMcpServers = JsonNullable.of(value); return this; }

  @JsonProperty("allowed_tools")
  private JsonNullable<List<String>> allowedTools = JsonNullable.undefined();

  public List<String> getAllowedTools() { return allowedTools.orElse(null); }
  public JsonNullable<List<String>> allowedToolsPresence() { return allowedTools; }
  public UpdateAgentRequest allowedTools(List<String> value) { this.allowedTools = JsonNullable.of(value); return this; }
@JsonDeserialize(using = AutonomyModeEnum.Deserializer.class)
public static final class AutonomyModeEnum {

  public static final AutonomyModeEnum NUMBER_1 = new AutonomyModeEnum(1);

  public static final AutonomyModeEnum NUMBER_2 = new AutonomyModeEnum(2);

  public static final AutonomyModeEnum NUMBER_3 = new AutonomyModeEnum(3);

  private final Integer value;
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public AutonomyModeEnum(Integer value) { this.value = value; }
  @JsonValue public Integer getValue() { return value; }
  public static AutonomyModeEnum fromValue(Integer value) { return new AutonomyModeEnum(value); }
  @Override public String toString() { return String.valueOf(value); }
  @Override public boolean equals(Object other) { return other instanceof AutonomyModeEnum e && Objects.equals(value, e.value); }
  @Override public int hashCode() { return Objects.hashCode(value); }
  public static final class Deserializer extends JsonDeserializer<AutonomyModeEnum> {
    @Override public AutonomyModeEnum deserialize(JsonParser parser, DeserializationContext context) throws IOException {
      return new AutonomyModeEnum(context.readValue(parser, Integer.class));
    }
  }
}

  @JsonProperty("autonomy_mode")
  private JsonNullable<AutonomyModeEnum> autonomyMode = JsonNullable.undefined();

  public AutonomyModeEnum getAutonomyMode() { return autonomyMode.orElse(null); }
  public JsonNullable<AutonomyModeEnum> autonomyModePresence() { return autonomyMode; }
  public UpdateAgentRequest autonomyMode(AutonomyModeEnum value) { this.autonomyMode = JsonNullable.of(value); return this; }

  @JsonProperty("enabled")
  private JsonNullable<Boolean> enabled = JsonNullable.undefined();

  public Boolean getEnabled() { return enabled.orElse(null); }
  public JsonNullable<Boolean> enabledPresence() { return enabled; }
  public UpdateAgentRequest enabled(Boolean value) { this.enabled = JsonNullable.of(value); return this; }

  @JsonProperty("model")
  private JsonNullable<String> model = JsonNullable.undefined();

  public String getModel() { return model.orElse(null); }
  public JsonNullable<String> modelPresence() { return model; }
  public UpdateAgentRequest model(String value) { this.model = JsonNullable.of(value); return this; }

  @JsonProperty("monthly_budget_cents")
  private JsonNullable<Integer> monthlyBudgetCents = JsonNullable.undefined();

  public Integer getMonthlyBudgetCents() { return monthlyBudgetCents.orElse(null); }
  public JsonNullable<Integer> monthlyBudgetCentsPresence() { return monthlyBudgetCents; }
  public UpdateAgentRequest monthlyBudgetCents(Integer value) { this.monthlyBudgetCents = JsonNullable.of(value); return this; }

  @JsonProperty("name")
  private JsonNullable<String> name = JsonNullable.undefined();

  public String getName() { return name.orElse(null); }
  public JsonNullable<String> namePresence() { return name; }
  public UpdateAgentRequest name(String value) { this.name = JsonNullable.of(value); return this; }

  @JsonProperty("retriage_on_reply")
  private JsonNullable<Boolean> retriageOnReply = JsonNullable.undefined();

  public Boolean getRetriageOnReply() { return retriageOnReply.orElse(null); }
  public JsonNullable<Boolean> retriageOnReplyPresence() { return retriageOnReply; }
  public UpdateAgentRequest retriageOnReply(Boolean value) { this.retriageOnReply = JsonNullable.of(value); return this; }

  @JsonProperty("system_prompt")
  private JsonNullable<String> systemPrompt = JsonNullable.undefined();

  public String getSystemPrompt() { return systemPrompt.orElse(null); }
  public JsonNullable<String> systemPromptPresence() { return systemPrompt; }
  public UpdateAgentRequest systemPrompt(String value) { this.systemPrompt = JsonNullable.of(value); return this; }

  @JsonProperty("web_allowed_domains")
  private JsonNullable<List<String>> webAllowedDomains = JsonNullable.undefined();

  public List<String> getWebAllowedDomains() { return webAllowedDomains.orElse(null); }
  public JsonNullable<List<String>> webAllowedDomainsPresence() { return webAllowedDomains; }
  public UpdateAgentRequest webAllowedDomains(List<String> value) { this.webAllowedDomains = JsonNullable.of(value); return this; }
  public static Builder builder() { return new Builder(); }
  public static final class Builder {
    private final UpdateAgentRequest value = new UpdateAgentRequest();
    public Builder allowedMcpServers(List<UUID> field) { value.allowedMcpServers(field); return this; }
    public Builder allowedTools(List<String> field) { value.allowedTools(field); return this; }
    public Builder autonomyMode(AutonomyModeEnum field) { value.autonomyMode(field); return this; }
    public Builder enabled(Boolean field) { value.enabled(field); return this; }
    public Builder model(String field) { value.model(field); return this; }
    public Builder monthlyBudgetCents(Integer field) { value.monthlyBudgetCents(field); return this; }
    public Builder name(String field) { value.name(field); return this; }
    public Builder retriageOnReply(Boolean field) { value.retriageOnReply(field); return this; }
    public Builder systemPrompt(String field) { value.systemPrompt(field); return this; }
    public Builder webAllowedDomains(List<String> field) { value.webAllowedDomains(field); return this; }
    public UpdateAgentRequest build() { return value; }
  }
}


