"""
    ManyForge API

    Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import date, datetime
from uuid import UUID
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import Field, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr, RootModel, field_validator, model_validator
from manyforge.model_support import Model, OpenEnum, JsonValue, UNSET, UnsetType

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from manyforge.models.ai_credential_properties_connection_status_enum import AICredentialPropertiesConnectionStatusEnum
from manyforge.models.ai_credential_properties_provider_enum import AICredentialPropertiesProviderEnum


class AICredential(Model):
    """AICredential wire model. Unspecified fields are never sent."""
    allow_private_base_url: StrictBool = Field(..., alias="allow_private_base_url")
    base_url: str = Field(..., alias="base_url")
    business_id: UUID = Field(..., alias="business_id")
    chatgpt_plan: str | UnsetType = Field(default=UNSET, alias="chatgpt_plan")
    connection_status: AICredentialPropertiesConnectionStatusEnum | UnsetType = Field(default=UNSET, alias="connection_status")
    created_at: datetime = Field(..., alias="created_at")
    default_model: str = Field(..., alias="default_model")
    id: UUID = Field(..., alias="id")
    max_concurrent_lanes: StrictInt = Field(..., alias="max_concurrent_lanes")
    oauth_access_expiry: datetime | UnsetType = Field(default=UNSET, alias="oauth_access_expiry")
    provider: AICredentialPropertiesProviderEnum = Field(..., alias="provider")
    updated_at: datetime = Field(..., alias="updated_at")



