"""
    ManyForge API

    Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import date, datetime
from uuid import UUID
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import Field, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr, RootModel, field_validator, model_validator
from manyforge.model_support import Model, OpenEnum, JsonValue, UNSET, UnsetType

from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List


class BusinessDeleteRequest(Model):
    """BusinessDeleteRequest wire model. Unspecified fields are never sent."""
    confirm: StrictBool = Field(..., alias="confirm")


    @field_validator("confirm")
    @classmethod
    def validate_confirm(cls, value: Any) -> Any:
        if isinstance(value, UnsetType):
            return value
        if value not in (True,):
            raise ValueError("Value is not permitted by the wire schema")
        return value



