"""
    ManyForge API

    Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import date, datetime
from uuid import UUID
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import Field, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr, RootModel, field_validator, model_validator
from manyforge.model_support import Model, OpenEnum, JsonValue, UNSET, UnsetType

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from manyforge.models.run_properties_status_enum import RunPropertiesStatusEnum
from manyforge.models.run_properties_trigger_enum import RunPropertiesTriggerEnum


class RunSummary(Model):
    """RunSummary wire model. Unspecified fields are never sent."""
    agent_id: UUID = Field(..., alias="agent_id")
    correlation_id: str = Field(..., alias="correlation_id")
    cost_cents: StrictInt = Field(..., alias="cost_cents")
    error: str | UnsetType = Field(default=UNSET, alias="error")
    id: UUID = Field(..., alias="id")
    status: RunPropertiesStatusEnum = Field(..., alias="status")
    tokens_in: StrictInt = Field(..., alias="tokens_in")
    tokens_out: StrictInt = Field(..., alias="tokens_out")
    trigger: RunPropertiesTriggerEnum = Field(..., alias="trigger")
    created_at: datetime = Field(..., alias="created_at")



