"""
    ManyForge API

    Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import date, datetime
from uuid import UUID
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import Field, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr, RootModel, field_validator, model_validator
from manyforge.model_support import Model, OpenEnum, JsonValue, UNSET, UnsetType

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from uuid import UUID
from manyforge.models.tenant_merge_count import TenantMergeCount
from manyforge.models.tenant_merge_finding import TenantMergeFinding
from manyforge.models.tenant_merge_table_metric import TenantMergeTableMetric


class TenantMergeManifest(Model):
    """TenantMergeManifest wire model. Unspecified fields are never sent."""
    actor_principal_id: UUID = Field(..., alias="actor_principal_id")
    affected_rows: StrictInt = Field(..., alias="affected_rows")
    completed_at: datetime = Field(..., alias="completed_at")
    correlation_id: UUID = Field(..., alias="correlation_id")
    created_at: datetime = Field(..., alias="created_at")
    destination_parent_id: UUID = Field(..., alias="destination_parent_id")
    destination_root_id: UUID = Field(..., alias="destination_root_id")
    estimated_bytes: StrictInt = Field(..., alias="estimated_bytes")
    inventory_version: StrictInt = Field(..., alias="inventory_version")
    module_counts: Dict[str, TenantMergeCount] = Field(..., alias="module_counts")
    operation_id: UUID = Field(..., alias="operation_id")
    preflight_generation: str = Field(..., alias="preflight_generation")
    reconciliation_hash: str = Field(..., alias="reconciliation_hash")
    reconciliation_version: StrictInt = Field(..., alias="reconciliation_version")
    resolutions: List[TenantMergeFinding] = Field(..., alias="resolutions")
    schema_hash: str = Field(..., alias="schema_hash")
    schema_version: StrictInt = Field(..., alias="schema_version")
    source_root_id: UUID = Field(..., alias="source_root_id")
    started_at: datetime = Field(..., alias="started_at")
    table_counts: Dict[str, int] = Field(..., alias="table_counts")
    table_metrics: Dict[str, TenantMergeTableMetric] = Field(..., alias="table_metrics")
    warnings: List[TenantMergeFinding] = Field(..., alias="warnings")



