"""
    ManyForge API

    Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import date, datetime
from uuid import UUID
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import Field, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr, RootModel, field_validator, model_validator
from manyforge.model_support import Model, OpenEnum, JsonValue, UNSET, UnsetType

from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from manyforge.models.duration_wait_config import DurationWaitConfig
from manyforge.models.until_wait_config import UntilWaitConfig

class WaitConfig(RootModel[Union[DurationWaitConfig, UntilWaitConfig, ]]):
    """Typed wire union; serialize its root, never a wrapper object."""
    @model_validator(mode="before")
    @classmethod
    def select_variant(cls, value: Any) -> Any:
        if not isinstance(value, dict):
            return value
        if value.get("mode") == "duration":
            return DurationWaitConfig.model_validate(value)
        if value.get("mode") == "until":
            return UntilWaitConfig.model_validate(value)
        return value



