// Generated resource tree. Do not edit.
import type { Transport } from './transport.js';
import { BusinessAccountingApi } from './apis/BusinessAccountingApi.js';
export * from './apis/BusinessAccountingApi.js';
import { BusinessAgentRunsApi } from './apis/BusinessAgentRunsApi.js';
export * from './apis/BusinessAgentRunsApi.js';
import { BusinessAgentsApi } from './apis/BusinessAgentsApi.js';
export * from './apis/BusinessAgentsApi.js';
import { BusinessAgentsModelsApi } from './apis/BusinessAgentsModelsApi.js';
export * from './apis/BusinessAgentsModelsApi.js';
import { BusinessAgentsProviderModelsApi } from './apis/BusinessAgentsProviderModelsApi.js';
export * from './apis/BusinessAgentsProviderModelsApi.js';
import { BusinessAgentsToolsApi } from './apis/BusinessAgentsToolsApi.js';
export * from './apis/BusinessAgentsToolsApi.js';
import { BusinessAiCredentialsApi } from './apis/BusinessAiCredentialsApi.js';
export * from './apis/BusinessAiCredentialsApi.js';
import { BusinessAiCredentialsCodexModelsApi } from './apis/BusinessAiCredentialsCodexModelsApi.js';
export * from './apis/BusinessAiCredentialsCodexModelsApi.js';
import { BusinessAiCredentialsCodexPkceApi } from './apis/BusinessAiCredentialsCodexPkceApi.js';
export * from './apis/BusinessAiCredentialsCodexPkceApi.js';
import { BusinessAnalyticsApi } from './apis/BusinessAnalyticsApi.js';
export * from './apis/BusinessAnalyticsApi.js';
import { BusinessAnalyticsPropertyRulesApi } from './apis/BusinessAnalyticsPropertyRulesApi.js';
export * from './apis/BusinessAnalyticsPropertyRulesApi.js';
import { BusinessApprovalsApi } from './apis/BusinessApprovalsApi.js';
export * from './apis/BusinessApprovalsApi.js';
import { BusinessAuditApi } from './apis/BusinessAuditApi.js';
export * from './apis/BusinessAuditApi.js';
import { BusinessAutomationsApi } from './apis/BusinessAutomationsApi.js';
export * from './apis/BusinessAutomationsApi.js';
import { BusinessAutomationsEnrollmentsApi } from './apis/BusinessAutomationsEnrollmentsApi.js';
export * from './apis/BusinessAutomationsEnrollmentsApi.js';
import { BusinessAutomationsStatsApi } from './apis/BusinessAutomationsStatsApi.js';
export * from './apis/BusinessAutomationsStatsApi.js';
import { BusinessAutomationsVersionsApi } from './apis/BusinessAutomationsVersionsApi.js';
export * from './apis/BusinessAutomationsVersionsApi.js';
import { BusinessAutomationsVersionsGraphApi } from './apis/BusinessAutomationsVersionsGraphApi.js';
export * from './apis/BusinessAutomationsVersionsGraphApi.js';
import { BusinessCodeReviewsApi } from './apis/BusinessCodeReviewsApi.js';
export * from './apis/BusinessCodeReviewsApi.js';
import { BusinessCompaniesApi } from './apis/BusinessCompaniesApi.js';
export * from './apis/BusinessCompaniesApi.js';
import { BusinessConnectorsApi } from './apis/BusinessConnectorsApi.js';
export * from './apis/BusinessConnectorsApi.js';
import { BusinessConnectorsCredentialsApi } from './apis/BusinessConnectorsCredentialsApi.js';
export * from './apis/BusinessConnectorsCredentialsApi.js';
import { BusinessConnectorsFailedOpsApi } from './apis/BusinessConnectorsFailedOpsApi.js';
export * from './apis/BusinessConnectorsFailedOpsApi.js';
import { BusinessContactsApi } from './apis/BusinessContactsApi.js';
export * from './apis/BusinessContactsApi.js';
import { BusinessContactsActivityApi } from './apis/BusinessContactsActivityApi.js';
export * from './apis/BusinessContactsActivityApi.js';
import { BusinessFeedbackBoardsApi } from './apis/BusinessFeedbackBoardsApi.js';
export * from './apis/BusinessFeedbackBoardsApi.js';
import { BusinessFeedbackKeysApi } from './apis/BusinessFeedbackKeysApi.js';
export * from './apis/BusinessFeedbackKeysApi.js';
import { BusinessFeedbackPostsApi } from './apis/BusinessFeedbackPostsApi.js';
export * from './apis/BusinessFeedbackPostsApi.js';
import { BusinessInboxEmailDomainsApi } from './apis/BusinessInboxEmailDomainsApi.js';
export * from './apis/BusinessInboxEmailDomainsApi.js';
import { BusinessInboxInboundAddressesApi } from './apis/BusinessInboxInboundAddressesApi.js';
export * from './apis/BusinessInboxInboundAddressesApi.js';
import { BusinessInvitationsApi } from './apis/BusinessInvitationsApi.js';
export * from './apis/BusinessInvitationsApi.js';
import { BusinessMailingCampaignsApi } from './apis/BusinessMailingCampaignsApi.js';
export * from './apis/BusinessMailingCampaignsApi.js';
import { BusinessMailingCampaignsStatsApi } from './apis/BusinessMailingCampaignsStatsApi.js';
export * from './apis/BusinessMailingCampaignsStatsApi.js';
import { BusinessMailingDeliveriesApi } from './apis/BusinessMailingDeliveriesApi.js';
export * from './apis/BusinessMailingDeliveriesApi.js';
import { BusinessMailingEventsApi } from './apis/BusinessMailingEventsApi.js';
export * from './apis/BusinessMailingEventsApi.js';
import { BusinessMailingKeysApi } from './apis/BusinessMailingKeysApi.js';
export * from './apis/BusinessMailingKeysApi.js';
import { BusinessMailingListsApi } from './apis/BusinessMailingListsApi.js';
export * from './apis/BusinessMailingListsApi.js';
import { BusinessMailingSendingProfileApi } from './apis/BusinessMailingSendingProfileApi.js';
export * from './apis/BusinessMailingSendingProfileApi.js';
import { BusinessMailingSubscribersApi } from './apis/BusinessMailingSubscribersApi.js';
export * from './apis/BusinessMailingSubscribersApi.js';
import { BusinessMailingSuppressionsApi } from './apis/BusinessMailingSuppressionsApi.js';
export * from './apis/BusinessMailingSuppressionsApi.js';
import { BusinessMailingTemplatesApi } from './apis/BusinessMailingTemplatesApi.js';
export * from './apis/BusinessMailingTemplatesApi.js';
import { BusinessMcpServersApi } from './apis/BusinessMcpServersApi.js';
export * from './apis/BusinessMcpServersApi.js';
import { BusinessMcpServersToolPoliciesApi } from './apis/BusinessMcpServersToolPoliciesApi.js';
export * from './apis/BusinessMcpServersToolPoliciesApi.js';
import { BusinessMcpServersToolsApi } from './apis/BusinessMcpServersToolsApi.js';
export * from './apis/BusinessMcpServersToolsApi.js';
import { BusinessMembersApi } from './apis/BusinessMembersApi.js';
export * from './apis/BusinessMembersApi.js';
import { BusinessRepoConnectorsApi } from './apis/BusinessRepoConnectorsApi.js';
export * from './apis/BusinessRepoConnectorsApi.js';
import { BusinessRepoConnectorsDimensionOverridesApi } from './apis/BusinessRepoConnectorsDimensionOverridesApi.js';
export * from './apis/BusinessRepoConnectorsDimensionOverridesApi.js';
import { BusinessRequestersApi } from './apis/BusinessRequestersApi.js';
export * from './apis/BusinessRequestersApi.js';
import { BusinessReviewConfigApi } from './apis/BusinessReviewConfigApi.js';
export * from './apis/BusinessReviewConfigApi.js';
import { BusinessReviewDimensionsApi } from './apis/BusinessReviewDimensionsApi.js';
export * from './apis/BusinessReviewDimensionsApi.js';
import { BusinessRolesApi } from './apis/BusinessRolesApi.js';
export * from './apis/BusinessRolesApi.js';
import { BusinessTelemetryClientsApi } from './apis/BusinessTelemetryClientsApi.js';
export * from './apis/BusinessTelemetryClientsApi.js';
import { BusinessTelemetryClientsAllowedOriginsApi } from './apis/BusinessTelemetryClientsAllowedOriginsApi.js';
export * from './apis/BusinessTelemetryClientsAllowedOriginsApi.js';
import { BusinessTelemetryClientsMoveTargetsApi } from './apis/BusinessTelemetryClientsMoveTargetsApi.js';
export * from './apis/BusinessTelemetryClientsMoveTargetsApi.js';
import { BusinessTicketsApi } from './apis/BusinessTicketsApi.js';
export * from './apis/BusinessTicketsApi.js';
import { BusinessTicketsAssignableMembersApi } from './apis/BusinessTicketsAssignableMembersApi.js';
export * from './apis/BusinessTicketsAssignableMembersApi.js';
import { BusinessTicketsMessagesApi } from './apis/BusinessTicketsMessagesApi.js';
export * from './apis/BusinessTicketsMessagesApi.js';

export type BusinessResources = { readonly accounting: Readonly<BusinessAccountingApi>; readonly agentRuns: Readonly<BusinessAgentRunsApi>; readonly agents: Readonly<BusinessAgentsApi> & { readonly models: Readonly<BusinessAgentsModelsApi>; readonly providerModels: Readonly<BusinessAgentsProviderModelsApi>; readonly tools: Readonly<BusinessAgentsToolsApi> }; readonly aiCredentials: Readonly<BusinessAiCredentialsApi> & { readonly codex: { readonly models: Readonly<BusinessAiCredentialsCodexModelsApi>; readonly pkce: Readonly<BusinessAiCredentialsCodexPkceApi> } }; readonly analytics: Readonly<BusinessAnalyticsApi> & { readonly propertyRules: Readonly<BusinessAnalyticsPropertyRulesApi> }; readonly approvals: Readonly<BusinessApprovalsApi>; readonly audit: Readonly<BusinessAuditApi>; readonly automations: Readonly<BusinessAutomationsApi> & { readonly enrollments: Readonly<BusinessAutomationsEnrollmentsApi>; readonly stats: Readonly<BusinessAutomationsStatsApi>; readonly versions: Readonly<BusinessAutomationsVersionsApi> & { readonly graph: Readonly<BusinessAutomationsVersionsGraphApi> } }; readonly codeReviews: Readonly<BusinessCodeReviewsApi>; readonly companies: Readonly<BusinessCompaniesApi>; readonly connectors: Readonly<BusinessConnectorsApi> & { readonly credentials: Readonly<BusinessConnectorsCredentialsApi>; readonly failedOps: Readonly<BusinessConnectorsFailedOpsApi> }; readonly contacts: Readonly<BusinessContactsApi> & { readonly activity: Readonly<BusinessContactsActivityApi> }; readonly feedback: { readonly boards: Readonly<BusinessFeedbackBoardsApi>; readonly keys: Readonly<BusinessFeedbackKeysApi>; readonly posts: Readonly<BusinessFeedbackPostsApi> }; readonly inbox: { readonly emailDomains: Readonly<BusinessInboxEmailDomainsApi>; readonly inboundAddresses: Readonly<BusinessInboxInboundAddressesApi> }; readonly invitations: Readonly<BusinessInvitationsApi>; readonly mailing: { readonly campaigns: Readonly<BusinessMailingCampaignsApi> & { readonly stats: Readonly<BusinessMailingCampaignsStatsApi> }; readonly deliveries: Readonly<BusinessMailingDeliveriesApi>; readonly events: Readonly<BusinessMailingEventsApi>; readonly keys: Readonly<BusinessMailingKeysApi>; readonly lists: Readonly<BusinessMailingListsApi>; readonly sendingProfile: Readonly<BusinessMailingSendingProfileApi>; readonly subscribers: Readonly<BusinessMailingSubscribersApi>; readonly suppressions: Readonly<BusinessMailingSuppressionsApi>; readonly templates: Readonly<BusinessMailingTemplatesApi> }; readonly mcpServers: Readonly<BusinessMcpServersApi> & { readonly toolPolicies: Readonly<BusinessMcpServersToolPoliciesApi>; readonly tools: Readonly<BusinessMcpServersToolsApi> }; readonly members: Readonly<BusinessMembersApi>; readonly repoConnectors: Readonly<BusinessRepoConnectorsApi> & { readonly dimensionOverrides: Readonly<BusinessRepoConnectorsDimensionOverridesApi> }; readonly requesters: Readonly<BusinessRequestersApi>; readonly reviewConfig: Readonly<BusinessReviewConfigApi>; readonly reviewDimensions: Readonly<BusinessReviewDimensionsApi>; readonly roles: Readonly<BusinessRolesApi>; readonly telemetry: { readonly clients: Readonly<BusinessTelemetryClientsApi> & { readonly allowedOrigins: Readonly<BusinessTelemetryClientsAllowedOriginsApi>; readonly moveTargets: Readonly<BusinessTelemetryClientsMoveTargetsApi> } }; readonly tickets: Readonly<BusinessTicketsApi> & { readonly assignableMembers: Readonly<BusinessTicketsAssignableMembersApi>; readonly messages: Readonly<BusinessTicketsMessagesApi> } };

export function createBusinessResources(transport: Transport, businessId: string): BusinessResources {
    if (!businessId) throw new TypeError('A nonempty scope identifier is required');
    const scope = Object.freeze({ id: businessId });
    return Object.freeze({ accounting: Object.freeze(new BusinessAccountingApi(transport, scope)), agentRuns: Object.freeze(new BusinessAgentRunsApi(transport, scope)), agents: Object.freeze(Object.assign(new BusinessAgentsApi(transport, scope), { models: Object.freeze(new BusinessAgentsModelsApi(transport, scope)), providerModels: Object.freeze(new BusinessAgentsProviderModelsApi(transport, scope)), tools: Object.freeze(new BusinessAgentsToolsApi(transport, scope)) })), aiCredentials: Object.freeze(Object.assign(new BusinessAiCredentialsApi(transport, scope), { codex: Object.freeze({ models: Object.freeze(new BusinessAiCredentialsCodexModelsApi(transport, scope)), pkce: Object.freeze(new BusinessAiCredentialsCodexPkceApi(transport, scope)) }) })), analytics: Object.freeze(Object.assign(new BusinessAnalyticsApi(transport, scope), { propertyRules: Object.freeze(new BusinessAnalyticsPropertyRulesApi(transport, scope)) })), approvals: Object.freeze(new BusinessApprovalsApi(transport, scope)), audit: Object.freeze(new BusinessAuditApi(transport, scope)), automations: Object.freeze(Object.assign(new BusinessAutomationsApi(transport, scope), { enrollments: Object.freeze(new BusinessAutomationsEnrollmentsApi(transport, scope)), stats: Object.freeze(new BusinessAutomationsStatsApi(transport, scope)), versions: Object.freeze(Object.assign(new BusinessAutomationsVersionsApi(transport, scope), { graph: Object.freeze(new BusinessAutomationsVersionsGraphApi(transport, scope)) })) })), codeReviews: Object.freeze(new BusinessCodeReviewsApi(transport, scope)), companies: Object.freeze(new BusinessCompaniesApi(transport, scope)), connectors: Object.freeze(Object.assign(new BusinessConnectorsApi(transport, scope), { credentials: Object.freeze(new BusinessConnectorsCredentialsApi(transport, scope)), failedOps: Object.freeze(new BusinessConnectorsFailedOpsApi(transport, scope)) })), contacts: Object.freeze(Object.assign(new BusinessContactsApi(transport, scope), { activity: Object.freeze(new BusinessContactsActivityApi(transport, scope)) })), feedback: Object.freeze({ boards: Object.freeze(new BusinessFeedbackBoardsApi(transport, scope)), keys: Object.freeze(new BusinessFeedbackKeysApi(transport, scope)), posts: Object.freeze(new BusinessFeedbackPostsApi(transport, scope)) }), inbox: Object.freeze({ emailDomains: Object.freeze(new BusinessInboxEmailDomainsApi(transport, scope)), inboundAddresses: Object.freeze(new BusinessInboxInboundAddressesApi(transport, scope)) }), invitations: Object.freeze(new BusinessInvitationsApi(transport, scope)), mailing: Object.freeze({ campaigns: Object.freeze(Object.assign(new BusinessMailingCampaignsApi(transport, scope), { stats: Object.freeze(new BusinessMailingCampaignsStatsApi(transport, scope)) })), deliveries: Object.freeze(new BusinessMailingDeliveriesApi(transport, scope)), events: Object.freeze(new BusinessMailingEventsApi(transport, scope)), keys: Object.freeze(new BusinessMailingKeysApi(transport, scope)), lists: Object.freeze(new BusinessMailingListsApi(transport, scope)), sendingProfile: Object.freeze(new BusinessMailingSendingProfileApi(transport, scope)), subscribers: Object.freeze(new BusinessMailingSubscribersApi(transport, scope)), suppressions: Object.freeze(new BusinessMailingSuppressionsApi(transport, scope)), templates: Object.freeze(new BusinessMailingTemplatesApi(transport, scope)) }), mcpServers: Object.freeze(Object.assign(new BusinessMcpServersApi(transport, scope), { toolPolicies: Object.freeze(new BusinessMcpServersToolPoliciesApi(transport, scope)), tools: Object.freeze(new BusinessMcpServersToolsApi(transport, scope)) })), members: Object.freeze(new BusinessMembersApi(transport, scope)), repoConnectors: Object.freeze(Object.assign(new BusinessRepoConnectorsApi(transport, scope), { dimensionOverrides: Object.freeze(new BusinessRepoConnectorsDimensionOverridesApi(transport, scope)) })), requesters: Object.freeze(new BusinessRequestersApi(transport, scope)), reviewConfig: Object.freeze(new BusinessReviewConfigApi(transport, scope)), reviewDimensions: Object.freeze(new BusinessReviewDimensionsApi(transport, scope)), roles: Object.freeze(new BusinessRolesApi(transport, scope)), telemetry: Object.freeze({ clients: Object.freeze(Object.assign(new BusinessTelemetryClientsApi(transport, scope), { allowedOrigins: Object.freeze(new BusinessTelemetryClientsAllowedOriginsApi(transport, scope)), moveTargets: Object.freeze(new BusinessTelemetryClientsMoveTargetsApi(transport, scope)) })) }), tickets: Object.freeze(Object.assign(new BusinessTicketsApi(transport, scope), { assignableMembers: Object.freeze(new BusinessTicketsAssignableMembersApi(transport, scope)), messages: Object.freeze(new BusinessTicketsMessagesApi(transport, scope)) })) });
}
