/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.resources;

import com.manyforge.sdk.*;
import com.manyforge.sdk.models.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.io.InputStream;
import java.time.*;
import java.math.BigDecimal;
import com.manyforge.sdk.models.AutomationEnrollmentInput;
import com.manyforge.sdk.models.Enrollment;
import com.manyforge.sdk.models.EnrollmentDetail;
import com.manyforge.sdk.models.EnrollmentPage;
import com.manyforge.sdk.models.Error;
import java.util.UUID;

public class BusinessAutomationsEnrollmentsResource {
  protected final Transport transport;
  protected final String binding;
  public BusinessAutomationsEnrollmentsResource(Transport transport, String binding) {
    this.transport = Objects.requireNonNull(transport);
    this.binding = binding;
  }

  public static final class BusinessAutomationsEnrollmentsCreateParams {

    private final UUID aid;

    private final AutomationEnrollmentInput automationEnrollmentInput;

    private BusinessAutomationsEnrollmentsCreateParams(Builder builder) {

      this.aid = builder.aid;

      this.automationEnrollmentInput = builder.automationEnrollmentInput;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.aid = aid;

      builder.automationEnrollmentInput = automationEnrollmentInput;

      return builder;
    }
    public static final class Builder {

      private UUID aid;
      public Builder aid(UUID value) { this.aid = value; return this; }

      private AutomationEnrollmentInput automationEnrollmentInput;
      public Builder automationEnrollmentInput(AutomationEnrollmentInput value) { this.automationEnrollmentInput = value; return this; }

      public BusinessAutomationsEnrollmentsCreateParams build() { return new BusinessAutomationsEnrollmentsCreateParams(this); }
    }
  }
  private Request<Enrollment> createRequest(BusinessAutomationsEnrollmentsCreateParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.aid, "aid");

    parameters.add(new Request.Parameter("aid", "path", params.aid, ""));

    Objects.requireNonNull(params.automationEnrollmentInput, "automationEnrollmentInput");

    return new Request<>("POST", "/api/v1/businesses/{id}/mailing/automations/{aid}/enrollments", parameters, params.automationEnrollmentInput, "application/json", true, "management", false, null, new TypeReference<Enrollment>() {});
  }
  public Enrollment create(BusinessAutomationsEnrollmentsCreateParams params) { return create(params, RequestOptions.DEFAULT); }
  public Enrollment create(BusinessAutomationsEnrollmentsCreateParams params, RequestOptions options) { return transport.send(createRequest(params), options); }
  public CompletableFuture<Enrollment> createAsync(BusinessAutomationsEnrollmentsCreateParams params) { return createAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<Enrollment> createAsync(BusinessAutomationsEnrollmentsCreateParams params, RequestOptions options) { return transport.sendAsync(createRequest(params), options); }

  public static final class BusinessAutomationsEnrollmentsExitParams {

    private final UUID aid;

    private final UUID eid;

    private BusinessAutomationsEnrollmentsExitParams(Builder builder) {

      this.aid = builder.aid;

      this.eid = builder.eid;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.aid = aid;

      builder.eid = eid;

      return builder;
    }
    public static final class Builder {

      private UUID aid;
      public Builder aid(UUID value) { this.aid = value; return this; }

      private UUID eid;
      public Builder eid(UUID value) { this.eid = value; return this; }

      public BusinessAutomationsEnrollmentsExitParams build() { return new BusinessAutomationsEnrollmentsExitParams(this); }
    }
  }
  private Request<Enrollment> exitRequest(BusinessAutomationsEnrollmentsExitParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.aid, "aid");

    parameters.add(new Request.Parameter("aid", "path", params.aid, ""));

    Objects.requireNonNull(params.eid, "eid");

    parameters.add(new Request.Parameter("eid", "path", params.eid, ""));
    return new Request<>("POST", "/api/v1/businesses/{id}/mailing/automations/{aid}/enrollments/{eid}/exit", parameters, null, "", true, "management", false, null, new TypeReference<Enrollment>() {});
  }
  public Enrollment exit(BusinessAutomationsEnrollmentsExitParams params) { return exit(params, RequestOptions.DEFAULT); }
  public Enrollment exit(BusinessAutomationsEnrollmentsExitParams params, RequestOptions options) { return transport.send(exitRequest(params), options); }
  public CompletableFuture<Enrollment> exitAsync(BusinessAutomationsEnrollmentsExitParams params) { return exitAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<Enrollment> exitAsync(BusinessAutomationsEnrollmentsExitParams params, RequestOptions options) { return transport.sendAsync(exitRequest(params), options); }

  public static final class BusinessAutomationsEnrollmentsGetParams {

    private final UUID aid;

    private final UUID eid;

    private BusinessAutomationsEnrollmentsGetParams(Builder builder) {

      this.aid = builder.aid;

      this.eid = builder.eid;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.aid = aid;

      builder.eid = eid;

      return builder;
    }
    public static final class Builder {

      private UUID aid;
      public Builder aid(UUID value) { this.aid = value; return this; }

      private UUID eid;
      public Builder eid(UUID value) { this.eid = value; return this; }

      public BusinessAutomationsEnrollmentsGetParams build() { return new BusinessAutomationsEnrollmentsGetParams(this); }
    }
  }
  private Request<EnrollmentDetail> getRequest(BusinessAutomationsEnrollmentsGetParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.aid, "aid");

    parameters.add(new Request.Parameter("aid", "path", params.aid, ""));

    Objects.requireNonNull(params.eid, "eid");

    parameters.add(new Request.Parameter("eid", "path", params.eid, ""));
    return new Request<>("GET", "/api/v1/businesses/{id}/mailing/automations/{aid}/enrollments/{eid}", parameters, null, "", true, "management", false, null, new TypeReference<EnrollmentDetail>() {});
  }
  public EnrollmentDetail get(BusinessAutomationsEnrollmentsGetParams params) { return get(params, RequestOptions.DEFAULT); }
  public EnrollmentDetail get(BusinessAutomationsEnrollmentsGetParams params, RequestOptions options) { return transport.send(getRequest(params), options); }
  public CompletableFuture<EnrollmentDetail> getAsync(BusinessAutomationsEnrollmentsGetParams params) { return getAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<EnrollmentDetail> getAsync(BusinessAutomationsEnrollmentsGetParams params, RequestOptions options) { return transport.sendAsync(getRequest(params), options); }

  public static final class BusinessAutomationsEnrollmentsListParams {

    private final UUID aid;

    private final String status;

    private final String nodeId;

    private final String cursor;

    private final Integer limit;

    private BusinessAutomationsEnrollmentsListParams(Builder builder) {

      this.aid = builder.aid;

      this.status = builder.status;

      this.nodeId = builder.nodeId;

      this.cursor = builder.cursor;

      this.limit = builder.limit;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.aid = aid;

      builder.status = status;

      builder.nodeId = nodeId;

      builder.cursor = cursor;

      builder.limit = limit;

      return builder;
    }
    public static final class Builder {

      private UUID aid;
      public Builder aid(UUID value) { this.aid = value; return this; }

      private String status;
      public Builder status(String value) { this.status = value; return this; }

      private String nodeId;
      public Builder nodeId(String value) { this.nodeId = value; return this; }

      private String cursor;
      public Builder cursor(String value) { this.cursor = value; return this; }

      private Integer limit;
      public Builder limit(Integer value) { this.limit = value; return this; }

      public BusinessAutomationsEnrollmentsListParams build() { return new BusinessAutomationsEnrollmentsListParams(this); }
    }
  }
  private Request<EnrollmentPage> listRequest(BusinessAutomationsEnrollmentsListParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.aid, "aid");

    parameters.add(new Request.Parameter("aid", "path", params.aid, ""));

    parameters.add(new Request.Parameter("status", "query", params.status, ""));

    parameters.add(new Request.Parameter("node_id", "query", params.nodeId, ""));

    parameters.add(new Request.Parameter("cursor", "query", params.cursor, ""));

    parameters.add(new Request.Parameter("limit", "query", params.limit, ""));
    return new Request<>("GET", "/api/v1/businesses/{id}/mailing/automations/{aid}/enrollments", parameters, null, "", true, "management", false, null, new TypeReference<EnrollmentPage>() {});
  }
  public EnrollmentPage list(BusinessAutomationsEnrollmentsListParams params) { return list(params, RequestOptions.DEFAULT); }
  public EnrollmentPage list(BusinessAutomationsEnrollmentsListParams params, RequestOptions options) { return transport.send(listRequest(params), options); }
  public CompletableFuture<EnrollmentPage> listAsync(BusinessAutomationsEnrollmentsListParams params) { return listAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<EnrollmentPage> listAsync(BusinessAutomationsEnrollmentsListParams params, RequestOptions options) { return transport.sendAsync(listRequest(params), options); }
  public Iterable<Enrollment> iter(BusinessAutomationsEnrollmentsListParams params) { return iter(params, RequestOptions.DEFAULT); }
  public Iterable<Enrollment> iter(BusinessAutomationsEnrollmentsListParams params, RequestOptions options) {
    return Pages.iterate(params.cursor, cursor -> list(params.toBuilder().cursor(cursor).build(), options), page -> page.getItems(), page -> page.getNextCursor());
  }

}
