/*
 * ManyForge API
 * Current implemented ManyForge application API. Configure an explicit instance-root URL. Management uses bearer access JWTs; public keys and server signatures have separate capabilities. Optional modules remain documented when disabled; their unavailable routes return real HTTP errors. Errors may be non-JSON at an intermediary; empty 202/204 responses contain no model. No SSE interface is implemented.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.manyforge.sdk.resources;

import com.manyforge.sdk.*;
import com.manyforge.sdk.models.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.io.InputStream;
import java.time.*;
import java.math.BigDecimal;
import com.manyforge.sdk.models.Connector;
import com.manyforge.sdk.models.ConnectorList;
import com.manyforge.sdk.models.ConnectorSyncAccepted;
import com.manyforge.sdk.models.CreateConnector;
import com.manyforge.sdk.models.Error;
import com.manyforge.sdk.models.TestResult;
import java.util.UUID;
import com.manyforge.sdk.models.UpdateConnector;

public class BusinessConnectorsResource {
  protected final Transport transport;
  protected final String binding;
  public BusinessConnectorsResource(Transport transport, String binding) {
    this.transport = Objects.requireNonNull(transport);
    this.binding = binding;
  }

  public static final class BusinessConnectorsSyncParams {

    private final UUID cid;

    private BusinessConnectorsSyncParams(Builder builder) {

      this.cid = builder.cid;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.cid = cid;

      return builder;
    }
    public static final class Builder {

      private UUID cid;
      public Builder cid(UUID value) { this.cid = value; return this; }

      public BusinessConnectorsSyncParams build() { return new BusinessConnectorsSyncParams(this); }
    }
  }
  private Request<ConnectorSyncAccepted> syncRequest(BusinessConnectorsSyncParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.cid, "cid");

    parameters.add(new Request.Parameter("cid", "path", params.cid, ""));
    return new Request<>("POST", "/api/v1/businesses/{id}/connectors/{cid}/sync", parameters, null, "", true, "management", false, null, new TypeReference<ConnectorSyncAccepted>() {});
  }
  public ConnectorSyncAccepted sync(BusinessConnectorsSyncParams params) { return sync(params, RequestOptions.DEFAULT); }
  public ConnectorSyncAccepted sync(BusinessConnectorsSyncParams params, RequestOptions options) { return transport.send(syncRequest(params), options); }
  public CompletableFuture<ConnectorSyncAccepted> syncAsync(BusinessConnectorsSyncParams params) { return syncAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<ConnectorSyncAccepted> syncAsync(BusinessConnectorsSyncParams params, RequestOptions options) { return transport.sendAsync(syncRequest(params), options); }

  public static final class BusinessConnectorsCreateParams {

    private final CreateConnector createConnector;

    private BusinessConnectorsCreateParams(Builder builder) {

      this.createConnector = builder.createConnector;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.createConnector = createConnector;

      return builder;
    }
    public static final class Builder {

      private CreateConnector createConnector;
      public Builder createConnector(CreateConnector value) { this.createConnector = value; return this; }

      public BusinessConnectorsCreateParams build() { return new BusinessConnectorsCreateParams(this); }
    }
  }
  private Request<Connector> createRequest(BusinessConnectorsCreateParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.createConnector, "createConnector");

    return new Request<>("POST", "/api/v1/businesses/{id}/connectors", parameters, params.createConnector, "application/json", true, "management", false, null, new TypeReference<Connector>() {});
  }
  public Connector create(BusinessConnectorsCreateParams params) { return create(params, RequestOptions.DEFAULT); }
  public Connector create(BusinessConnectorsCreateParams params, RequestOptions options) { return transport.send(createRequest(params), options); }
  public CompletableFuture<Connector> createAsync(BusinessConnectorsCreateParams params) { return createAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<Connector> createAsync(BusinessConnectorsCreateParams params, RequestOptions options) { return transport.sendAsync(createRequest(params), options); }

  public static final class BusinessConnectorsDeleteParams {

    private final UUID cid;

    private BusinessConnectorsDeleteParams(Builder builder) {

      this.cid = builder.cid;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.cid = cid;

      return builder;
    }
    public static final class Builder {

      private UUID cid;
      public Builder cid(UUID value) { this.cid = value; return this; }

      public BusinessConnectorsDeleteParams build() { return new BusinessConnectorsDeleteParams(this); }
    }
  }
  private Request<Void> deleteRequest(BusinessConnectorsDeleteParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.cid, "cid");

    parameters.add(new Request.Parameter("cid", "path", params.cid, ""));
    return new Request<>("DELETE", "/api/v1/businesses/{id}/connectors/{cid}", parameters, null, "", true, "management", false, null, new TypeReference<Void>() {});
  }
  public Void delete(BusinessConnectorsDeleteParams params) { return delete(params, RequestOptions.DEFAULT); }
  public Void delete(BusinessConnectorsDeleteParams params, RequestOptions options) { return transport.send(deleteRequest(params), options); }
  public CompletableFuture<Void> deleteAsync(BusinessConnectorsDeleteParams params) { return deleteAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<Void> deleteAsync(BusinessConnectorsDeleteParams params, RequestOptions options) { return transport.sendAsync(deleteRequest(params), options); }

  public static final class BusinessConnectorsGetParams {

    private final UUID cid;

    private BusinessConnectorsGetParams(Builder builder) {

      this.cid = builder.cid;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.cid = cid;

      return builder;
    }
    public static final class Builder {

      private UUID cid;
      public Builder cid(UUID value) { this.cid = value; return this; }

      public BusinessConnectorsGetParams build() { return new BusinessConnectorsGetParams(this); }
    }
  }
  private Request<Connector> getRequest(BusinessConnectorsGetParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.cid, "cid");

    parameters.add(new Request.Parameter("cid", "path", params.cid, ""));
    return new Request<>("GET", "/api/v1/businesses/{id}/connectors/{cid}", parameters, null, "", true, "management", false, null, new TypeReference<Connector>() {});
  }
  public Connector get(BusinessConnectorsGetParams params) { return get(params, RequestOptions.DEFAULT); }
  public Connector get(BusinessConnectorsGetParams params, RequestOptions options) { return transport.send(getRequest(params), options); }
  public CompletableFuture<Connector> getAsync(BusinessConnectorsGetParams params) { return getAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<Connector> getAsync(BusinessConnectorsGetParams params, RequestOptions options) { return transport.sendAsync(getRequest(params), options); }

  public static final class BusinessConnectorsListParams {

    private BusinessConnectorsListParams(Builder builder) {

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      return builder;
    }
    public static final class Builder {

      public BusinessConnectorsListParams build() { return new BusinessConnectorsListParams(this); }
    }
  }
  private Request<ConnectorList> listRequest(BusinessConnectorsListParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));
    return new Request<>("GET", "/api/v1/businesses/{id}/connectors", parameters, null, "", true, "management", false, null, new TypeReference<ConnectorList>() {});
  }
  public ConnectorList list(BusinessConnectorsListParams params) { return list(params, RequestOptions.DEFAULT); }
  public ConnectorList list(BusinessConnectorsListParams params, RequestOptions options) { return transport.send(listRequest(params), options); }
  public CompletableFuture<ConnectorList> listAsync(BusinessConnectorsListParams params) { return listAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<ConnectorList> listAsync(BusinessConnectorsListParams params, RequestOptions options) { return transport.sendAsync(listRequest(params), options); }
  public ConnectorList list() { return list(BusinessConnectorsListParams.builder().build()); }
  public CompletableFuture<ConnectorList> listAsync() { return listAsync(BusinessConnectorsListParams.builder().build()); }

  public static final class BusinessConnectorsTestParams {

    private final UUID cid;

    private BusinessConnectorsTestParams(Builder builder) {

      this.cid = builder.cid;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.cid = cid;

      return builder;
    }
    public static final class Builder {

      private UUID cid;
      public Builder cid(UUID value) { this.cid = value; return this; }

      public BusinessConnectorsTestParams build() { return new BusinessConnectorsTestParams(this); }
    }
  }
  private Request<TestResult> testRequest(BusinessConnectorsTestParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.cid, "cid");

    parameters.add(new Request.Parameter("cid", "path", params.cid, ""));
    return new Request<>("POST", "/api/v1/businesses/{id}/connectors/{cid}/test", parameters, null, "", true, "management", false, null, new TypeReference<TestResult>() {});
  }
  public TestResult test(BusinessConnectorsTestParams params) { return test(params, RequestOptions.DEFAULT); }
  public TestResult test(BusinessConnectorsTestParams params, RequestOptions options) { return transport.send(testRequest(params), options); }
  public CompletableFuture<TestResult> testAsync(BusinessConnectorsTestParams params) { return testAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<TestResult> testAsync(BusinessConnectorsTestParams params, RequestOptions options) { return transport.sendAsync(testRequest(params), options); }

  public static final class BusinessConnectorsUpdateParams {

    private final UUID cid;

    private final UpdateConnector updateConnector;

    private BusinessConnectorsUpdateParams(Builder builder) {

      this.cid = builder.cid;

      this.updateConnector = builder.updateConnector;

    }
    public static Builder builder() { return new Builder(); }
    public Builder toBuilder() {
      Builder builder = new Builder();

      builder.cid = cid;

      builder.updateConnector = updateConnector;

      return builder;
    }
    public static final class Builder {

      private UUID cid;
      public Builder cid(UUID value) { this.cid = value; return this; }

      private UpdateConnector updateConnector;
      public Builder updateConnector(UpdateConnector value) { this.updateConnector = value; return this; }

      public BusinessConnectorsUpdateParams build() { return new BusinessConnectorsUpdateParams(this); }
    }
  }
  private Request<Connector> updateRequest(BusinessConnectorsUpdateParams params) {
    Objects.requireNonNull(params, "params");
    List<Request.Parameter> parameters = new ArrayList<>();

    parameters.add(new Request.Parameter("id", "path", Objects.requireNonNull(binding, "resource binding"), ""));

    Objects.requireNonNull(params.cid, "cid");

    parameters.add(new Request.Parameter("cid", "path", params.cid, ""));

    Objects.requireNonNull(params.updateConnector, "updateConnector");

    return new Request<>("PATCH", "/api/v1/businesses/{id}/connectors/{cid}", parameters, params.updateConnector, "application/json", true, "management", false, null, new TypeReference<Connector>() {});
  }
  public Connector update(BusinessConnectorsUpdateParams params) { return update(params, RequestOptions.DEFAULT); }
  public Connector update(BusinessConnectorsUpdateParams params, RequestOptions options) { return transport.send(updateRequest(params), options); }
  public CompletableFuture<Connector> updateAsync(BusinessConnectorsUpdateParams params) { return updateAsync(params, RequestOptions.DEFAULT); }
  public CompletableFuture<Connector> updateAsync(BusinessConnectorsUpdateParams params, RequestOptions options) { return transport.sendAsync(updateRequest(params), options); }

}
